// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClsBoard.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#import <Protobuf/GPBProtocolBuffers.h>

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class TBPageBoardAddC2S_GraphicData;
@class TBPageBoardAddS2C_GraphicData;
@class TBPageBoardEditC2S_GraphicData;
@class TBPageBoardEditS2C_GraphicData;
@class TBPageBoardListChangeNotify_PageItem;
@class TBPageBoardNotify_GrapicData;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - ClsBoardRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface ClsBoardRoot : GPBRootObject
@end

#pragma mark - TBPageBoardNotify

typedef GPB_ENUM(TBPageBoardNotify_FieldNumber) {
  TBPageBoardNotify_FieldNumber_TextbookId = 1,
  TBPageBoardNotify_FieldNumber_Page = 2,
  TBPageBoardNotify_FieldNumber_Operate = 3,
  TBPageBoardNotify_FieldNumber_VecGraphicArray = 4,
};

/**
 * 白板数据通知
 **/
@interface TBPageBoardNotify : GPBMessage

@property(nonatomic, readwrite) uint32_t textbookId;

@property(nonatomic, readwrite) uint32_t page;

@property(nonatomic, readwrite) uint32_t operate;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<TBPageBoardNotify_GrapicData*> *vecGraphicArray;
/** The number of items in @c vecGraphicArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger vecGraphicArray_Count;

@end

#pragma mark - TBPageBoardNotify_GrapicData

typedef GPB_ENUM(TBPageBoardNotify_GrapicData_FieldNumber) {
  TBPageBoardNotify_GrapicData_FieldNumber_Seq = 1,
  TBPageBoardNotify_GrapicData_FieldNumber_Uid = 2,
  TBPageBoardNotify_GrapicData_FieldNumber_Time = 3,
  TBPageBoardNotify_GrapicData_FieldNumber_StrData = 4,
  TBPageBoardNotify_GrapicData_FieldNumber_ByteData = 5,
};

@interface TBPageBoardNotify_GrapicData : GPBMessage

@property(nonatomic, readwrite) uint32_t seq;

@property(nonatomic, readwrite) uint64_t uid;

@property(nonatomic, readwrite) uint64_t time;

@property(nonatomic, readwrite, copy, null_resettable) NSString *strData;

@property(nonatomic, readwrite, copy, null_resettable) NSData *byteData;

@end

#pragma mark - TBPageBoardGetC2S

typedef GPB_ENUM(TBPageBoardGetC2S_FieldNumber) {
  TBPageBoardGetC2S_FieldNumber_TextbookId = 1,
  TBPageBoardGetC2S_FieldNumber_Page = 2,
};

@interface TBPageBoardGetC2S : GPBMessage

@property(nonatomic, readwrite) uint32_t textbookId;

@property(nonatomic, readwrite) uint32_t page;

@end

#pragma mark - TBPageBoardAddC2S

typedef GPB_ENUM(TBPageBoardAddC2S_FieldNumber) {
  TBPageBoardAddC2S_FieldNumber_TextbookId = 1,
  TBPageBoardAddC2S_FieldNumber_Page = 2,
  TBPageBoardAddC2S_FieldNumber_VecGraphicArray = 3,
};

@interface TBPageBoardAddC2S : GPBMessage

@property(nonatomic, readwrite) uint32_t textbookId;

@property(nonatomic, readwrite) uint32_t page;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<TBPageBoardAddC2S_GraphicData*> *vecGraphicArray;
/** The number of items in @c vecGraphicArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger vecGraphicArray_Count;

@end

#pragma mark - TBPageBoardAddC2S_GraphicData

typedef GPB_ENUM(TBPageBoardAddC2S_GraphicData_FieldNumber) {
  TBPageBoardAddC2S_GraphicData_FieldNumber_CliSeq = 1,
  TBPageBoardAddC2S_GraphicData_FieldNumber_StrData = 2,
  TBPageBoardAddC2S_GraphicData_FieldNumber_ByteData = 3,
};

@interface TBPageBoardAddC2S_GraphicData : GPBMessage

@property(nonatomic, readwrite) uint32_t cliSeq;

@property(nonatomic, readwrite, copy, null_resettable) NSString *strData;

@property(nonatomic, readwrite, copy, null_resettable) NSData *byteData;

@end

#pragma mark - TBPageBoardAddS2C

typedef GPB_ENUM(TBPageBoardAddS2C_FieldNumber) {
  TBPageBoardAddS2C_FieldNumber_RspCode = 1,
  TBPageBoardAddS2C_FieldNumber_TextbookId = 2,
  TBPageBoardAddS2C_FieldNumber_Page = 3,
  TBPageBoardAddS2C_FieldNumber_VecGraphicArray = 4,
};

@interface TBPageBoardAddS2C : GPBMessage

@property(nonatomic, readwrite) uint32_t rspCode;

@property(nonatomic, readwrite) uint32_t textbookId;

@property(nonatomic, readwrite) uint32_t page;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<TBPageBoardAddS2C_GraphicData*> *vecGraphicArray;
/** The number of items in @c vecGraphicArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger vecGraphicArray_Count;

@end

#pragma mark - TBPageBoardAddS2C_GraphicData

typedef GPB_ENUM(TBPageBoardAddS2C_GraphicData_FieldNumber) {
  TBPageBoardAddS2C_GraphicData_FieldNumber_CliSeq = 1,
  TBPageBoardAddS2C_GraphicData_FieldNumber_Seq = 2,
  TBPageBoardAddS2C_GraphicData_FieldNumber_Time = 3,
};

@interface TBPageBoardAddS2C_GraphicData : GPBMessage

@property(nonatomic, readwrite) uint32_t cliSeq;

@property(nonatomic, readwrite) uint32_t seq;

@property(nonatomic, readwrite) uint64_t time;

@end

#pragma mark - TBPageBoardDelC2S

typedef GPB_ENUM(TBPageBoardDelC2S_FieldNumber) {
  TBPageBoardDelC2S_FieldNumber_TextbookId = 1,
  TBPageBoardDelC2S_FieldNumber_Page = 2,
  TBPageBoardDelC2S_FieldNumber_VecSeqArray = 3,
};

@interface TBPageBoardDelC2S : GPBMessage

@property(nonatomic, readwrite) uint32_t textbookId;

@property(nonatomic, readwrite) uint32_t page;

@property(nonatomic, readwrite, strong, null_resettable) GPBUInt32Array *vecSeqArray;
/** The number of items in @c vecSeqArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger vecSeqArray_Count;

@end

#pragma mark - TBPageBoardDelS2C

typedef GPB_ENUM(TBPageBoardDelS2C_FieldNumber) {
  TBPageBoardDelS2C_FieldNumber_RspCode = 1,
  TBPageBoardDelS2C_FieldNumber_TextbookId = 2,
  TBPageBoardDelS2C_FieldNumber_Page = 3,
  TBPageBoardDelS2C_FieldNumber_VecSeqArray = 4,
};

@interface TBPageBoardDelS2C : GPBMessage

@property(nonatomic, readwrite) uint32_t rspCode;

@property(nonatomic, readwrite) uint32_t textbookId;

@property(nonatomic, readwrite) uint32_t page;

@property(nonatomic, readwrite, strong, null_resettable) GPBUInt32Array *vecSeqArray;
/** The number of items in @c vecSeqArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger vecSeqArray_Count;

@end

#pragma mark - TBPageBoardEditC2S

typedef GPB_ENUM(TBPageBoardEditC2S_FieldNumber) {
  TBPageBoardEditC2S_FieldNumber_TextbookId = 1,
  TBPageBoardEditC2S_FieldNumber_Page = 2,
  TBPageBoardEditC2S_FieldNumber_VecGraphicArray = 3,
};

@interface TBPageBoardEditC2S : GPBMessage

@property(nonatomic, readwrite) uint32_t textbookId;

@property(nonatomic, readwrite) uint32_t page;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<TBPageBoardEditC2S_GraphicData*> *vecGraphicArray;
/** The number of items in @c vecGraphicArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger vecGraphicArray_Count;

@end

#pragma mark - TBPageBoardEditC2S_GraphicData

typedef GPB_ENUM(TBPageBoardEditC2S_GraphicData_FieldNumber) {
  TBPageBoardEditC2S_GraphicData_FieldNumber_Seq = 1,
  TBPageBoardEditC2S_GraphicData_FieldNumber_StrData = 2,
  TBPageBoardEditC2S_GraphicData_FieldNumber_ByteData = 3,
};

@interface TBPageBoardEditC2S_GraphicData : GPBMessage

@property(nonatomic, readwrite) uint32_t seq;

@property(nonatomic, readwrite, copy, null_resettable) NSString *strData;

@property(nonatomic, readwrite, copy, null_resettable) NSData *byteData;

@end

#pragma mark - TBPageBoardEditS2C

typedef GPB_ENUM(TBPageBoardEditS2C_FieldNumber) {
  TBPageBoardEditS2C_FieldNumber_RspCode = 1,
  TBPageBoardEditS2C_FieldNumber_TextbookId = 2,
  TBPageBoardEditS2C_FieldNumber_Page = 3,
  TBPageBoardEditS2C_FieldNumber_VecGraphicArray = 4,
};

@interface TBPageBoardEditS2C : GPBMessage

@property(nonatomic, readwrite) uint32_t rspCode;

@property(nonatomic, readwrite) uint32_t textbookId;

@property(nonatomic, readwrite) uint32_t page;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<TBPageBoardEditS2C_GraphicData*> *vecGraphicArray;
/** The number of items in @c vecGraphicArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger vecGraphicArray_Count;

@end

#pragma mark - TBPageBoardEditS2C_GraphicData

typedef GPB_ENUM(TBPageBoardEditS2C_GraphicData_FieldNumber) {
  TBPageBoardEditS2C_GraphicData_FieldNumber_Seq = 1,
  TBPageBoardEditS2C_GraphicData_FieldNumber_Time = 2,
};

@interface TBPageBoardEditS2C_GraphicData : GPBMessage

@property(nonatomic, readwrite) uint32_t seq;

@property(nonatomic, readwrite) uint64_t time;

@end

#pragma mark - TBPageBoardClearC2S

typedef GPB_ENUM(TBPageBoardClearC2S_FieldNumber) {
  TBPageBoardClearC2S_FieldNumber_TextbookId = 1,
  TBPageBoardClearC2S_FieldNumber_Page = 2,
};

/**
 * 清空白板数据
 **/
@interface TBPageBoardClearC2S : GPBMessage

@property(nonatomic, readwrite) uint32_t textbookId;

@property(nonatomic, readwrite) uint32_t page;

@end

#pragma mark - TBPageBoardClearS2C

typedef GPB_ENUM(TBPageBoardClearS2C_FieldNumber) {
  TBPageBoardClearS2C_FieldNumber_RspCode = 1,
  TBPageBoardClearS2C_FieldNumber_TextbookId = 2,
  TBPageBoardClearS2C_FieldNumber_Page = 3,
};

@interface TBPageBoardClearS2C : GPBMessage

@property(nonatomic, readwrite) uint32_t rspCode;

@property(nonatomic, readwrite) uint32_t textbookId;

@property(nonatomic, readwrite) uint32_t page;

@end

#pragma mark - TBPageBoardSetPageC2S

typedef GPB_ENUM(TBPageBoardSetPageC2S_FieldNumber) {
  TBPageBoardSetPageC2S_FieldNumber_TextbookId = 1,
  TBPageBoardSetPageC2S_FieldNumber_Page = 2,
};

/**
 * 0x00400060
 **/
@interface TBPageBoardSetPageC2S : GPBMessage

@property(nonatomic, readwrite) uint32_t textbookId;

@property(nonatomic, readwrite) uint32_t page;

@end

#pragma mark - TBPageBoardSetPageS2C

typedef GPB_ENUM(TBPageBoardSetPageS2C_FieldNumber) {
  TBPageBoardSetPageS2C_FieldNumber_RspCode = 1,
  TBPageBoardSetPageS2C_FieldNumber_TextbookId = 2,
  TBPageBoardSetPageS2C_FieldNumber_Page = 3,
  TBPageBoardSetPageS2C_FieldNumber_Version = 4,
};

/**
 * 设置当前使用的教材+课件页码
 * 0x00400061
 **/
@interface TBPageBoardSetPageS2C : GPBMessage

@property(nonatomic, readwrite) uint32_t rspCode;

@property(nonatomic, readwrite) uint32_t textbookId;

@property(nonatomic, readwrite) uint32_t page;

@property(nonatomic, readwrite) uint32_t version;

@end

#pragma mark - TBPageBoardSetPageNotify

typedef GPB_ENUM(TBPageBoardSetPageNotify_FieldNumber) {
  TBPageBoardSetPageNotify_FieldNumber_TextbookId = 1,
  TBPageBoardSetPageNotify_FieldNumber_Page = 2,
  TBPageBoardSetPageNotify_FieldNumber_Version = 3,
  TBPageBoardSetPageNotify_FieldNumber_Uid = 4,
};

/**
 * 0x00400062
 **/
@interface TBPageBoardSetPageNotify : GPBMessage

@property(nonatomic, readwrite) uint32_t textbookId;

@property(nonatomic, readwrite) uint32_t page;

@property(nonatomic, readwrite) uint32_t version;

@property(nonatomic, readwrite) uint64_t uid;

@end

#pragma mark - TBPageBoardAddBlankPageC2S

typedef GPB_ENUM(TBPageBoardAddBlankPageC2S_FieldNumber) {
  TBPageBoardAddBlankPageC2S_FieldNumber_TextbookId = 1,
  TBPageBoardAddBlankPageC2S_FieldNumber_Page = 2,
  TBPageBoardAddBlankPageC2S_FieldNumber_Num = 3,
};

/**
 * 添加课件空白页
 * 0x00400063
 **/
@interface TBPageBoardAddBlankPageC2S : GPBMessage

@property(nonatomic, readwrite) uint32_t textbookId;

@property(nonatomic, readwrite) uint32_t page;

@property(nonatomic, readwrite) uint32_t num;

@end

#pragma mark - TBPageBoardAddBlankPageS2C

typedef GPB_ENUM(TBPageBoardAddBlankPageS2C_FieldNumber) {
  TBPageBoardAddBlankPageS2C_FieldNumber_RspCode = 1,
  TBPageBoardAddBlankPageS2C_FieldNumber_TextbookId = 2,
  TBPageBoardAddBlankPageS2C_FieldNumber_Page = 3,
  TBPageBoardAddBlankPageS2C_FieldNumber_VecPageArray = 4,
  TBPageBoardAddBlankPageS2C_FieldNumber_Version = 5,
};

/**
 * 添加课件空白页
 * 0x00400064
 **/
@interface TBPageBoardAddBlankPageS2C : GPBMessage

@property(nonatomic, readwrite) uint32_t rspCode;

@property(nonatomic, readwrite) uint32_t textbookId;

@property(nonatomic, readwrite) uint32_t page;

@property(nonatomic, readwrite, strong, null_resettable) GPBUInt32Array *vecPageArray;
/** The number of items in @c vecPageArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger vecPageArray_Count;

@property(nonatomic, readwrite) uint32_t version;

@end

#pragma mark - TBPageBoardDelBlankPageC2S

typedef GPB_ENUM(TBPageBoardDelBlankPageC2S_FieldNumber) {
  TBPageBoardDelBlankPageC2S_FieldNumber_TextbookId = 1,
  TBPageBoardDelBlankPageC2S_FieldNumber_VecPageArray = 2,
};

/**
 * 删除课件空白页
 * 0x00400065
 **/
@interface TBPageBoardDelBlankPageC2S : GPBMessage

@property(nonatomic, readwrite) uint32_t textbookId;

@property(nonatomic, readwrite, strong, null_resettable) GPBUInt32Array *vecPageArray;
/** The number of items in @c vecPageArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger vecPageArray_Count;

@end

#pragma mark - TBPageBoardDelBlankPageS2C

typedef GPB_ENUM(TBPageBoardDelBlankPageS2C_FieldNumber) {
  TBPageBoardDelBlankPageS2C_FieldNumber_RspCode = 1,
  TBPageBoardDelBlankPageS2C_FieldNumber_TextbookId = 2,
  TBPageBoardDelBlankPageS2C_FieldNumber_VecPageArray = 3,
  TBPageBoardDelBlankPageS2C_FieldNumber_Version = 4,
};

/**
 * 删除课件空白页
 * 0x00400066
 **/
@interface TBPageBoardDelBlankPageS2C : GPBMessage

@property(nonatomic, readwrite) uint32_t rspCode;

@property(nonatomic, readwrite) uint32_t textbookId;

@property(nonatomic, readwrite, strong, null_resettable) GPBUInt32Array *vecPageArray;
/** The number of items in @c vecPageArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger vecPageArray_Count;

@property(nonatomic, readwrite) uint32_t version;

@end

#pragma mark - TBPageBoardListChangeNotify

typedef GPB_ENUM(TBPageBoardListChangeNotify_FieldNumber) {
  TBPageBoardListChangeNotify_FieldNumber_TextbookId = 1,
  TBPageBoardListChangeNotify_FieldNumber_PageListArray = 2,
  TBPageBoardListChangeNotify_FieldNumber_Version = 3,
};

/**
 * 课件页列表（课件页->教材页、空白页映射关系）变更通知
 * 0x00400067
 **/
@interface TBPageBoardListChangeNotify : GPBMessage

@property(nonatomic, readwrite) uint32_t textbookId;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<TBPageBoardListChangeNotify_PageItem*> *pageListArray;
/** The number of items in @c pageListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger pageListArray_Count;

@property(nonatomic, readwrite) uint32_t version;

@end

#pragma mark - TBPageBoardListChangeNotify_PageItem

typedef GPB_ENUM(TBPageBoardListChangeNotify_PageItem_FieldNumber) {
  TBPageBoardListChangeNotify_PageItem_FieldNumber_Page = 1,
  TBPageBoardListChangeNotify_PageItem_FieldNumber_CrswarePage = 2,
  TBPageBoardListChangeNotify_PageItem_FieldNumber_Uid = 3,
  TBPageBoardListChangeNotify_PageItem_FieldNumber_Time = 4,
};

@interface TBPageBoardListChangeNotify_PageItem : GPBMessage

@property(nonatomic, readwrite) uint32_t page;

@property(nonatomic, readwrite) int32_t crswarePage;

@property(nonatomic, readwrite) uint64_t uid;

@property(nonatomic, readwrite) uint64_t time;

@end

#pragma mark - TBPageBoardSetCursorPosC2S

typedef GPB_ENUM(TBPageBoardSetCursorPosC2S_FieldNumber) {
  TBPageBoardSetCursorPosC2S_FieldNumber_TextbookId = 1,
  TBPageBoardSetCursorPosC2S_FieldNumber_Page = 2,
  TBPageBoardSetCursorPosC2S_FieldNumber_PosX = 3,
  TBPageBoardSetCursorPosC2S_FieldNumber_PosY = 4,
};

/**
 * 设置教材页的鼠标位置
 * 0x0040006C
 **/
@interface TBPageBoardSetCursorPosC2S : GPBMessage

@property(nonatomic, readwrite) uint32_t textbookId;

@property(nonatomic, readwrite) uint32_t page;

@property(nonatomic, readwrite, copy, null_resettable) NSString *posX;

@property(nonatomic, readwrite, copy, null_resettable) NSString *posY;

@end

#pragma mark - TBPageBoardSetCursorPosS2C

typedef GPB_ENUM(TBPageBoardSetCursorPosS2C_FieldNumber) {
  TBPageBoardSetCursorPosS2C_FieldNumber_RspCode = 1,
  TBPageBoardSetCursorPosS2C_FieldNumber_TextbookId = 2,
  TBPageBoardSetCursorPosS2C_FieldNumber_Page = 3,
};

/**
 * 设置教材页的鼠标位置
 * 0x0040006D
 **/
@interface TBPageBoardSetCursorPosS2C : GPBMessage

@property(nonatomic, readwrite) uint32_t rspCode;

@property(nonatomic, readwrite) uint32_t textbookId;

@property(nonatomic, readwrite) uint32_t page;

@end

#pragma mark - TBPageBoardSetCursorPosNotify

typedef GPB_ENUM(TBPageBoardSetCursorPosNotify_FieldNumber) {
  TBPageBoardSetCursorPosNotify_FieldNumber_TextbookId = 1,
  TBPageBoardSetCursorPosNotify_FieldNumber_Page = 2,
  TBPageBoardSetCursorPosNotify_FieldNumber_PosX = 3,
  TBPageBoardSetCursorPosNotify_FieldNumber_PosY = 4,
  TBPageBoardSetCursorPosNotify_FieldNumber_Uid = 5,
};

/**
 * 下发教材页的鼠标位置通知
 * 0x0040006E
 **/
@interface TBPageBoardSetCursorPosNotify : GPBMessage

@property(nonatomic, readwrite) uint32_t textbookId;

@property(nonatomic, readwrite) uint32_t page;

@property(nonatomic, readwrite, copy, null_resettable) NSString *posX;

@property(nonatomic, readwrite, copy, null_resettable) NSString *posY;

@property(nonatomic, readwrite) uint64_t uid;

@end

#pragma mark - TBPageBoardReqSyncCurPageC2S

typedef GPB_ENUM(TBPageBoardReqSyncCurPageC2S_FieldNumber) {
  TBPageBoardReqSyncCurPageC2S_FieldNumber_TbPageVerion = 1,
  TBPageBoardReqSyncCurPageC2S_FieldNumber_TextbookId = 2,
  TBPageBoardReqSyncCurPageC2S_FieldNumber_PageListVerion = 3,
};

/**
 * 定时请求同步当前课件的相关设置（当前教材、当前页码、课件页列表）
 * 0x00400068
 **/
@interface TBPageBoardReqSyncCurPageC2S : GPBMessage

@property(nonatomic, readwrite) uint32_t tbPageVerion;

@property(nonatomic, readwrite) uint32_t textbookId;

@property(nonatomic, readwrite) uint32_t pageListVerion;

@end

#pragma mark - TBPageBoardSetScrollPosC2S

typedef GPB_ENUM(TBPageBoardSetScrollPosC2S_FieldNumber) {
  TBPageBoardSetScrollPosC2S_FieldNumber_TextbookId = 1,
  TBPageBoardSetScrollPosC2S_FieldNumber_Page = 2,
  TBPageBoardSetScrollPosC2S_FieldNumber_PosX = 3,
  TBPageBoardSetScrollPosC2S_FieldNumber_PosY = 4,
};

/**
 * 设置课件页的滚动条位置
 * 0x00400069
 **/
@interface TBPageBoardSetScrollPosC2S : GPBMessage

@property(nonatomic, readwrite) uint32_t textbookId;

@property(nonatomic, readwrite) uint32_t page;

@property(nonatomic, readwrite, copy, null_resettable) NSString *posX;

@property(nonatomic, readwrite, copy, null_resettable) NSString *posY;

@end

#pragma mark - TBPageBoardSetScrollPosS2C

typedef GPB_ENUM(TBPageBoardSetScrollPosS2C_FieldNumber) {
  TBPageBoardSetScrollPosS2C_FieldNumber_RspCode = 1,
  TBPageBoardSetScrollPosS2C_FieldNumber_TextbookId = 2,
  TBPageBoardSetScrollPosS2C_FieldNumber_Page = 3,
};

/**
 * 设置课件页的滚动条位置
 * 0x0040006A
 **/
@interface TBPageBoardSetScrollPosS2C : GPBMessage

@property(nonatomic, readwrite) uint32_t rspCode;

@property(nonatomic, readwrite) uint32_t textbookId;

@property(nonatomic, readwrite) uint32_t page;

@end

#pragma mark - TBPageBoardScrollPosNotify

typedef GPB_ENUM(TBPageBoardScrollPosNotify_FieldNumber) {
  TBPageBoardScrollPosNotify_FieldNumber_TextbookId = 1,
  TBPageBoardScrollPosNotify_FieldNumber_Page = 2,
  TBPageBoardScrollPosNotify_FieldNumber_PosX = 3,
  TBPageBoardScrollPosNotify_FieldNumber_PosY = 4,
  TBPageBoardScrollPosNotify_FieldNumber_Uid = 5,
};

/**
 * 下发教材页的滚动条位置通知
 * 0x0040006B
 **/
@interface TBPageBoardScrollPosNotify : GPBMessage

@property(nonatomic, readwrite) uint32_t textbookId;

@property(nonatomic, readwrite) uint32_t page;

@property(nonatomic, readwrite, copy, null_resettable) NSString *posX;

@property(nonatomic, readwrite, copy, null_resettable) NSString *posY;

@property(nonatomic, readwrite) uint64_t uid;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
