// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClsTextbook.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#import <Protobuf/GPBProtocolBuffers.h>

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class TBPageListNotify_PageItem;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - ClsTextbookRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface ClsTextbookRoot : GPBRootObject
@end

#pragma mark - TBSetPageC2S

typedef GPB_ENUM(TBSetPageC2S_FieldNumber) {
  TBSetPageC2S_FieldNumber_TextbookId = 1,
  TBSetPageC2S_FieldNumber_Page = 2,
  TBSetPageC2S_FieldNumber_SubPage = 3,
};

/**
 * 0x001300B0
 **/
@interface TBSetPageC2S : GPBMessage

@property(nonatomic, readwrite) uint32_t textbookId;

@property(nonatomic, readwrite) uint32_t page;

@property(nonatomic, readwrite) uint32_t subPage;

@end

#pragma mark - TBSetPageS2C

typedef GPB_ENUM(TBSetPageS2C_FieldNumber) {
  TBSetPageS2C_FieldNumber_RspCode = 1,
  TBSetPageS2C_FieldNumber_TextbookId = 2,
  TBSetPageS2C_FieldNumber_Page = 3,
  TBSetPageS2C_FieldNumber_Version = 4,
  TBSetPageS2C_FieldNumber_SubPage = 5,
};

/**
 * 0x001300B1
 **/
@interface TBSetPageS2C : GPBMessage

@property(nonatomic, readwrite) uint32_t rspCode;

@property(nonatomic, readwrite) uint32_t textbookId;

@property(nonatomic, readwrite) uint32_t page;

@property(nonatomic, readwrite) uint32_t version;

@property(nonatomic, readwrite) uint32_t subPage;

@end

#pragma mark - TBPageNotify

typedef GPB_ENUM(TBPageNotify_FieldNumber) {
  TBPageNotify_FieldNumber_TextbookId = 1,
  TBPageNotify_FieldNumber_Page = 2,
  TBPageNotify_FieldNumber_Version = 3,
  TBPageNotify_FieldNumber_Uid = 4,
  TBPageNotify_FieldNumber_SubPage = 5,
};

/**
 * 0x001300B2
 **/
@interface TBPageNotify : GPBMessage

@property(nonatomic, readwrite) uint32_t textbookId;

@property(nonatomic, readwrite) uint32_t page;

@property(nonatomic, readwrite) uint32_t version;

@property(nonatomic, readwrite) uint64_t uid;

@property(nonatomic, readwrite) uint32_t subPage;

@end

#pragma mark - TBWPageAddC2S

typedef GPB_ENUM(TBWPageAddC2S_FieldNumber) {
  TBWPageAddC2S_FieldNumber_TextbookId = 1,
  TBWPageAddC2S_FieldNumber_Page = 2,
  TBWPageAddC2S_FieldNumber_Num = 3,
};

/**
 * 0x001300B3
 **/
@interface TBWPageAddC2S : GPBMessage

@property(nonatomic, readwrite) uint32_t textbookId;

@property(nonatomic, readwrite) uint32_t page;

@property(nonatomic, readwrite) uint32_t num;

@end

#pragma mark - TBWPageAddS2C

typedef GPB_ENUM(TBWPageAddS2C_FieldNumber) {
  TBWPageAddS2C_FieldNumber_RspCode = 1,
  TBWPageAddS2C_FieldNumber_TextbookId = 2,
  TBWPageAddS2C_FieldNumber_Page = 3,
  TBWPageAddS2C_FieldNumber_VecPageArray = 4,
  TBWPageAddS2C_FieldNumber_Version = 5,
};

/**
 * 0x001300B4
 **/
@interface TBWPageAddS2C : GPBMessage

@property(nonatomic, readwrite) uint32_t rspCode;

@property(nonatomic, readwrite) uint32_t textbookId;

@property(nonatomic, readwrite) uint32_t page;

@property(nonatomic, readwrite, strong, null_resettable) GPBUInt32Array *vecPageArray;
/** The number of items in @c vecPageArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger vecPageArray_Count;

@property(nonatomic, readwrite) uint32_t version;

@end

#pragma mark - TBWPageDelC2S

typedef GPB_ENUM(TBWPageDelC2S_FieldNumber) {
  TBWPageDelC2S_FieldNumber_TextbookId = 1,
  TBWPageDelC2S_FieldNumber_VecPageArray = 2,
};

/**
 * 0x001300B5
 **/
@interface TBWPageDelC2S : GPBMessage

@property(nonatomic, readwrite) uint32_t textbookId;

@property(nonatomic, readwrite, strong, null_resettable) GPBUInt32Array *vecPageArray;
/** The number of items in @c vecPageArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger vecPageArray_Count;

@end

#pragma mark - TBWPageDelS2C

typedef GPB_ENUM(TBWPageDelS2C_FieldNumber) {
  TBWPageDelS2C_FieldNumber_RspCode = 1,
  TBWPageDelS2C_FieldNumber_TextbookId = 2,
  TBWPageDelS2C_FieldNumber_VecPageArray = 3,
  TBWPageDelS2C_FieldNumber_Version = 4,
};

/**
 * 0x001300B6
 **/
@interface TBWPageDelS2C : GPBMessage

@property(nonatomic, readwrite) uint32_t rspCode;

@property(nonatomic, readwrite) uint32_t textbookId;

@property(nonatomic, readwrite, strong, null_resettable) GPBUInt32Array *vecPageArray;
/** The number of items in @c vecPageArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger vecPageArray_Count;

@property(nonatomic, readwrite) uint32_t version;

@end

#pragma mark - TBPageListNotify

typedef GPB_ENUM(TBPageListNotify_FieldNumber) {
  TBPageListNotify_FieldNumber_TextbookId = 1,
  TBPageListNotify_FieldNumber_PageListArray = 2,
  TBPageListNotify_FieldNumber_Version = 3,
};

/**
 * 0x001300B7
 **/
@interface TBPageListNotify : GPBMessage

@property(nonatomic, readwrite) uint32_t textbookId;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<TBPageListNotify_PageItem*> *pageListArray;
/** The number of items in @c pageListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger pageListArray_Count;

@property(nonatomic, readwrite) uint32_t version;

@end

#pragma mark - TBPageListNotify_PageItem

typedef GPB_ENUM(TBPageListNotify_PageItem_FieldNumber) {
  TBPageListNotify_PageItem_FieldNumber_Page = 1,
  TBPageListNotify_PageItem_FieldNumber_CrswarePage = 2,
  TBPageListNotify_PageItem_FieldNumber_Uid = 3,
  TBPageListNotify_PageItem_FieldNumber_Time = 4,
  TBPageListNotify_PageItem_FieldNumber_Seq = 5,
};

@interface TBPageListNotify_PageItem : GPBMessage

@property(nonatomic, readwrite) uint32_t page;

@property(nonatomic, readwrite) int32_t crswarePage;

@property(nonatomic, readwrite) uint64_t uid;

@property(nonatomic, readwrite) uint64_t time;

@property(nonatomic, readwrite) uint32_t seq;

@end

#pragma mark - CrswareSync

typedef GPB_ENUM(CrswareSync_FieldNumber) {
  CrswareSync_FieldNumber_TbPageVerion = 1,
  CrswareSync_FieldNumber_TextbookId = 2,
  CrswareSync_FieldNumber_PageListVerion = 3,
};

/**
 * 0x001300B8
 **/
@interface CrswareSync : GPBMessage

@property(nonatomic, readwrite) uint32_t tbPageVerion;

@property(nonatomic, readwrite) uint32_t textbookId;

@property(nonatomic, readwrite) uint32_t pageListVerion;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
