// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DoubleTOSCls.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#import <Protobuf/GPBProtocolBuffers.h>

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class DoubleTUserInfo;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - DoubleTosclsRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface DoubleTosclsRoot : GPBRootObject
@end

#pragma mark - OSClsEnterC2S

typedef GPB_ENUM(OSClsEnterC2S_FieldNumber) {
  OSClsEnterC2S_FieldNumber_CusData = 1,
};

/**
 * 0x00450020
 **/
@interface OSClsEnterC2S : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *cusData;

@end

#pragma mark - OSClsEnterS2C

typedef GPB_ENUM(OSClsEnterS2C_FieldNumber) {
  OSClsEnterS2C_FieldNumber_RspCode = 1,
  OSClsEnterS2C_FieldNumber_UserInfo = 2,
};

/**
 * 0x00450021
 **/
@interface OSClsEnterS2C : GPBMessage

@property(nonatomic, readwrite) uint32_t rspCode;

@property(nonatomic, readwrite, strong, null_resettable) DoubleTUserInfo *userInfo;
/** Test to see if @c userInfo has been set. */
@property(nonatomic, readwrite) BOOL hasUserInfo;

@end

#pragma mark - OSClsEnterComplete

/**
 * 0x00450022
 **/
@interface OSClsEnterComplete : GPBMessage

@end

#pragma mark - OSClsGetAssistListC2S

typedef GPB_ENUM(OSClsGetAssistListC2S_FieldNumber) {
  OSClsGetAssistListC2S_FieldNumber_Version = 1,
};

/**
 * 0x00450033
 **/
@interface OSClsGetAssistListC2S : GPBMessage

@property(nonatomic, readwrite) uint32_t version;

@end

#pragma mark - OSClsGetAssistListS2C

typedef GPB_ENUM(OSClsGetAssistListS2C_FieldNumber) {
  OSClsGetAssistListS2C_FieldNumber_RspCode = 1,
  OSClsGetAssistListS2C_FieldNumber_Version = 2,
  OSClsGetAssistListS2C_FieldNumber_VecAssistArray = 3,
};

/**
 * 0x00450034
 **/
@interface OSClsGetAssistListS2C : GPBMessage

@property(nonatomic, readwrite) uint32_t rspCode;

@property(nonatomic, readwrite) uint32_t version;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<DoubleTUserInfo*> *vecAssistArray;
/** The number of items in @c vecAssistArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger vecAssistArray_Count;

@end

#pragma mark - OSClsAssistListNotify

typedef GPB_ENUM(OSClsAssistListNotify_FieldNumber) {
  OSClsAssistListNotify_FieldNumber_Version = 1,
};

/**
 * 0x00450035
 **/
@interface OSClsAssistListNotify : GPBMessage

@property(nonatomic, readwrite) uint32_t version;

@end

#pragma mark - OSClsGetStuListC2S

typedef GPB_ENUM(OSClsGetStuListC2S_FieldNumber) {
  OSClsGetStuListC2S_FieldNumber_Version = 1,
};

/**
 * 0x00450036
 **/
@interface OSClsGetStuListC2S : GPBMessage

@property(nonatomic, readwrite) uint32_t version;

@end

#pragma mark - OSClsGetStuListS2C

typedef GPB_ENUM(OSClsGetStuListS2C_FieldNumber) {
  OSClsGetStuListS2C_FieldNumber_RspCode = 1,
  OSClsGetStuListS2C_FieldNumber_Version = 2,
  OSClsGetStuListS2C_FieldNumber_VecStuArray = 3,
};

/**
 * 0x00450037
 **/
@interface OSClsGetStuListS2C : GPBMessage

@property(nonatomic, readwrite) uint32_t rspCode;

@property(nonatomic, readwrite) uint32_t version;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<DoubleTUserInfo*> *vecStuArray;
/** The number of items in @c vecStuArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger vecStuArray_Count;

@end

#pragma mark - OSClsStuListNotify

typedef GPB_ENUM(OSClsStuListNotify_FieldNumber) {
  OSClsStuListNotify_FieldNumber_Version = 1,
};

/**
 * 0x00450038
 **/
@interface OSClsStuListNotify : GPBMessage

@property(nonatomic, readwrite) uint32_t version;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
