// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DoubleTClsStorage.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#import <Protobuf/GPBProtocolBuffers.h>

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class OClsAddConsistStorageC2S_ClsItem;
@class OClsAddStorageItem;
@class OClsDelConsistStorageC2S_ClsItem;
@class OClsStorageItem;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - DoubleTclsStorageRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface DoubleTclsStorageRoot : GPBRootObject
@end

#pragma mark - OClsGetConsistStorageC2S

typedef GPB_ENUM(OClsGetConsistStorageC2S_FieldNumber) {
  OClsGetConsistStorageC2S_FieldNumber_Version = 1,
};

/**
 * 0x004300C6、0x004400C6、0x004500C6
 **/
@interface OClsGetConsistStorageC2S : GPBMessage

@property(nonatomic, readwrite) uint32_t version;

@end

#pragma mark - OClsStorageItem

typedef GPB_ENUM(OClsStorageItem_FieldNumber) {
  OClsStorageItem_FieldNumber_State = 1,
  OClsStorageItem_FieldNumber_Key = 2,
  OClsStorageItem_FieldNumber_Value = 3,
  OClsStorageItem_FieldNumber_StrValue = 4,
  OClsStorageItem_FieldNumber_OwnerUid = 5,
  OClsStorageItem_FieldNumber_OwnerCid = 6,
  OClsStorageItem_FieldNumber_OwnerCtype = 7,
};

@interface OClsStorageItem : GPBMessage

@property(nonatomic, readwrite) uint32_t state;

@property(nonatomic, readwrite, copy, null_resettable) NSString *key;

@property(nonatomic, readwrite, copy, null_resettable) NSData *value;

@property(nonatomic, readwrite, copy, null_resettable) NSString *strValue;

@property(nonatomic, readwrite) uint64_t ownerUid;

@property(nonatomic, readwrite) uint64_t ownerCid;

@property(nonatomic, readwrite) uint32_t ownerCtype;

@end

#pragma mark - OClsGetConsistStorageS2C

typedef GPB_ENUM(OClsGetConsistStorageS2C_FieldNumber) {
  OClsGetConsistStorageS2C_FieldNumber_RspCode = 1,
  OClsGetConsistStorageS2C_FieldNumber_Version = 2,
  OClsGetConsistStorageS2C_FieldNumber_VecItemArray = 3,
};

/**
 * 0x004300C7、0x004400C7、0x004500C7
 **/
@interface OClsGetConsistStorageS2C : GPBMessage

@property(nonatomic, readwrite) uint32_t rspCode;

@property(nonatomic, readwrite) uint32_t version;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<OClsStorageItem*> *vecItemArray;
/** The number of items in @c vecItemArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger vecItemArray_Count;

@end

#pragma mark - OClsConsistStorageNotify

typedef GPB_ENUM(OClsConsistStorageNotify_FieldNumber) {
  OClsConsistStorageNotify_FieldNumber_Version = 1,
};

/**
 * 0x004300C8、0x004400C8、0x004500C8
 **/
@interface OClsConsistStorageNotify : GPBMessage

@property(nonatomic, readwrite) uint32_t version;

@end

#pragma mark - OClsAddStorageItem

typedef GPB_ENUM(OClsAddStorageItem_FieldNumber) {
  OClsAddStorageItem_FieldNumber_Key = 1,
  OClsAddStorageItem_FieldNumber_Value = 2,
  OClsAddStorageItem_FieldNumber_StrValue = 3,
};

@interface OClsAddStorageItem : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *key;

@property(nonatomic, readwrite, copy, null_resettable) NSData *value;

@property(nonatomic, readwrite, copy, null_resettable) NSString *strValue;

@end

#pragma mark - OClsAddConsistStorageC2S

typedef GPB_ENUM(OClsAddConsistStorageC2S_FieldNumber) {
  OClsAddConsistStorageC2S_FieldNumber_Scope = 1,
  OClsAddConsistStorageC2S_FieldNumber_VecClsArray = 2,
  OClsAddConsistStorageC2S_FieldNumber_VecItemArray = 3,
};

/**
 * 0x004300C9、0x004400C9、0x004500C9
 **/
@interface OClsAddConsistStorageC2S : GPBMessage

@property(nonatomic, readwrite) uint32_t scope;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<OClsAddConsistStorageC2S_ClsItem*> *vecClsArray;
/** The number of items in @c vecClsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger vecClsArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<OClsAddStorageItem*> *vecItemArray;
/** The number of items in @c vecItemArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger vecItemArray_Count;

@end

#pragma mark - OClsAddConsistStorageC2S_ClsItem

typedef GPB_ENUM(OClsAddConsistStorageC2S_ClsItem_FieldNumber) {
  OClsAddConsistStorageC2S_ClsItem_FieldNumber_Ctype = 1,
  OClsAddConsistStorageC2S_ClsItem_FieldNumber_Cid = 2,
};

@interface OClsAddConsistStorageC2S_ClsItem : GPBMessage

@property(nonatomic, readwrite) uint32_t ctype;

@property(nonatomic, readwrite) uint64_t cid;

@end

#pragma mark - OClsAddConsistStorageS2C

typedef GPB_ENUM(OClsAddConsistStorageS2C_FieldNumber) {
  OClsAddConsistStorageS2C_FieldNumber_RspCode = 1,
  OClsAddConsistStorageS2C_FieldNumber_Version = 2,
  OClsAddConsistStorageS2C_FieldNumber_VecFailedItemArray = 3,
};

/**
 * 0x004300CA、0x004400CA、0x004500CA
 **/
@interface OClsAddConsistStorageS2C : GPBMessage

@property(nonatomic, readwrite) uint32_t rspCode;

@property(nonatomic, readwrite) uint32_t version;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<OClsAddStorageItem*> *vecFailedItemArray;
/** The number of items in @c vecFailedItemArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger vecFailedItemArray_Count;

@end

#pragma mark - OClsDelConsistStorageC2S

typedef GPB_ENUM(OClsDelConsistStorageC2S_FieldNumber) {
  OClsDelConsistStorageC2S_FieldNumber_Scope = 1,
  OClsDelConsistStorageC2S_FieldNumber_VecClsArray = 2,
  OClsDelConsistStorageC2S_FieldNumber_VecKeyArray = 3,
};

/**
 * 0x004300CB、0x004400CB、0x004500CB
 **/
@interface OClsDelConsistStorageC2S : GPBMessage

@property(nonatomic, readwrite) uint32_t scope;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<OClsDelConsistStorageC2S_ClsItem*> *vecClsArray;
/** The number of items in @c vecClsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger vecClsArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *vecKeyArray;
/** The number of items in @c vecKeyArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger vecKeyArray_Count;

@end

#pragma mark - OClsDelConsistStorageC2S_ClsItem

typedef GPB_ENUM(OClsDelConsistStorageC2S_ClsItem_FieldNumber) {
  OClsDelConsistStorageC2S_ClsItem_FieldNumber_Ctype = 1,
  OClsDelConsistStorageC2S_ClsItem_FieldNumber_Cid = 2,
};

@interface OClsDelConsistStorageC2S_ClsItem : GPBMessage

@property(nonatomic, readwrite) uint32_t ctype;

@property(nonatomic, readwrite) uint64_t cid;

@end

#pragma mark - OClsDelConsistStorageS2C

typedef GPB_ENUM(OClsDelConsistStorageS2C_FieldNumber) {
  OClsDelConsistStorageS2C_FieldNumber_RspCode = 1,
  OClsDelConsistStorageS2C_FieldNumber_Version = 2,
  OClsDelConsistStorageS2C_FieldNumber_VecFailedKeyArray = 3,
};

/**
 * 0x004300CC、0x004400CC、0x004500CC
 **/
@interface OClsDelConsistStorageS2C : GPBMessage

@property(nonatomic, readwrite) uint32_t rspCode;

@property(nonatomic, readwrite) uint32_t version;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *vecFailedKeyArray;
/** The number of items in @c vecFailedKeyArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger vecFailedKeyArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
