// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DoubleTClsTextbook.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#import <Protobuf/GPBProtocolBuffers.h>

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class DoubleTClsCrswareInfo;
@class DoubleTClsTbPageListChangeNotify_DoubleTPageItem;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - DoubleTclsTextbookRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface DoubleTclsTextbookRoot : GPBRootObject
@end

#pragma mark - DoubleTClsCrswareInfo

typedef GPB_ENUM(DoubleTClsCrswareInfo_FieldNumber) {
  DoubleTClsCrswareInfo_FieldNumber_Id_p = 1,
  DoubleTClsCrswareInfo_FieldNumber_Type = 2,
  DoubleTClsCrswareInfo_FieldNumber_Name = 3,
  DoubleTClsCrswareInfo_FieldNumber_URL = 4,
  DoubleTClsCrswareInfo_FieldNumber_FileMd5 = 5,
  DoubleTClsCrswareInfo_FieldNumber_FileSize = 6,
  DoubleTClsCrswareInfo_FieldNumber_URLListArray = 7,
  DoubleTClsCrswareInfo_FieldNumber_ZipURLListArray = 8,
};

@interface DoubleTClsCrswareInfo : GPBMessage

@property(nonatomic, readwrite) uint32_t id_p;

@property(nonatomic, readwrite) uint32_t type;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite, copy, null_resettable) NSString *URL;

@property(nonatomic, readwrite, copy, null_resettable) NSString *fileMd5;

@property(nonatomic, readwrite) uint32_t fileSize;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *URLListArray;
/** The number of items in @c URLListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger URLListArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *zipURLListArray;
/** The number of items in @c zipURLListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger zipURLListArray_Count;

@end

#pragma mark - DoubleTClsGetCrswareListC2S

typedef GPB_ENUM(DoubleTClsGetCrswareListC2S_FieldNumber) {
  DoubleTClsGetCrswareListC2S_FieldNumber_Version = 1,
};

/**
 * 0x0043005A
 **/
@interface DoubleTClsGetCrswareListC2S : GPBMessage

@property(nonatomic, readwrite) uint32_t version;

@end

#pragma mark - DoubleTClsGetCrswareListS2C

typedef GPB_ENUM(DoubleTClsGetCrswareListS2C_FieldNumber) {
  DoubleTClsGetCrswareListS2C_FieldNumber_CrswareListArray = 1,
  DoubleTClsGetCrswareListS2C_FieldNumber_Version = 2,
};

/**
 * 0x0043005B
 **/
@interface DoubleTClsGetCrswareListS2C : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<DoubleTClsCrswareInfo*> *crswareListArray;
/** The number of items in @c crswareListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger crswareListArray_Count;

@property(nonatomic, readwrite) uint32_t version;

@end

#pragma mark - DoubleTClsCrswareListNotify

typedef GPB_ENUM(DoubleTClsCrswareListNotify_FieldNumber) {
  DoubleTClsCrswareListNotify_FieldNumber_Version = 1,
};

/**
 * 0x0043005C
 **/
@interface DoubleTClsCrswareListNotify : GPBMessage

@property(nonatomic, readwrite) uint32_t version;

@end

#pragma mark - DoubleTClsSetCurTbPageC2S

typedef GPB_ENUM(DoubleTClsSetCurTbPageC2S_FieldNumber) {
  DoubleTClsSetCurTbPageC2S_FieldNumber_TextbookId = 1,
  DoubleTClsSetCurTbPageC2S_FieldNumber_Page = 2,
  DoubleTClsSetCurTbPageC2S_FieldNumber_SubPage = 3,
};

/**
 * 设置当前使用的教材+课件页码
 * 0x00430060
 **/
@interface DoubleTClsSetCurTbPageC2S : GPBMessage

@property(nonatomic, readwrite) uint32_t textbookId;

@property(nonatomic, readwrite) uint32_t page;

@property(nonatomic, readwrite) uint32_t subPage;

@end

#pragma mark - DoubleTClsSetCurTbPageS2C

typedef GPB_ENUM(DoubleTClsSetCurTbPageS2C_FieldNumber) {
  DoubleTClsSetCurTbPageS2C_FieldNumber_RspCode = 1,
  DoubleTClsSetCurTbPageS2C_FieldNumber_TextbookId = 2,
  DoubleTClsSetCurTbPageS2C_FieldNumber_Page = 3,
  DoubleTClsSetCurTbPageS2C_FieldNumber_Version = 4,
  DoubleTClsSetCurTbPageS2C_FieldNumber_SubPage = 5,
};

/**
 * 设置当前使用的教材+课件页码
 * 0x00430061
 **/
@interface DoubleTClsSetCurTbPageS2C : GPBMessage

@property(nonatomic, readwrite) uint32_t rspCode;

@property(nonatomic, readwrite) uint32_t textbookId;

@property(nonatomic, readwrite) uint32_t page;

@property(nonatomic, readwrite) uint32_t version;

@property(nonatomic, readwrite) uint32_t subPage;

@end

#pragma mark - DoubleTClsCurTbPageNotify

typedef GPB_ENUM(DoubleTClsCurTbPageNotify_FieldNumber) {
  DoubleTClsCurTbPageNotify_FieldNumber_TextbookId = 1,
  DoubleTClsCurTbPageNotify_FieldNumber_Page = 2,
  DoubleTClsCurTbPageNotify_FieldNumber_Version = 3,
  DoubleTClsCurTbPageNotify_FieldNumber_Uid = 4,
  DoubleTClsCurTbPageNotify_FieldNumber_SubPage = 5,
};

/**
 * 下发当前使用的教材+课件页码通知
 * 0x00430062
 **/
@interface DoubleTClsCurTbPageNotify : GPBMessage

@property(nonatomic, readwrite) uint32_t textbookId;

@property(nonatomic, readwrite) uint32_t page;

@property(nonatomic, readwrite) uint32_t version;

@property(nonatomic, readwrite) uint64_t uid;

@property(nonatomic, readwrite) uint32_t subPage;

@end

#pragma mark - DoubleTClsAddTbBlankPageC2S

typedef GPB_ENUM(DoubleTClsAddTbBlankPageC2S_FieldNumber) {
  DoubleTClsAddTbBlankPageC2S_FieldNumber_TextbookId = 1,
  DoubleTClsAddTbBlankPageC2S_FieldNumber_Page = 2,
  DoubleTClsAddTbBlankPageC2S_FieldNumber_Num = 3,
};

/**
 * 添加课件空白页
 * 0x00430063
 **/
@interface DoubleTClsAddTbBlankPageC2S : GPBMessage

@property(nonatomic, readwrite) uint32_t textbookId;

@property(nonatomic, readwrite) uint32_t page;

@property(nonatomic, readwrite) uint32_t num;

@end

#pragma mark - DoubleTClsAddTbBlankPageS2C

typedef GPB_ENUM(DoubleTClsAddTbBlankPageS2C_FieldNumber) {
  DoubleTClsAddTbBlankPageS2C_FieldNumber_RspCode = 1,
  DoubleTClsAddTbBlankPageS2C_FieldNumber_TextbookId = 2,
  DoubleTClsAddTbBlankPageS2C_FieldNumber_Page = 3,
  DoubleTClsAddTbBlankPageS2C_FieldNumber_VecPageArray = 4,
  DoubleTClsAddTbBlankPageS2C_FieldNumber_Version = 5,
};

/**
 * 添加课件空白页
 * 0x00430064
 **/
@interface DoubleTClsAddTbBlankPageS2C : GPBMessage

@property(nonatomic, readwrite) uint32_t rspCode;

@property(nonatomic, readwrite) uint32_t textbookId;

@property(nonatomic, readwrite) uint32_t page;

@property(nonatomic, readwrite, strong, null_resettable) GPBUInt32Array *vecPageArray;
/** The number of items in @c vecPageArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger vecPageArray_Count;

@property(nonatomic, readwrite) uint32_t version;

@end

#pragma mark - DoubleTClsDelTbBlankPageC2S

typedef GPB_ENUM(DoubleTClsDelTbBlankPageC2S_FieldNumber) {
  DoubleTClsDelTbBlankPageC2S_FieldNumber_TextbookId = 1,
  DoubleTClsDelTbBlankPageC2S_FieldNumber_VecPageArray = 2,
};

/**
 * 删除课件空白页
 * 0x00430065
 **/
@interface DoubleTClsDelTbBlankPageC2S : GPBMessage

@property(nonatomic, readwrite) uint32_t textbookId;

@property(nonatomic, readwrite, strong, null_resettable) GPBUInt32Array *vecPageArray;
/** The number of items in @c vecPageArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger vecPageArray_Count;

@end

#pragma mark - DoubleTClsDelTbBlankPageS2C

typedef GPB_ENUM(DoubleTClsDelTbBlankPageS2C_FieldNumber) {
  DoubleTClsDelTbBlankPageS2C_FieldNumber_RspCode = 1,
  DoubleTClsDelTbBlankPageS2C_FieldNumber_TextbookId = 2,
  DoubleTClsDelTbBlankPageS2C_FieldNumber_VecPageArray = 3,
  DoubleTClsDelTbBlankPageS2C_FieldNumber_Version = 4,
};

/**
 * 删除课件空白页
 * 0x00430066
 **/
@interface DoubleTClsDelTbBlankPageS2C : GPBMessage

@property(nonatomic, readwrite) uint32_t rspCode;

@property(nonatomic, readwrite) uint32_t textbookId;

@property(nonatomic, readwrite, strong, null_resettable) GPBUInt32Array *vecPageArray;
/** The number of items in @c vecPageArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger vecPageArray_Count;

@property(nonatomic, readwrite) uint32_t version;

@end

#pragma mark - DoubleTClsTbPageListChangeNotify

typedef GPB_ENUM(DoubleTClsTbPageListChangeNotify_FieldNumber) {
  DoubleTClsTbPageListChangeNotify_FieldNumber_TextbookId = 1,
  DoubleTClsTbPageListChangeNotify_FieldNumber_PageListArray = 2,
  DoubleTClsTbPageListChangeNotify_FieldNumber_Version = 3,
};

/**
 * 课件页列表（课件页->教材页、空白页映射关系）变更通知
 * 0x00430067
 **/
@interface DoubleTClsTbPageListChangeNotify : GPBMessage

@property(nonatomic, readwrite) uint32_t textbookId;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<DoubleTClsTbPageListChangeNotify_DoubleTPageItem*> *pageListArray;
/** The number of items in @c pageListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger pageListArray_Count;

@property(nonatomic, readwrite) uint32_t version;

@end

#pragma mark - DoubleTClsTbPageListChangeNotify_DoubleTPageItem

typedef GPB_ENUM(DoubleTClsTbPageListChangeNotify_DoubleTPageItem_FieldNumber) {
  DoubleTClsTbPageListChangeNotify_DoubleTPageItem_FieldNumber_Page = 1,
  DoubleTClsTbPageListChangeNotify_DoubleTPageItem_FieldNumber_CrswarePage = 2,
  DoubleTClsTbPageListChangeNotify_DoubleTPageItem_FieldNumber_Uid = 3,
  DoubleTClsTbPageListChangeNotify_DoubleTPageItem_FieldNumber_Time = 4,
  DoubleTClsTbPageListChangeNotify_DoubleTPageItem_FieldNumber_Seq = 5,
};

@interface DoubleTClsTbPageListChangeNotify_DoubleTPageItem : GPBMessage

@property(nonatomic, readwrite) uint32_t page;

@property(nonatomic, readwrite) int32_t crswarePage;

@property(nonatomic, readwrite) uint64_t uid;

@property(nonatomic, readwrite) uint64_t time;

@property(nonatomic, readwrite) uint32_t seq;

@end

#pragma mark - DoubleTClsReqSyncCurTbPageSetC2S

typedef GPB_ENUM(DoubleTClsReqSyncCurTbPageSetC2S_FieldNumber) {
  DoubleTClsReqSyncCurTbPageSetC2S_FieldNumber_TbPageVerion = 1,
  DoubleTClsReqSyncCurTbPageSetC2S_FieldNumber_TextbookId = 2,
  DoubleTClsReqSyncCurTbPageSetC2S_FieldNumber_PageListVerion = 3,
};

/**
 * 定时请求同步当前课件的相关设置（当前教材、当前页码、课件页列表）
 * 0x00450068
 **/
@interface DoubleTClsReqSyncCurTbPageSetC2S : GPBMessage

@property(nonatomic, readwrite) uint32_t tbPageVerion;

@property(nonatomic, readwrite) uint32_t textbookId;

@property(nonatomic, readwrite) uint32_t pageListVerion;

@end

#pragma mark - DoubleTClsSetTbPageScrollbarPosC2S

typedef GPB_ENUM(DoubleTClsSetTbPageScrollbarPosC2S_FieldNumber) {
  DoubleTClsSetTbPageScrollbarPosC2S_FieldNumber_TextbookId = 1,
  DoubleTClsSetTbPageScrollbarPosC2S_FieldNumber_Page = 2,
  DoubleTClsSetTbPageScrollbarPosC2S_FieldNumber_PosX = 3,
  DoubleTClsSetTbPageScrollbarPosC2S_FieldNumber_PosY = 4,
};

/**
 * 设置课件页的滚动条位置
 * 0x00430069
 **/
@interface DoubleTClsSetTbPageScrollbarPosC2S : GPBMessage

@property(nonatomic, readwrite) uint32_t textbookId;

@property(nonatomic, readwrite) uint32_t page;

@property(nonatomic, readwrite, copy, null_resettable) NSString *posX;

@property(nonatomic, readwrite, copy, null_resettable) NSString *posY;

@end

#pragma mark - DoubleTClsSetTbPageScrollbarPosS2C

typedef GPB_ENUM(DoubleTClsSetTbPageScrollbarPosS2C_FieldNumber) {
  DoubleTClsSetTbPageScrollbarPosS2C_FieldNumber_RspCode = 1,
  DoubleTClsSetTbPageScrollbarPosS2C_FieldNumber_TextbookId = 2,
  DoubleTClsSetTbPageScrollbarPosS2C_FieldNumber_Page = 3,
};

/**
 * 设置课件页的滚动条位置
 * 0x0043006A
 **/
@interface DoubleTClsSetTbPageScrollbarPosS2C : GPBMessage

@property(nonatomic, readwrite) uint32_t rspCode;

@property(nonatomic, readwrite) uint32_t textbookId;

@property(nonatomic, readwrite) uint32_t page;

@end

#pragma mark - DoubleTClsTbPageScrollbarPosNotify

typedef GPB_ENUM(DoubleTClsTbPageScrollbarPosNotify_FieldNumber) {
  DoubleTClsTbPageScrollbarPosNotify_FieldNumber_TextbookId = 1,
  DoubleTClsTbPageScrollbarPosNotify_FieldNumber_Page = 2,
  DoubleTClsTbPageScrollbarPosNotify_FieldNumber_PosX = 3,
  DoubleTClsTbPageScrollbarPosNotify_FieldNumber_PosY = 4,
  DoubleTClsTbPageScrollbarPosNotify_FieldNumber_Uid = 5,
};

/**
 * 下发教材页的滚动条位置通知
 * 0x0043006B
 **/
@interface DoubleTClsTbPageScrollbarPosNotify : GPBMessage

@property(nonatomic, readwrite) uint32_t textbookId;

@property(nonatomic, readwrite) uint32_t page;

@property(nonatomic, readwrite, copy, null_resettable) NSString *posX;

@property(nonatomic, readwrite, copy, null_resettable) NSString *posY;

@property(nonatomic, readwrite) uint64_t uid;

@end

#pragma mark - DoubleTClsSetTbPageCursorPosC2S

typedef GPB_ENUM(DoubleTClsSetTbPageCursorPosC2S_FieldNumber) {
  DoubleTClsSetTbPageCursorPosC2S_FieldNumber_TextbookId = 1,
  DoubleTClsSetTbPageCursorPosC2S_FieldNumber_Page = 2,
  DoubleTClsSetTbPageCursorPosC2S_FieldNumber_PosX = 3,
  DoubleTClsSetTbPageCursorPosC2S_FieldNumber_PosY = 4,
};

/**
 * 设置教材页的鼠标位置
 * 0x0040006C
 **/
@interface DoubleTClsSetTbPageCursorPosC2S : GPBMessage

@property(nonatomic, readwrite) uint32_t textbookId;

@property(nonatomic, readwrite) uint32_t page;

@property(nonatomic, readwrite, copy, null_resettable) NSString *posX;

@property(nonatomic, readwrite, copy, null_resettable) NSString *posY;

@end

#pragma mark - DoubleTClsSetTbPageCursorPosS2C

typedef GPB_ENUM(DoubleTClsSetTbPageCursorPosS2C_FieldNumber) {
  DoubleTClsSetTbPageCursorPosS2C_FieldNumber_RspCode = 1,
  DoubleTClsSetTbPageCursorPosS2C_FieldNumber_TextbookId = 2,
  DoubleTClsSetTbPageCursorPosS2C_FieldNumber_Page = 3,
};

/**
 * 设置教材页的鼠标位置
 * 0x0040006D
 **/
@interface DoubleTClsSetTbPageCursorPosS2C : GPBMessage

@property(nonatomic, readwrite) uint32_t rspCode;

@property(nonatomic, readwrite) uint32_t textbookId;

@property(nonatomic, readwrite) uint32_t page;

@end

#pragma mark - DoubleTClsTbPageCursorPosNotify

typedef GPB_ENUM(DoubleTClsTbPageCursorPosNotify_FieldNumber) {
  DoubleTClsTbPageCursorPosNotify_FieldNumber_TextbookId = 1,
  DoubleTClsTbPageCursorPosNotify_FieldNumber_Page = 2,
  DoubleTClsTbPageCursorPosNotify_FieldNumber_PosX = 3,
  DoubleTClsTbPageCursorPosNotify_FieldNumber_PosY = 4,
  DoubleTClsTbPageCursorPosNotify_FieldNumber_Uid = 5,
};

/**
 * 下发教材页的鼠标位置通知
 * 0x0040006E
 **/
@interface DoubleTClsTbPageCursorPosNotify : GPBMessage

@property(nonatomic, readwrite) uint32_t textbookId;

@property(nonatomic, readwrite) uint32_t page;

@property(nonatomic, readwrite, copy, null_resettable) NSString *posX;

@property(nonatomic, readwrite, copy, null_resettable) NSString *posY;

@property(nonatomic, readwrite) uint64_t uid;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
