// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DoubleTClsInfo.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#import <Protobuf/GPBProtocolBuffers.h>

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class OAClsInfo;
@class OClsAssistInfo;
@class OClsTeaInfo;
@class OSClsInfo;
@class OTClsInfo;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - DoubleTclsInfoRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface DoubleTclsInfoRoot : GPBRootObject
@end

#pragma mark - OClsTeaInfo

typedef GPB_ENUM(OClsTeaInfo_FieldNumber) {
  OClsTeaInfo_FieldNumber_Uid = 1,
  OClsTeaInfo_FieldNumber_Name = 2,
};

@interface OClsTeaInfo : GPBMessage

@property(nonatomic, readwrite) uint64_t uid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@end

#pragma mark - OTClsInfo

typedef GPB_ENUM(OTClsInfo_FieldNumber) {
  OTClsInfo_FieldNumber_Cid = 1,
  OTClsInfo_FieldNumber_Name = 2,
  OTClsInfo_FieldNumber_Avatar = 3,
  OTClsInfo_FieldNumber_BeginTime = 4,
  OTClsInfo_FieldNumber_EndTime = 5,
  OTClsInfo_FieldNumber_VecTeaArray = 6,
};

@interface OTClsInfo : GPBMessage

@property(nonatomic, readwrite) uint64_t cid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite, copy, null_resettable) NSString *avatar;

@property(nonatomic, readwrite) uint64_t beginTime;

@property(nonatomic, readwrite) uint64_t endTime;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<OClsTeaInfo*> *vecTeaArray;
/** The number of items in @c vecTeaArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger vecTeaArray_Count;

@end

#pragma mark - GetClsTypeC2S

/**
 * 0x0043000E
 **/
@interface GetClsTypeC2S : GPBMessage

@end

#pragma mark - GetClsTypeS2C

typedef GPB_ENUM(GetClsTypeS2C_FieldNumber) {
  GetClsTypeS2C_FieldNumber_RspCode = 1,
  GetClsTypeS2C_FieldNumber_Type = 2,
  GetClsTypeS2C_FieldNumber_Level = 3,
};

/**
 * 0x0043000F
 **/
@interface GetClsTypeS2C : GPBMessage

@property(nonatomic, readwrite) uint32_t rspCode;

@property(nonatomic, readwrite) uint32_t type;

@property(nonatomic, readwrite) uint32_t level;

@end

#pragma mark - GetOTClsInfoC2S

typedef GPB_ENUM(GetOTClsInfoC2S_FieldNumber) {
  GetOTClsInfoC2S_FieldNumber_Version = 1,
};

/**
 * 0x00430010
 **/
@interface GetOTClsInfoC2S : GPBMessage

@property(nonatomic, readwrite) uint32_t version;

@end

#pragma mark - GetOTClsInfoS2C

typedef GPB_ENUM(GetOTClsInfoS2C_FieldNumber) {
  GetOTClsInfoS2C_FieldNumber_RspCode = 1,
  GetOTClsInfoS2C_FieldNumber_Version = 2,
  GetOTClsInfoS2C_FieldNumber_Info = 3,
};

/**
 * 0x00430011
 **/
@interface GetOTClsInfoS2C : GPBMessage

@property(nonatomic, readwrite) uint32_t rspCode;

@property(nonatomic, readwrite) uint32_t version;

@property(nonatomic, readwrite, strong, null_resettable) OTClsInfo *info;
/** Test to see if @c info has been set. */
@property(nonatomic, readwrite) BOOL hasInfo;

@end

#pragma mark - OTClsInfoChangeNotify

typedef GPB_ENUM(OTClsInfoChangeNotify_FieldNumber) {
  OTClsInfoChangeNotify_FieldNumber_Version = 1,
};

/**
 * 0x00430012
 **/
@interface OTClsInfoChangeNotify : GPBMessage

@property(nonatomic, readwrite) uint32_t version;

@end

#pragma mark - OClsAssistInfo

typedef GPB_ENUM(OClsAssistInfo_FieldNumber) {
  OClsAssistInfo_FieldNumber_Uid = 1,
  OClsAssistInfo_FieldNumber_Name = 2,
};

@interface OClsAssistInfo : GPBMessage

@property(nonatomic, readwrite) uint64_t uid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@end

#pragma mark - OAClsInfo

typedef GPB_ENUM(OAClsInfo_FieldNumber) {
  OAClsInfo_FieldNumber_Cid = 1,
  OAClsInfo_FieldNumber_OtclsId = 2,
  OAClsInfo_FieldNumber_Name = 3,
  OAClsInfo_FieldNumber_Avatar = 4,
  OAClsInfo_FieldNumber_BeginTime = 5,
  OAClsInfo_FieldNumber_EndTime = 6,
  OAClsInfo_FieldNumber_VecTeaArray = 7,
  OAClsInfo_FieldNumber_VecAssistArray = 8,
};

@interface OAClsInfo : GPBMessage

@property(nonatomic, readwrite) uint64_t cid;

@property(nonatomic, readwrite) uint64_t otclsId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite, copy, null_resettable) NSString *avatar;

@property(nonatomic, readwrite) uint64_t beginTime;

@property(nonatomic, readwrite) uint64_t endTime;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<OClsTeaInfo*> *vecTeaArray;
/** The number of items in @c vecTeaArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger vecTeaArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<OClsAssistInfo*> *vecAssistArray;
/** The number of items in @c vecAssistArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger vecAssistArray_Count;

@end

#pragma mark - GetOAClsInfoC2S

typedef GPB_ENUM(GetOAClsInfoC2S_FieldNumber) {
  GetOAClsInfoC2S_FieldNumber_Version = 1,
};

/**
 * 0x00440010
 **/
@interface GetOAClsInfoC2S : GPBMessage

@property(nonatomic, readwrite) uint32_t version;

@end

#pragma mark - GetOAClsInfoS2C

typedef GPB_ENUM(GetOAClsInfoS2C_FieldNumber) {
  GetOAClsInfoS2C_FieldNumber_RspCode = 1,
  GetOAClsInfoS2C_FieldNumber_Version = 2,
  GetOAClsInfoS2C_FieldNumber_Info = 3,
};

/**
 * 0x00440011
 **/
@interface GetOAClsInfoS2C : GPBMessage

@property(nonatomic, readwrite) uint32_t rspCode;

@property(nonatomic, readwrite) uint32_t version;

@property(nonatomic, readwrite, strong, null_resettable) OAClsInfo *info;
/** Test to see if @c info has been set. */
@property(nonatomic, readwrite) BOOL hasInfo;

@end

#pragma mark - OAClsInfoChangeNotify

typedef GPB_ENUM(OAClsInfoChangeNotify_FieldNumber) {
  OAClsInfoChangeNotify_FieldNumber_Version = 1,
};

/**
 * 0x00440012
 **/
@interface OAClsInfoChangeNotify : GPBMessage

@property(nonatomic, readwrite) uint32_t version;

@end

#pragma mark - OSClsInfo

typedef GPB_ENUM(OSClsInfo_FieldNumber) {
  OSClsInfo_FieldNumber_Cid = 1,
  OSClsInfo_FieldNumber_OaclsId = 2,
  OSClsInfo_FieldNumber_OtclsId = 3,
  OSClsInfo_FieldNumber_Name = 4,
  OSClsInfo_FieldNumber_Avatar = 5,
  OSClsInfo_FieldNumber_BeginTime = 6,
  OSClsInfo_FieldNumber_EndTime = 7,
  OSClsInfo_FieldNumber_VecTeaArray = 8,
  OSClsInfo_FieldNumber_VecAssistArray = 9,
};

@interface OSClsInfo : GPBMessage

@property(nonatomic, readwrite) uint64_t cid;

@property(nonatomic, readwrite) uint64_t oaclsId;

@property(nonatomic, readwrite) uint64_t otclsId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite, copy, null_resettable) NSString *avatar;

@property(nonatomic, readwrite) uint64_t beginTime;

@property(nonatomic, readwrite) uint64_t endTime;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<OClsTeaInfo*> *vecTeaArray;
/** The number of items in @c vecTeaArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger vecTeaArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<OClsAssistInfo*> *vecAssistArray;
/** The number of items in @c vecAssistArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger vecAssistArray_Count;

@end

#pragma mark - GetOSClsInfoC2S

typedef GPB_ENUM(GetOSClsInfoC2S_FieldNumber) {
  GetOSClsInfoC2S_FieldNumber_Version = 1,
};

/**
 * 0x00450010
 **/
@interface GetOSClsInfoC2S : GPBMessage

@property(nonatomic, readwrite) uint32_t version;

@end

#pragma mark - GetOSClsInfoS2C

typedef GPB_ENUM(GetOSClsInfoS2C_FieldNumber) {
  GetOSClsInfoS2C_FieldNumber_RspCode = 1,
  GetOSClsInfoS2C_FieldNumber_Version = 2,
  GetOSClsInfoS2C_FieldNumber_Info = 3,
};

/**
 * 0x00450011
 **/
@interface GetOSClsInfoS2C : GPBMessage

@property(nonatomic, readwrite) uint32_t rspCode;

@property(nonatomic, readwrite) uint32_t version;

@property(nonatomic, readwrite, strong, null_resettable) OSClsInfo *info;
/** Test to see if @c info has been set. */
@property(nonatomic, readwrite) BOOL hasInfo;

@end

#pragma mark - OSClsInfoChangeNotify

typedef GPB_ENUM(OSClsInfoChangeNotify_FieldNumber) {
  OSClsInfoChangeNotify_FieldNumber_Version = 1,
};

/**
 * 0x00450012
 **/
@interface OSClsInfoChangeNotify : GPBMessage

@property(nonatomic, readwrite) uint32_t version;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
