// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DoubleTBroadcastMsg.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#import <Protobuf/GPBProtocolBuffers.h>

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class OClsBroadcastMsgC2S_ClsItem;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - DoubleTbroadcastMsgRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface DoubleTbroadcastMsgRoot : GPBRootObject
@end

#pragma mark - OClsBroadcastMsgC2S

typedef GPB_ENUM(OClsBroadcastMsgC2S_FieldNumber) {
  OClsBroadcastMsgC2S_FieldNumber_Scope = 1,
  OClsBroadcastMsgC2S_FieldNumber_VecClsArray = 2,
  OClsBroadcastMsgC2S_FieldNumber_Type = 3,
  OClsBroadcastMsgC2S_FieldNumber_Data_p = 4,
  OClsBroadcastMsgC2S_FieldNumber_StrData = 5,
};

/**
 * 0x004300C0、0x004400C0、0x004500C0
 **/
@interface OClsBroadcastMsgC2S : GPBMessage

@property(nonatomic, readwrite) uint32_t scope;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<OClsBroadcastMsgC2S_ClsItem*> *vecClsArray;
/** The number of items in @c vecClsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger vecClsArray_Count;

@property(nonatomic, readwrite) uint32_t type;

@property(nonatomic, readwrite, copy, null_resettable) NSData *data_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *strData;

@end

#pragma mark - OClsBroadcastMsgC2S_ClsItem

typedef GPB_ENUM(OClsBroadcastMsgC2S_ClsItem_FieldNumber) {
  OClsBroadcastMsgC2S_ClsItem_FieldNumber_Ctype = 1,
  OClsBroadcastMsgC2S_ClsItem_FieldNumber_Cid = 2,
  OClsBroadcastMsgC2S_ClsItem_FieldNumber_VecUidArray = 3,
};

@interface OClsBroadcastMsgC2S_ClsItem : GPBMessage

@property(nonatomic, readwrite) uint32_t ctype;

@property(nonatomic, readwrite) uint64_t cid;

@property(nonatomic, readwrite, strong, null_resettable) GPBUInt64Array *vecUidArray;
/** The number of items in @c vecUidArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger vecUidArray_Count;

@end

#pragma mark - OClsBroadcastMsgS2C

typedef GPB_ENUM(OClsBroadcastMsgS2C_FieldNumber) {
  OClsBroadcastMsgS2C_FieldNumber_RspCode = 1,
};

/**
 * 0x004300C1、0x004400C1、0x004500C1
 **/
@interface OClsBroadcastMsgS2C : GPBMessage

@property(nonatomic, readwrite) uint32_t rspCode;

@end

#pragma mark - OClsBroadcastMsgNotify

typedef GPB_ENUM(OClsBroadcastMsgNotify_FieldNumber) {
  OClsBroadcastMsgNotify_FieldNumber_Type = 1,
  OClsBroadcastMsgNotify_FieldNumber_Data_p = 2,
  OClsBroadcastMsgNotify_FieldNumber_StrData = 3,
  OClsBroadcastMsgNotify_FieldNumber_OwnerUid = 4,
  OClsBroadcastMsgNotify_FieldNumber_OwnerCid = 5,
  OClsBroadcastMsgNotify_FieldNumber_OwnerCtype = 6,
};

/**
 * 0x004300C2、0x004400C2、0x004500C2
 **/
@interface OClsBroadcastMsgNotify : GPBMessage

@property(nonatomic, readwrite) uint32_t type;

@property(nonatomic, readwrite, copy, null_resettable) NSData *data_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *strData;

@property(nonatomic, readwrite) uint64_t ownerUid;

@property(nonatomic, readwrite) uint64_t ownerCid;

@property(nonatomic, readwrite) uint32_t ownerCtype;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
