// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DoubleTClsQuiz.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#import <Protobuf/GPBProtocolBuffers.h>

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class DoubleTClsQuizInfo;
@class DoubleTGiveALikeNotify_DoubleTUserInfo;
@class DoubleTQuizAnswer;
@class DoubleTQuizInfo;
@class DoubleTQuizNumberAnswer;
@class DoubleTQuizOption;
@class DoubleTRewardsInfo;
@class DoubleTUserAnswer;
@class DoubleTUserQuizInfo;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - DoubleTclsQuizRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface DoubleTclsQuizRoot : GPBRootObject
@end

#pragma mark - DoubleTQuizOption

typedef GPB_ENUM(DoubleTQuizOption_FieldNumber) {
  DoubleTQuizOption_FieldNumber_Id_p = 1,
  DoubleTQuizOption_FieldNumber_Text = 2,
};

@interface DoubleTQuizOption : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *text;

@end

#pragma mark - DoubleTQuizInfo

typedef GPB_ENUM(DoubleTQuizInfo_FieldNumber) {
  DoubleTQuizInfo_FieldNumber_QuizNumber = 1,
  DoubleTQuizInfo_FieldNumber_Content = 2,
  DoubleTQuizInfo_FieldNumber_VecOptionArray = 3,
  DoubleTQuizInfo_FieldNumber_VecAnswerArray = 4,
  DoubleTQuizInfo_FieldNumber_AwardCoins = 5,
};

@interface DoubleTQuizInfo : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *quizNumber;

@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<DoubleTQuizOption*> *vecOptionArray;
/** The number of items in @c vecOptionArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger vecOptionArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *vecAnswerArray;
/** The number of items in @c vecAnswerArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger vecAnswerArray_Count;

@property(nonatomic, readwrite) int32_t awardCoins;

@end

#pragma mark - DoubleTQuizAnswer

typedef GPB_ENUM(DoubleTQuizAnswer_FieldNumber) {
  DoubleTQuizAnswer_FieldNumber_QuizNumber = 1,
  DoubleTQuizAnswer_FieldNumber_VecAnswerArray = 2,
};

@interface DoubleTQuizAnswer : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *quizNumber;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *vecAnswerArray;
/** The number of items in @c vecAnswerArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger vecAnswerArray_Count;

@end

#pragma mark - DoubleTUserQuizInfo

typedef GPB_ENUM(DoubleTUserQuizInfo_FieldNumber) {
  DoubleTUserQuizInfo_FieldNumber_Cid = 1,
  DoubleTUserQuizInfo_FieldNumber_ClsName = 2,
  DoubleTUserQuizInfo_FieldNumber_Uid = 3,
  DoubleTUserQuizInfo_FieldNumber_Name = 4,
  DoubleTUserQuizInfo_FieldNumber_Avatar = 5,
  DoubleTUserQuizInfo_FieldNumber_Liked = 6,
  DoubleTUserQuizInfo_FieldNumber_AnswerCnt = 7,
  DoubleTUserQuizInfo_FieldNumber_RightCnt = 8,
  DoubleTUserQuizInfo_FieldNumber_TotalCnt = 9,
  DoubleTUserQuizInfo_FieldNumber_VecAnswerArray = 10,
};

@interface DoubleTUserQuizInfo : GPBMessage

@property(nonatomic, readwrite) uint64_t cid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *clsName;

@property(nonatomic, readwrite) uint64_t uid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite, copy, null_resettable) NSString *avatar;

@property(nonatomic, readwrite) BOOL liked;

@property(nonatomic, readwrite) uint32_t answerCnt;

@property(nonatomic, readwrite) uint32_t rightCnt;

@property(nonatomic, readwrite) uint32_t totalCnt;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<DoubleTQuizAnswer*> *vecAnswerArray;
/** The number of items in @c vecAnswerArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger vecAnswerArray_Count;

@end

#pragma mark - DoubleTRewardsInfo

typedef GPB_ENUM(DoubleTRewardsInfo_FieldNumber) {
  DoubleTRewardsInfo_FieldNumber_UsrCnt = 1,
  DoubleTRewardsInfo_FieldNumber_Rewards = 2,
  DoubleTRewardsInfo_FieldNumber_VecUsrArray = 3,
};

@interface DoubleTRewardsInfo : GPBMessage

@property(nonatomic, readwrite) uint32_t usrCnt;

@property(nonatomic, readwrite) uint32_t rewards;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<DoubleTUserQuizInfo*> *vecUsrArray;
/** The number of items in @c vecUsrArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger vecUsrArray_Count;

@end

#pragma mark - DoubleTClsQuizInfo

typedef GPB_ENUM(DoubleTClsQuizInfo_FieldNumber) {
  DoubleTClsQuizInfo_FieldNumber_Cid = 1,
  DoubleTClsQuizInfo_FieldNumber_ClsName = 2,
  DoubleTClsQuizInfo_FieldNumber_AnswerCnt = 3,
  DoubleTClsQuizInfo_FieldNumber_RightCnt = 4,
  DoubleTClsQuizInfo_FieldNumber_TotalCnt = 5,
};

@interface DoubleTClsQuizInfo : GPBMessage

@property(nonatomic, readwrite) uint64_t cid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *clsName;

@property(nonatomic, readwrite) uint32_t answerCnt;

@property(nonatomic, readwrite) uint32_t rightCnt;

@property(nonatomic, readwrite) uint32_t totalCnt;

@end

#pragma mark - DoubleTUserAnswer

typedef GPB_ENUM(DoubleTUserAnswer_FieldNumber) {
  DoubleTUserAnswer_FieldNumber_UsrCnt = 1,
  DoubleTUserAnswer_FieldNumber_VecAnswerArray = 2,
  DoubleTUserAnswer_FieldNumber_VecUsrArray = 3,
};

@interface DoubleTUserAnswer : GPBMessage

@property(nonatomic, readwrite) uint32_t usrCnt;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *vecAnswerArray;
/** The number of items in @c vecAnswerArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger vecAnswerArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<DoubleTUserQuizInfo*> *vecUsrArray;
/** The number of items in @c vecUsrArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger vecUsrArray_Count;

@end

#pragma mark - DoubleTQuizNumberAnswer

typedef GPB_ENUM(DoubleTQuizNumberAnswer_FieldNumber) {
  DoubleTQuizNumberAnswer_FieldNumber_QuizNumber = 1,
  DoubleTQuizNumberAnswer_FieldNumber_AnswerCnt = 2,
  DoubleTQuizNumberAnswer_FieldNumber_RightCnt = 3,
  DoubleTQuizNumberAnswer_FieldNumber_TotalCnt = 4,
  DoubleTQuizNumberAnswer_FieldNumber_RightAnswerArray = 5,
  DoubleTQuizNumberAnswer_FieldNumber_VecAnswerArray = 6,
};

@interface DoubleTQuizNumberAnswer : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *quizNumber;

@property(nonatomic, readwrite) uint32_t answerCnt;

@property(nonatomic, readwrite) uint32_t rightCnt;

@property(nonatomic, readwrite) uint32_t totalCnt;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *rightAnswerArray;
/** The number of items in @c rightAnswerArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger rightAnswerArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<DoubleTUserAnswer*> *vecAnswerArray;
/** The number of items in @c vecAnswerArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger vecAnswerArray_Count;

@end

#pragma mark - DoubleTStartQuizC2S

typedef GPB_ENUM(DoubleTStartQuizC2S_FieldNumber) {
  DoubleTStartQuizC2S_FieldNumber_QuizSeq = 1,
  DoubleTStartQuizC2S_FieldNumber_QuizListArray = 2,
  DoubleTStartQuizC2S_FieldNumber_Screenshot = 3,
};

/**
 * 0x004300E0, 0x004400E0
 **/
@interface DoubleTStartQuizC2S : GPBMessage

@property(nonatomic, readwrite) uint32_t quizSeq;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<DoubleTQuizInfo*> *quizListArray;
/** The number of items in @c quizListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger quizListArray_Count;

@property(nonatomic, readwrite, copy, null_resettable) NSString *screenshot;

@end

#pragma mark - DoubleTStartQuizS2C

typedef GPB_ENUM(DoubleTStartQuizS2C_FieldNumber) {
  DoubleTStartQuizS2C_FieldNumber_RspCode = 1,
  DoubleTStartQuizS2C_FieldNumber_QuizSeq = 2,
  DoubleTStartQuizS2C_FieldNumber_QuizId = 3,
  DoubleTStartQuizS2C_FieldNumber_UserNum = 4,
  DoubleTStartQuizS2C_FieldNumber_StartStamp = 5,
};

/**
 * 0x004300E1, 0x004400E1
 **/
@interface DoubleTStartQuizS2C : GPBMessage

@property(nonatomic, readwrite) uint32_t rspCode;

@property(nonatomic, readwrite) uint32_t quizSeq;

@property(nonatomic, readwrite, copy, null_resettable) NSString *quizId;

@property(nonatomic, readwrite) uint32_t userNum;

@property(nonatomic, readwrite) int64_t startStamp;

@end

#pragma mark - DoubleTStopQuizC2S

typedef GPB_ENUM(DoubleTStopQuizC2S_FieldNumber) {
  DoubleTStopQuizC2S_FieldNumber_QuizId = 1,
};

/**
 * 0x004300E2, 0x004400E2
 **/
@interface DoubleTStopQuizC2S : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *quizId;

@end

#pragma mark - DoubleTStopQuizS2C

typedef GPB_ENUM(DoubleTStopQuizS2C_FieldNumber) {
  DoubleTStopQuizS2C_FieldNumber_RspCode = 1,
  DoubleTStopQuizS2C_FieldNumber_QuizId = 2,
};

/**
 * 0x004300E3, 0x004400E3
 **/
@interface DoubleTStopQuizS2C : GPBMessage

@property(nonatomic, readwrite) uint32_t rspCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *quizId;

@end

#pragma mark - DoubleTQuizStatNotify

typedef GPB_ENUM(DoubleTQuizStatNotify_FieldNumber) {
  DoubleTQuizStatNotify_FieldNumber_Stat = 1,
  DoubleTQuizStatNotify_FieldNumber_QuizId = 2,
  DoubleTQuizStatNotify_FieldNumber_QuizListArray = 3,
  DoubleTQuizStatNotify_FieldNumber_TeaUid = 4,
  DoubleTQuizStatNotify_FieldNumber_Stamp = 5,
};

/**
 * 0x004300E4, 0x004400E4, 0x004500E4
 **/
@interface DoubleTQuizStatNotify : GPBMessage

/** 1: start 2: stop */
@property(nonatomic, readwrite) uint32_t stat;

@property(nonatomic, readwrite, copy, null_resettable) NSString *quizId;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<DoubleTQuizInfo*> *quizListArray;
/** The number of items in @c quizListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger quizListArray_Count;

@property(nonatomic, readwrite) uint64_t teaUid;

@property(nonatomic, readwrite) int64_t stamp;

@end

#pragma mark - DoubleTSubmitQuizC2S

typedef GPB_ENUM(DoubleTSubmitQuizC2S_FieldNumber) {
  DoubleTSubmitQuizC2S_FieldNumber_QuizId = 1,
  DoubleTSubmitQuizC2S_FieldNumber_VecAnswerArray = 2,
};

/**
 * 0x004500E6
 **/
@interface DoubleTSubmitQuizC2S : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *quizId;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<DoubleTQuizAnswer*> *vecAnswerArray;
/** The number of items in @c vecAnswerArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger vecAnswerArray_Count;

@end

#pragma mark - DoubleTSubmitQuizS2C

typedef GPB_ENUM(DoubleTSubmitQuizS2C_FieldNumber) {
  DoubleTSubmitQuizS2C_FieldNumber_RspCode = 1,
  DoubleTSubmitQuizS2C_FieldNumber_QuizId = 2,
  DoubleTSubmitQuizS2C_FieldNumber_SubmitStamp = 3,
  DoubleTSubmitQuizS2C_FieldNumber_AwardCoins = 4,
  DoubleTSubmitQuizS2C_FieldNumber_TotalCoins = 5,
};

/**
 * 0x004500E7
 **/
@interface DoubleTSubmitQuizS2C : GPBMessage

@property(nonatomic, readwrite) uint32_t rspCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *quizId;

@property(nonatomic, readwrite) int64_t submitStamp;

@property(nonatomic, readwrite) int32_t awardCoins;

@property(nonatomic, readwrite) int32_t totalCoins;

@end

#pragma mark - DoubleTGiveALikeC2S

typedef GPB_ENUM(DoubleTGiveALikeC2S_FieldNumber) {
  DoubleTGiveALikeC2S_FieldNumber_Type = 1,
  DoubleTGiveALikeC2S_FieldNumber_QuizId = 2,
  DoubleTGiveALikeC2S_FieldNumber_Count = 3,
  DoubleTGiveALikeC2S_FieldNumber_VecUidArray = 4,
};

/**
 * 0x004300E8, 0x004400E8
 **/
@interface DoubleTGiveALikeC2S : GPBMessage

/** 1:notify vec_uid 2:notify top count */
@property(nonatomic, readwrite) uint32_t type;

@property(nonatomic, readwrite, copy, null_resettable) NSString *quizId;

@property(nonatomic, readwrite) uint32_t count;

@property(nonatomic, readwrite, strong, null_resettable) GPBUInt64Array *vecUidArray;
/** The number of items in @c vecUidArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger vecUidArray_Count;

@end

#pragma mark - DoubleTGiveALikeS2C

typedef GPB_ENUM(DoubleTGiveALikeS2C_FieldNumber) {
  DoubleTGiveALikeS2C_FieldNumber_RspCode = 1,
  DoubleTGiveALikeS2C_FieldNumber_Type = 2,
  DoubleTGiveALikeS2C_FieldNumber_QuizId = 3,
};

/**
 * 0x004300E9, 0x004400E9
 **/
@interface DoubleTGiveALikeS2C : GPBMessage

@property(nonatomic, readwrite) uint32_t rspCode;

@property(nonatomic, readwrite) uint32_t type;

@property(nonatomic, readwrite, copy, null_resettable) NSString *quizId;

@end

#pragma mark - DoubleTGiveALikeNotify

typedef GPB_ENUM(DoubleTGiveALikeNotify_FieldNumber) {
  DoubleTGiveALikeNotify_FieldNumber_QuizId = 1,
  DoubleTGiveALikeNotify_FieldNumber_VecUserArray = 2,
  DoubleTGiveALikeNotify_FieldNumber_TeaInfo = 3,
};

/**
 * 0x004500EA
 **/
@interface DoubleTGiveALikeNotify : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *quizId;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<DoubleTGiveALikeNotify_DoubleTUserInfo*> *vecUserArray;
/** The number of items in @c vecUserArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger vecUserArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) DoubleTGiveALikeNotify_DoubleTUserInfo *teaInfo;
/** Test to see if @c teaInfo has been set. */
@property(nonatomic, readwrite) BOOL hasTeaInfo;

@end

#pragma mark - DoubleTGiveALikeNotify_DoubleTUserInfo

typedef GPB_ENUM(DoubleTGiveALikeNotify_DoubleTUserInfo_FieldNumber) {
  DoubleTGiveALikeNotify_DoubleTUserInfo_FieldNumber_Cid = 1,
  DoubleTGiveALikeNotify_DoubleTUserInfo_FieldNumber_Uid = 2,
  DoubleTGiveALikeNotify_DoubleTUserInfo_FieldNumber_Name = 3,
  DoubleTGiveALikeNotify_DoubleTUserInfo_FieldNumber_Avatar = 4,
};

@interface DoubleTGiveALikeNotify_DoubleTUserInfo : GPBMessage

@property(nonatomic, readwrite) uint64_t cid;

@property(nonatomic, readwrite) uint64_t uid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite, copy, null_resettable) NSString *avatar;

@end

#pragma mark - DoubleTMsgRemindingC2S

typedef GPB_ENUM(DoubleTMsgRemindingC2S_FieldNumber) {
  DoubleTMsgRemindingC2S_FieldNumber_QuizId = 1,
  DoubleTMsgRemindingC2S_FieldNumber_Type = 2,
  DoubleTMsgRemindingC2S_FieldNumber_VecUidArray = 3,
  DoubleTMsgRemindingC2S_FieldNumber_Content = 4,
};

/**
 * 0x004300EB, 0x004400EB
 **/
@interface DoubleTMsgRemindingC2S : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *quizId;

@property(nonatomic, readwrite) uint32_t type;

@property(nonatomic, readwrite, strong, null_resettable) GPBUInt64Array *vecUidArray;
/** The number of items in @c vecUidArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger vecUidArray_Count;

@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

@end

#pragma mark - DoubleTMsgRemindingS2C

typedef GPB_ENUM(DoubleTMsgRemindingS2C_FieldNumber) {
  DoubleTMsgRemindingS2C_FieldNumber_RspCode = 1,
  DoubleTMsgRemindingS2C_FieldNumber_QuizId = 2,
  DoubleTMsgRemindingS2C_FieldNumber_Type = 3,
  DoubleTMsgRemindingS2C_FieldNumber_VecUidArray = 4,
  DoubleTMsgRemindingS2C_FieldNumber_Content = 5,
};

/**
 * 0x004300EC, 0x004400EC
 **/
@interface DoubleTMsgRemindingS2C : GPBMessage

@property(nonatomic, readwrite) uint32_t rspCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *quizId;

@property(nonatomic, readwrite) uint32_t type;

@property(nonatomic, readwrite, strong, null_resettable) GPBUInt64Array *vecUidArray;
/** The number of items in @c vecUidArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger vecUidArray_Count;

@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

@end

#pragma mark - DoubleTMsgRemindingNotify

typedef GPB_ENUM(DoubleTMsgRemindingNotify_FieldNumber) {
  DoubleTMsgRemindingNotify_FieldNumber_Type = 1,
  DoubleTMsgRemindingNotify_FieldNumber_Content = 2,
};

/**
 * 0x004300ED, 0x004400ED, 0x004500ED
 **/
@interface DoubleTMsgRemindingNotify : GPBMessage

@property(nonatomic, readwrite) uint32_t type;

@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

@end

#pragma mark - DoubleTRecvQuizACK

typedef GPB_ENUM(DoubleTRecvQuizACK_FieldNumber) {
  DoubleTRecvQuizACK_FieldNumber_QuizId = 1,
};

/**
 * 0x004300E5
 **/
@interface DoubleTRecvQuizACK : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *quizId;

@end

#pragma mark - DoubleTGetQuizResultC2S

typedef GPB_ENUM(DoubleTGetQuizResultC2S_FieldNumber) {
  DoubleTGetQuizResultC2S_FieldNumber_Cid = 1,
  DoubleTGetQuizResultC2S_FieldNumber_QuizId = 2,
};

/**
 * 0x004300EE, 0x004400EE
 **/
@interface DoubleTGetQuizResultC2S : GPBMessage

@property(nonatomic, readwrite) uint64_t cid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *quizId;

@end

#pragma mark - DoubleTGetQuizResultS2C

typedef GPB_ENUM(DoubleTGetQuizResultS2C_FieldNumber) {
  DoubleTGetQuizResultS2C_FieldNumber_RspCode = 1,
  DoubleTGetQuizResultS2C_FieldNumber_Cid = 2,
  DoubleTGetQuizResultS2C_FieldNumber_QuizId = 3,
  DoubleTGetQuizResultS2C_FieldNumber_AnswerCnt = 4,
  DoubleTGetQuizResultS2C_FieldNumber_RightCnt = 5,
  DoubleTGetQuizResultS2C_FieldNumber_TotalCnt = 6,
  DoubleTGetQuizResultS2C_FieldNumber_VecAnswerArray = 7,
};

/**
 * 0x004300EF, 0x004400EF
 **/
@interface DoubleTGetQuizResultS2C : GPBMessage

@property(nonatomic, readwrite) uint32_t rspCode;

@property(nonatomic, readwrite) uint64_t cid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *quizId;

@property(nonatomic, readwrite) uint32_t answerCnt;

@property(nonatomic, readwrite) uint32_t rightCnt;

@property(nonatomic, readwrite) uint32_t totalCnt;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<DoubleTQuizNumberAnswer*> *vecAnswerArray;
/** The number of items in @c vecAnswerArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger vecAnswerArray_Count;

@end

#pragma mark - DoubleTGetQuizRewardC2S

typedef GPB_ENUM(DoubleTGetQuizRewardC2S_FieldNumber) {
  DoubleTGetQuizRewardC2S_FieldNumber_Cid = 1,
  DoubleTGetQuizRewardC2S_FieldNumber_QuizId = 2,
};

/**
 * 0x004300F0, 0x004400F0
 **/
@interface DoubleTGetQuizRewardC2S : GPBMessage

@property(nonatomic, readwrite) uint64_t cid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *quizId;

@end

#pragma mark - DoubleTGetQuizRewardS2C

typedef GPB_ENUM(DoubleTGetQuizRewardS2C_FieldNumber) {
  DoubleTGetQuizRewardS2C_FieldNumber_RspCode = 1,
  DoubleTGetQuizRewardS2C_FieldNumber_Cid = 2,
  DoubleTGetQuizRewardS2C_FieldNumber_QuizId = 3,
  DoubleTGetQuizRewardS2C_FieldNumber_VecRewardArray = 4,
};

/**
 * 0x004300F1,0x004400F1
 **/
@interface DoubleTGetQuizRewardS2C : GPBMessage

@property(nonatomic, readwrite) uint32_t rspCode;

@property(nonatomic, readwrite) uint64_t cid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *quizId;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<DoubleTRewardsInfo*> *vecRewardArray;
/** The number of items in @c vecRewardArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger vecRewardArray_Count;

@end

#pragma mark - DoubleTGetQuizUsersC2S

typedef GPB_ENUM(DoubleTGetQuizUsersC2S_FieldNumber) {
  DoubleTGetQuizUsersC2S_FieldNumber_Type = 1,
  DoubleTGetQuizUsersC2S_FieldNumber_QuizId = 2,
  DoubleTGetQuizUsersC2S_FieldNumber_Offset = 3,
  DoubleTGetQuizUsersC2S_FieldNumber_Count = 4,
};

/**
 * 0x004300F2, 0x004400F2
 **/
@interface DoubleTGetQuizUsersC2S : GPBMessage

@property(nonatomic, readwrite) uint32_t type;

@property(nonatomic, readwrite, copy, null_resettable) NSString *quizId;

/** range(start,count) */
@property(nonatomic, readwrite) uint32_t offset;

@property(nonatomic, readwrite) uint32_t count;

@end

#pragma mark - DoubleTGetQuizUsersS2C

typedef GPB_ENUM(DoubleTGetQuizUsersS2C_FieldNumber) {
  DoubleTGetQuizUsersS2C_FieldNumber_RspCode = 1,
  DoubleTGetQuizUsersS2C_FieldNumber_Type = 2,
  DoubleTGetQuizUsersS2C_FieldNumber_QuizId = 3,
  DoubleTGetQuizUsersS2C_FieldNumber_Offset = 4,
  DoubleTGetQuizUsersS2C_FieldNumber_Count = 5,
  DoubleTGetQuizUsersS2C_FieldNumber_Remainder = 6,
  DoubleTGetQuizUsersS2C_FieldNumber_AnswerCnt = 7,
  DoubleTGetQuizUsersS2C_FieldNumber_RightCnt = 8,
  DoubleTGetQuizUsersS2C_FieldNumber_TotalCnt = 9,
  DoubleTGetQuizUsersS2C_FieldNumber_VecUsrArray = 10,
};

/**
 * 0x004300F3, 0x004400F3
 **/
@interface DoubleTGetQuizUsersS2C : GPBMessage

@property(nonatomic, readwrite) uint32_t rspCode;

@property(nonatomic, readwrite) uint32_t type;

@property(nonatomic, readwrite, copy, null_resettable) NSString *quizId;

/** range(start,count) */
@property(nonatomic, readwrite) uint32_t offset;

@property(nonatomic, readwrite) uint32_t count;

@property(nonatomic, readwrite) uint32_t remainder;

@property(nonatomic, readwrite) uint32_t answerCnt;

@property(nonatomic, readwrite) uint32_t rightCnt;

@property(nonatomic, readwrite) uint32_t totalCnt;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<DoubleTUserQuizInfo*> *vecUsrArray;
/** The number of items in @c vecUsrArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger vecUsrArray_Count;

@end

#pragma mark - DoubleTGetClsQuizInfoC2S

typedef GPB_ENUM(DoubleTGetClsQuizInfoC2S_FieldNumber) {
  DoubleTGetClsQuizInfoC2S_FieldNumber_QuizId = 1,
};

/**
 * 0x004300F4, 0x004400F4
 **/
@interface DoubleTGetClsQuizInfoC2S : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *quizId;

@end

#pragma mark - DoubleTGetClsQuizInfoS2C

typedef GPB_ENUM(DoubleTGetClsQuizInfoS2C_FieldNumber) {
  DoubleTGetClsQuizInfoS2C_FieldNumber_RspCode = 1,
  DoubleTGetClsQuizInfoS2C_FieldNumber_QuizId = 2,
  DoubleTGetClsQuizInfoS2C_FieldNumber_VecClsInfoArray = 3,
};

/**
 * 0x004300F5, 0x004400F5
 **/
@interface DoubleTGetClsQuizInfoS2C : GPBMessage

@property(nonatomic, readwrite) uint32_t rspCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *quizId;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<DoubleTClsQuizInfo*> *vecClsInfoArray;
/** The number of items in @c vecClsInfoArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger vecClsInfoArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
