// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DoubleTClsChat.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#import <Protobuf/GPBProtocolBuffers.h>

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class DoubleTUserInfo;
@class OClsChatMsg;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - DoubleTclsChatRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface DoubleTclsChatRoot : GPBRootObject
@end

#pragma mark - OClsSendChatMsgC2S

typedef GPB_ENUM(OClsSendChatMsgC2S_FieldNumber) {
  OClsSendChatMsgC2S_FieldNumber_CliSeq = 1,
  OClsSendChatMsgC2S_FieldNumber_SendTm = 2,
  OClsSendChatMsgC2S_FieldNumber_Type = 3,
  OClsSendChatMsgC2S_FieldNumber_Option = 4,
  OClsSendChatMsgC2S_FieldNumber_Content = 5,
};

/**
 * 0x004300B3
 **/
@interface OClsSendChatMsgC2S : GPBMessage

@property(nonatomic, readwrite) uint32_t cliSeq;

@property(nonatomic, readwrite) uint64_t sendTm;

@property(nonatomic, readwrite) uint32_t type;

@property(nonatomic, readwrite, copy, null_resettable) NSString *option;

@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

@end

#pragma mark - OClsSendChatMsgC2SAck

typedef GPB_ENUM(OClsSendChatMsgC2SAck_FieldNumber) {
  OClsSendChatMsgC2SAck_FieldNumber_RspCode = 1,
  OClsSendChatMsgC2SAck_FieldNumber_CliSeq = 2,
  OClsSendChatMsgC2SAck_FieldNumber_MsgId = 3,
  OClsSendChatMsgC2SAck_FieldNumber_SendTm = 4,
};

/**
 * 0x004300B4
 **/
@interface OClsSendChatMsgC2SAck : GPBMessage

@property(nonatomic, readwrite) uint32_t rspCode;

@property(nonatomic, readwrite) uint32_t cliSeq;

@property(nonatomic, readwrite) uint64_t msgId;

@property(nonatomic, readwrite) uint64_t sendTm;

@end

#pragma mark - OClsSendChatMsgS2C

typedef GPB_ENUM(OClsSendChatMsgS2C_FieldNumber) {
  OClsSendChatMsgS2C_FieldNumber_MsgId = 1,
  OClsSendChatMsgS2C_FieldNumber_UserInfo = 2,
  OClsSendChatMsgS2C_FieldNumber_SendTm = 3,
  OClsSendChatMsgS2C_FieldNumber_Type = 4,
  OClsSendChatMsgS2C_FieldNumber_Option = 5,
  OClsSendChatMsgS2C_FieldNumber_Content = 6,
};

/**
 * 0x004300B5
 **/
@interface OClsSendChatMsgS2C : GPBMessage

@property(nonatomic, readwrite) uint64_t msgId;

@property(nonatomic, readwrite, strong, null_resettable) DoubleTUserInfo *userInfo;
/** Test to see if @c userInfo has been set. */
@property(nonatomic, readwrite) BOOL hasUserInfo;

@property(nonatomic, readwrite) uint64_t sendTm;

@property(nonatomic, readwrite) uint32_t type;

@property(nonatomic, readwrite, copy, null_resettable) NSString *option;

@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

@end

#pragma mark - OClsSendChatMsgS2CAck

typedef GPB_ENUM(OClsSendChatMsgS2CAck_FieldNumber) {
  OClsSendChatMsgS2CAck_FieldNumber_MsgId = 1,
};

/**
 * 0x004300B6
 **/
@interface OClsSendChatMsgS2CAck : GPBMessage

@property(nonatomic, readwrite) uint64_t msgId;

@end

#pragma mark - OClsPullChatMsgC2S

typedef GPB_ENUM(OClsPullChatMsgC2S_FieldNumber) {
  OClsPullChatMsgC2S_FieldNumber_LowMsgId = 1,
  OClsPullChatMsgC2S_FieldNumber_HighMsgId = 2,
};

/**
 * 0x004300B6
 **/
@interface OClsPullChatMsgC2S : GPBMessage

@property(nonatomic, readwrite) uint64_t lowMsgId;

@property(nonatomic, readwrite) uint64_t highMsgId;

@end

#pragma mark - OClsChatMsg

typedef GPB_ENUM(OClsChatMsg_FieldNumber) {
  OClsChatMsg_FieldNumber_MsgId = 1,
  OClsChatMsg_FieldNumber_UserInfo = 2,
  OClsChatMsg_FieldNumber_SendTm = 3,
  OClsChatMsg_FieldNumber_Type = 4,
  OClsChatMsg_FieldNumber_Option = 5,
  OClsChatMsg_FieldNumber_Content = 6,
};

@interface OClsChatMsg : GPBMessage

@property(nonatomic, readwrite) uint64_t msgId;

@property(nonatomic, readwrite, strong, null_resettable) DoubleTUserInfo *userInfo;
/** Test to see if @c userInfo has been set. */
@property(nonatomic, readwrite) BOOL hasUserInfo;

@property(nonatomic, readwrite) uint64_t sendTm;

@property(nonatomic, readwrite) uint32_t type;

@property(nonatomic, readwrite, copy, null_resettable) NSString *option;

@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

@end

#pragma mark - OClsPullChatMsgS2C

typedef GPB_ENUM(OClsPullChatMsgS2C_FieldNumber) {
  OClsPullChatMsgS2C_FieldNumber_RspCode = 1,
  OClsPullChatMsgS2C_FieldNumber_MinMsgId = 2,
  OClsPullChatMsgS2C_FieldNumber_MaxMsgId = 3,
  OClsPullChatMsgS2C_FieldNumber_MsgListArray = 4,
};

/**
 * 0x004300B8
 **/
@interface OClsPullChatMsgS2C : GPBMessage

@property(nonatomic, readwrite) uint32_t rspCode;

@property(nonatomic, readwrite) uint64_t minMsgId;

@property(nonatomic, readwrite) uint64_t maxMsgId;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<OClsChatMsg*> *msgListArray;
/** The number of items in @c msgListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger msgListArray_Count;

@end

#pragma mark - OClsLatestChatMsgNoitfy

typedef GPB_ENUM(OClsLatestChatMsgNoitfy_FieldNumber) {
  OClsLatestChatMsgNoitfy_FieldNumber_MsgListArray = 1,
};

/**
 * 0x004300B9
 **/
@interface OClsLatestChatMsgNoitfy : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<OClsChatMsg*> *msgListArray;
/** The number of items in @c msgListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger msgListArray_Count;

@end

#pragma mark - OClsChatMsgMediaOkC2S

typedef GPB_ENUM(OClsChatMsgMediaOkC2S_FieldNumber) {
  OClsChatMsgMediaOkC2S_FieldNumber_MsgId = 1,
  OClsChatMsgMediaOkC2S_FieldNumber_VecDataArray = 2,
};

/**
 * 0x004300BA
 **/
@interface OClsChatMsgMediaOkC2S : GPBMessage

@property(nonatomic, readwrite) uint64_t msgId;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *vecDataArray;
/** The number of items in @c vecDataArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger vecDataArray_Count;

@end

#pragma mark - OClsChatMsgMediaOkS2C

typedef GPB_ENUM(OClsChatMsgMediaOkS2C_FieldNumber) {
  OClsChatMsgMediaOkS2C_FieldNumber_RspCode = 1,
  OClsChatMsgMediaOkS2C_FieldNumber_MsgId = 2,
};

/**
 * 0x004300BB
 **/
@interface OClsChatMsgMediaOkS2C : GPBMessage

@property(nonatomic, readwrite) uint32_t rspCode;

@property(nonatomic, readwrite) uint64_t msgId;

@end

#pragma mark - OClsChatMsgMediaOkNotify

typedef GPB_ENUM(OClsChatMsgMediaOkNotify_FieldNumber) {
  OClsChatMsgMediaOkNotify_FieldNumber_MsgId = 1,
  OClsChatMsgMediaOkNotify_FieldNumber_VecDataArray = 2,
};

/**
 * 0x004300BC
 **/
@interface OClsChatMsgMediaOkNotify : GPBMessage

@property(nonatomic, readwrite) uint64_t msgId;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *vecDataArray;
/** The number of items in @c vecDataArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger vecDataArray_Count;

@end

#pragma mark - OClsSendCommNoticeC2S

typedef GPB_ENUM(OClsSendCommNoticeC2S_FieldNumber) {
  OClsSendCommNoticeC2S_FieldNumber_Content = 1,
};

/**
 * /notice 0x004300BD
 **/
@interface OClsSendCommNoticeC2S : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

@end

#pragma mark - OClsSendCommNoticeS2C

typedef GPB_ENUM(OClsSendCommNoticeS2C_FieldNumber) {
  OClsSendCommNoticeS2C_FieldNumber_RspCode = 1,
  OClsSendCommNoticeS2C_FieldNumber_Content = 2,
};

/**
 * 0x004300BE
 **/
@interface OClsSendCommNoticeS2C : GPBMessage

@property(nonatomic, readwrite) uint32_t rspCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

@end

#pragma mark - OClsSendCommNoticeNotify

typedef GPB_ENUM(OClsSendCommNoticeNotify_FieldNumber) {
  OClsSendCommNoticeNotify_FieldNumber_UserInfo = 1,
  OClsSendCommNoticeNotify_FieldNumber_Content = 2,
};

/**
 * 0x004300BF
 **/
@interface OClsSendCommNoticeNotify : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) DoubleTUserInfo *userInfo;
/** Test to see if @c userInfo has been set. */
@property(nonatomic, readwrite) BOOL hasUserInfo;

@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
