// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DoubleTUserList.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#import <Protobuf/GPBProtocolBuffers.h>

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class DoubleTUserInfo;
@class OClsCidUidPair;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - DoubleTuserListRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface DoubleTuserListRoot : GPBRootObject
@end

#pragma mark - OClsCidUidPair

typedef GPB_ENUM(OClsCidUidPair_FieldNumber) {
  OClsCidUidPair_FieldNumber_Cid = 1,
  OClsCidUidPair_FieldNumber_Uid = 2,
};

/**
 * 0x00430025,0x00440025
 **/
@interface OClsCidUidPair : GPBMessage

@property(nonatomic, readwrite) uint64_t cid;

@property(nonatomic, readwrite) uint64_t uid;

@end

#pragma mark - OClsForceLeaveC2S

typedef GPB_ENUM(OClsForceLeaveC2S_FieldNumber) {
  OClsForceLeaveC2S_FieldNumber_VecItemArray = 1,
  OClsForceLeaveC2S_FieldNumber_Reason = 2,
};

@interface OClsForceLeaveC2S : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<OClsCidUidPair*> *vecItemArray;
/** The number of items in @c vecItemArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger vecItemArray_Count;

@property(nonatomic, readwrite) uint32_t reason;

@end

#pragma mark - OClsForceLeaveS2C

typedef GPB_ENUM(OClsForceLeaveS2C_FieldNumber) {
  OClsForceLeaveS2C_FieldNumber_RspCode = 1,
  OClsForceLeaveS2C_FieldNumber_VecItemArray = 2,
};

/**
 * 0x00430026,0x00440026
 **/
@interface OClsForceLeaveS2C : GPBMessage

@property(nonatomic, readwrite) uint32_t rspCode;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<OClsCidUidPair*> *vecItemArray;
/** The number of items in @c vecItemArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger vecItemArray_Count;

@end

#pragma mark - OClsForceLeaveNotify

typedef GPB_ENUM(OClsForceLeaveNotify_FieldNumber) {
  OClsForceLeaveNotify_FieldNumber_Reason = 1,
  OClsForceLeaveNotify_FieldNumber_StrReason = 2,
};

/**
 * 0x00430027,0x00440027,0x00450027
 **/
@interface OClsForceLeaveNotify : GPBMessage

@property(nonatomic, readwrite) uint32_t reason;

@property(nonatomic, readwrite, copy, null_resettable) NSString *strReason;

@end

#pragma mark - OClsGetTeaListC2S

typedef GPB_ENUM(OClsGetTeaListC2S_FieldNumber) {
  OClsGetTeaListC2S_FieldNumber_Version = 1,
};

/**
 * 0x00430030、0x00440030、0x00450030
 **/
@interface OClsGetTeaListC2S : GPBMessage

@property(nonatomic, readwrite) uint32_t version;

@end

#pragma mark - OClsGetTeaListS2C

typedef GPB_ENUM(OClsGetTeaListS2C_FieldNumber) {
  OClsGetTeaListS2C_FieldNumber_RspCode = 1,
  OClsGetTeaListS2C_FieldNumber_Version = 2,
  OClsGetTeaListS2C_FieldNumber_VecTeaArray = 3,
};

/**
 * 0x00430031、0x00440031、0x00450031
 **/
@interface OClsGetTeaListS2C : GPBMessage

@property(nonatomic, readwrite) uint32_t rspCode;

@property(nonatomic, readwrite) uint32_t version;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<DoubleTUserInfo*> *vecTeaArray;
/** The number of items in @c vecTeaArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger vecTeaArray_Count;

@end

#pragma mark - OClsTeaListChangeNotify

typedef GPB_ENUM(OClsTeaListChangeNotify_FieldNumber) {
  OClsTeaListChangeNotify_FieldNumber_Version = 1,
};

/**
 * 0x00430032、0x00440032、0x00450032
 **/
@interface OClsTeaListChangeNotify : GPBMessage

@property(nonatomic, readwrite) uint32_t version;

@end

#pragma mark - OClsSetUserRightC2S

typedef GPB_ENUM(OClsSetUserRightC2S_FieldNumber) {
  OClsSetUserRightC2S_FieldNumber_Cid = 1,
  OClsSetUserRightC2S_FieldNumber_Uid = 2,
  OClsSetUserRightC2S_FieldNumber_OpType = 3,
  OClsSetUserRightC2S_FieldNumber_Offset = 4,
  OClsSetUserRightC2S_FieldNumber_Right = 5,
  OClsSetUserRightC2S_FieldNumber_Reserved = 6,
};

/**
 * 0x00430054, 0x00430057, 0x00440057
 **/
@interface OClsSetUserRightC2S : GPBMessage

@property(nonatomic, readwrite) uint64_t cid;

@property(nonatomic, readwrite) uint64_t uid;

@property(nonatomic, readwrite) uint32_t opType;

@property(nonatomic, readwrite) uint32_t offset;

@property(nonatomic, readwrite) uint32_t right;

@property(nonatomic, readwrite, copy, null_resettable) NSString *reserved;

@end

#pragma mark - OClsSetUserRightS2C

typedef GPB_ENUM(OClsSetUserRightS2C_FieldNumber) {
  OClsSetUserRightS2C_FieldNumber_RspCode = 1,
  OClsSetUserRightS2C_FieldNumber_OpType = 2,
  OClsSetUserRightS2C_FieldNumber_Offset = 3,
  OClsSetUserRightS2C_FieldNumber_Right = 4,
  OClsSetUserRightS2C_FieldNumber_UserInfo = 5,
  OClsSetUserRightS2C_FieldNumber_Reserved = 6,
};

/**
 * 0x00430055, 0x00430058, 0x00440058
 **/
@interface OClsSetUserRightS2C : GPBMessage

@property(nonatomic, readwrite) uint32_t rspCode;

@property(nonatomic, readwrite) uint32_t opType;

@property(nonatomic, readwrite) uint32_t offset;

@property(nonatomic, readwrite) uint32_t right;

@property(nonatomic, readwrite, strong, null_resettable) DoubleTUserInfo *userInfo;
/** Test to see if @c userInfo has been set. */
@property(nonatomic, readwrite) BOOL hasUserInfo;

@property(nonatomic, readwrite, copy, null_resettable) NSString *reserved;

@end

#pragma mark - OClsUserRightNotify

typedef GPB_ENUM(OClsUserRightNotify_FieldNumber) {
  OClsUserRightNotify_FieldNumber_OpType = 1,
  OClsUserRightNotify_FieldNumber_Offset = 2,
  OClsUserRightNotify_FieldNumber_Right = 3,
  OClsUserRightNotify_FieldNumber_OpUser = 4,
  OClsUserRightNotify_FieldNumber_UserInfo = 5,
  OClsUserRightNotify_FieldNumber_Reserved = 6,
};

/**
 * 0x00430056, 0x00430059, 0x00440056, 0x00440059,0x00450059
 **/
@interface OClsUserRightNotify : GPBMessage

@property(nonatomic, readwrite) uint32_t opType;

@property(nonatomic, readwrite) uint32_t offset;

@property(nonatomic, readwrite) uint32_t right;

@property(nonatomic, readwrite, strong, null_resettable) DoubleTUserInfo *opUser;
/** Test to see if @c opUser has been set. */
@property(nonatomic, readwrite) BOOL hasOpUser;

@property(nonatomic, readwrite, strong, null_resettable) DoubleTUserInfo *userInfo;
/** Test to see if @c userInfo has been set. */
@property(nonatomic, readwrite) BOOL hasUserInfo;

@property(nonatomic, readwrite, copy, null_resettable) NSString *reserved;

@end

#pragma mark - OClsSetUserSwitchC2S

typedef GPB_ENUM(OClsSetUserSwitchC2S_FieldNumber) {
  OClsSetUserSwitchC2S_FieldNumber_Cid = 1,
  OClsSetUserSwitchC2S_FieldNumber_Uid = 2,
  OClsSetUserSwitchC2S_FieldNumber_OpType = 3,
  OClsSetUserSwitchC2S_FieldNumber_Offset = 4,
  OClsSetUserSwitchC2S_FieldNumber_Switch_p = 5,
  OClsSetUserSwitchC2S_FieldNumber_Reserved = 6,
};

/**
 * 0x00430090, 0x00440090, 0x00450090
 **/
@interface OClsSetUserSwitchC2S : GPBMessage

@property(nonatomic, readwrite) uint64_t cid;

@property(nonatomic, readwrite) uint64_t uid;

@property(nonatomic, readwrite) uint32_t opType;

@property(nonatomic, readwrite) uint32_t offset;

@property(nonatomic, readwrite) uint32_t switch_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *reserved;

@end

#pragma mark - OClsSetUserSwitchS2C

typedef GPB_ENUM(OClsSetUserSwitchS2C_FieldNumber) {
  OClsSetUserSwitchS2C_FieldNumber_RspCode = 1,
  OClsSetUserSwitchS2C_FieldNumber_OpType = 2,
  OClsSetUserSwitchS2C_FieldNumber_Offset = 3,
  OClsSetUserSwitchS2C_FieldNumber_Switch_p = 4,
  OClsSetUserSwitchS2C_FieldNumber_UserInfo = 5,
  OClsSetUserSwitchS2C_FieldNumber_Reserved = 6,
};

/**
 * 0x00430091, 0x00440091, 0x00450091
 **/
@interface OClsSetUserSwitchS2C : GPBMessage

@property(nonatomic, readwrite) uint32_t rspCode;

@property(nonatomic, readwrite) uint32_t opType;

@property(nonatomic, readwrite) uint32_t offset;

@property(nonatomic, readwrite) uint32_t switch_p;

@property(nonatomic, readwrite, strong, null_resettable) DoubleTUserInfo *userInfo;
/** Test to see if @c userInfo has been set. */
@property(nonatomic, readwrite) BOOL hasUserInfo;

@property(nonatomic, readwrite, copy, null_resettable) NSString *reserved;

@end

#pragma mark - OClsUserSwitchNotify

typedef GPB_ENUM(OClsUserSwitchNotify_FieldNumber) {
  OClsUserSwitchNotify_FieldNumber_OpType = 1,
  OClsUserSwitchNotify_FieldNumber_Offset = 2,
  OClsUserSwitchNotify_FieldNumber_Switch_p = 3,
  OClsUserSwitchNotify_FieldNumber_OpUser = 4,
  OClsUserSwitchNotify_FieldNumber_UserInfo = 5,
  OClsUserSwitchNotify_FieldNumber_Reserved = 6,
};

/**
 * 0x00430092, 0x00440092, 0x00450092
 **/
@interface OClsUserSwitchNotify : GPBMessage

@property(nonatomic, readwrite) uint32_t opType;

@property(nonatomic, readwrite) uint32_t offset;

@property(nonatomic, readwrite) uint32_t switch_p;

@property(nonatomic, readwrite, strong, null_resettable) DoubleTUserInfo *opUser;
/** Test to see if @c opUser has been set. */
@property(nonatomic, readwrite) BOOL hasOpUser;

@property(nonatomic, readwrite, strong, null_resettable) DoubleTUserInfo *userInfo;
/** Test to see if @c userInfo has been set. */
@property(nonatomic, readwrite) BOOL hasUserInfo;

@property(nonatomic, readwrite, copy, null_resettable) NSString *reserved;

@end

#pragma mark - OClsGetUserInfoC2S

typedef GPB_ENUM(OClsGetUserInfoC2S_FieldNumber) {
  OClsGetUserInfoC2S_FieldNumber_Cid = 1,
  OClsGetUserInfoC2S_FieldNumber_Level = 2,
  OClsGetUserInfoC2S_FieldNumber_VecUidArray = 3,
};

/**
 * 0x00430093, 0x00440093, 0x00450093
 **/
@interface OClsGetUserInfoC2S : GPBMessage

@property(nonatomic, readwrite) uint64_t cid;

@property(nonatomic, readwrite) uint32_t level;

@property(nonatomic, readwrite, strong, null_resettable) GPBUInt64Array *vecUidArray;
/** The number of items in @c vecUidArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger vecUidArray_Count;

@end

#pragma mark - OClsGetUserInfoS2C

typedef GPB_ENUM(OClsGetUserInfoS2C_FieldNumber) {
  OClsGetUserInfoS2C_FieldNumber_RspCode = 1,
  OClsGetUserInfoS2C_FieldNumber_Cid = 2,
  OClsGetUserInfoS2C_FieldNumber_Level = 3,
  OClsGetUserInfoS2C_FieldNumber_VecUserInfoArray = 4,
};

/**
 * 0x00430094,0x00440094,0x00450094
 **/
@interface OClsGetUserInfoS2C : GPBMessage

@property(nonatomic, readwrite) uint32_t rspCode;

@property(nonatomic, readwrite) uint64_t cid;

@property(nonatomic, readwrite) uint32_t level;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<DoubleTUserInfo*> *vecUserInfoArray;
/** The number of items in @c vecUserInfoArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger vecUserInfoArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
