// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DoubleTClsClose.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#import <Protobuf/GPBProtocolBuffers.h>

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - DoubleTclsCloseRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface DoubleTclsCloseRoot : GPBRootObject
@end

#pragma mark - OClsCloseC2S

typedef GPB_ENUM(OClsCloseC2S_FieldNumber) {
  OClsCloseC2S_FieldNumber_Reason = 1,
  OClsCloseC2S_FieldNumber_Desp = 2,
};

/**
 * 0x0044001D、0x0044001D、0x0045001D
 **/
@interface OClsCloseC2S : GPBMessage

@property(nonatomic, readwrite) uint32_t reason;

@property(nonatomic, readwrite, copy, null_resettable) NSString *desp;

@end

#pragma mark - OClsCloseS2C

typedef GPB_ENUM(OClsCloseS2C_FieldNumber) {
  OClsCloseS2C_FieldNumber_RspCode = 1,
  OClsCloseS2C_FieldNumber_Reason = 2,
  OClsCloseS2C_FieldNumber_Desp = 3,
};

/**
 * 0x0044001E、0x0044001E、0x0045001E
 **/
@interface OClsCloseS2C : GPBMessage

@property(nonatomic, readwrite) uint32_t rspCode;

@property(nonatomic, readwrite) uint32_t reason;

@property(nonatomic, readwrite, copy, null_resettable) NSString *desp;

@end

#pragma mark - OClsCloseNotify

typedef GPB_ENUM(OClsCloseNotify_FieldNumber) {
  OClsCloseNotify_FieldNumber_Reason = 1,
  OClsCloseNotify_FieldNumber_Desp = 2,
};

/**
 * 0x0044001F、0x0044001F、0x0045001F
 **/
@interface OClsCloseNotify : GPBMessage

@property(nonatomic, readwrite) uint32_t reason;

@property(nonatomic, readwrite, copy, null_resettable) NSString *desp;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
