// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MSClsTbPageListChangeNotify.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#import <Protobuf/GPBProtocolBuffers.h>

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class MSClsTbPageListChangeNotify_PageItem;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - MsclsTbPageListChangeNotifyRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface MsclsTbPageListChangeNotifyRoot : GPBRootObject
@end

#pragma mark - MSClsTbPageListChangeNotify

typedef GPB_ENUM(MSClsTbPageListChangeNotify_FieldNumber) {
  MSClsTbPageListChangeNotify_FieldNumber_TextbookId = 1,
  MSClsTbPageListChangeNotify_FieldNumber_PageListArray = 2,
  MSClsTbPageListChangeNotify_FieldNumber_Version = 3,
};

/**
 * 课件页列表（课件页->教材页、空白页映射关系）变更通知
 * 0x00400067
 **/
@interface MSClsTbPageListChangeNotify : GPBMessage

@property(nonatomic, readwrite) uint32_t textbookId;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<MSClsTbPageListChangeNotify_PageItem*> *pageListArray;
/** The number of items in @c pageListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger pageListArray_Count;

@property(nonatomic, readwrite) uint32_t version;

@end

#pragma mark - MSClsTbPageListChangeNotify_PageItem

typedef GPB_ENUM(MSClsTbPageListChangeNotify_PageItem_FieldNumber) {
  MSClsTbPageListChangeNotify_PageItem_FieldNumber_Page = 1,
  MSClsTbPageListChangeNotify_PageItem_FieldNumber_CrswarePage = 2,
  MSClsTbPageListChangeNotify_PageItem_FieldNumber_Uid = 3,
  MSClsTbPageListChangeNotify_PageItem_FieldNumber_Time = 4,
  MSClsTbPageListChangeNotify_PageItem_FieldNumber_Seq = 5,
};

@interface MSClsTbPageListChangeNotify_PageItem : GPBMessage

@property(nonatomic, readwrite) uint32_t page;

@property(nonatomic, readwrite) int32_t crswarePage;

@property(nonatomic, readwrite) uint64_t uid;

@property(nonatomic, readwrite) uint64_t time;

@property(nonatomic, readwrite) uint32_t seq;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
