// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MSClsCurTbPageNotify.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#import <Protobuf/GPBProtocolBuffers.h>

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - MsclsCurTbPageNotifyRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface MsclsCurTbPageNotifyRoot : GPBRootObject
@end

#pragma mark - MSClsCurTbPageNotify

typedef GPB_ENUM(MSClsCurTbPageNotify_FieldNumber) {
  MSClsCurTbPageNotify_FieldNumber_TextbookId = 1,
  MSClsCurTbPageNotify_FieldNumber_Page = 2,
  MSClsCurTbPageNotify_FieldNumber_Version = 3,
  MSClsCurTbPageNotify_FieldNumber_Uid = 4,
  MSClsCurTbPageNotify_FieldNumber_SubPage = 5,
};

/**
 * 下发当前使用的教材+课件页码通知
 * 0x00400062
 **/
@interface MSClsCurTbPageNotify : GPBMessage

@property(nonatomic, readwrite) uint32_t textbookId;

@property(nonatomic, readwrite) uint32_t page;

@property(nonatomic, readwrite) uint32_t version;

@property(nonatomic, readwrite) uint64_t uid;

@property(nonatomic, readwrite) uint32_t subPage;
@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
