#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)
#ifndef ROOMBOXPLAYBACK_SWIFT_H
#define ROOMBOXPLAYBACK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import AVFoundation;
@import AliyunPlayer;
@import CoreGraphics;
@import Foundation;
@import ObjectiveC;
@import RoomBoxUtils;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="RoomBoxPlayback",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class NSCoder;

SWIFT_CLASS("_TtC15RoomBoxPlayback12ABPlayerCore")
@interface ABPlayerCore : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)layoutSubviews;
@end




SWIFT_PROTOCOL("_TtP15RoomBoxPlayback20ABPlayerCoreProtocol_")
@protocol ABPlayerCoreProtocol <NSObject>
- (void)play;
- (void)pause;
- (BOOL)isPlaying SWIFT_WARN_UNUSED_RESULT;
- (void)seekWithPosition:(int64_t)position;
- (void)setPlaySpeedWithSpeed:(float)speed;
- (void)muteWithMute:(BOOL)mute;
- (void)stop;
- (void)retry;
- (void)trialEnd;
@property (nonatomic) float rate;
@property (nonatomic) BOOL isMuted;
@property (nonatomic, readonly) int64_t duration;
@property (nonatomic, readonly) int64_t currentTime;
@end


@interface ABPlayerCore (SWIFT_EXTENSION(RoomBoxPlayback)) <ABPlayerCoreProtocol>
@property (nonatomic) float rate;
@property (nonatomic) BOOL isMuted;
@property (nonatomic, readonly) int64_t duration;
@property (nonatomic, readonly) int64_t currentTime;
- (void)pause;
- (void)stop;
- (void)play;
- (BOOL)isPlaying SWIFT_WARN_UNUSED_RESULT;
- (void)seekWithPosition:(int64_t)position;
- (void)setPlaySpeedWithSpeed:(float)speed;
- (void)muteWithMute:(BOOL)mute;
- (void)retry;
- (void)trialEnd;
@end


@protocol ABPlayerViewDelegate;

SWIFT_CLASS("_TtC15RoomBoxPlayback12ABPlayerView")
@interface ABPlayerView : UIView
@property (nonatomic, weak) id <ABPlayerViewDelegate> _Nullable delegate;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)InitAmazingBoxEnvWithType:(NSInteger)type;
- (void)EnterAmazingBoxWithType:(NSInteger)type uid:(NSString * _Nonnull)uid userToken:(NSString * _Nonnull)userToken cid:(NSString * _Nonnull)cid nickName:(NSString * _Nonnull)nickName;
- (void)Destroy;
@end




SWIFT_PROTOCOL("_TtP15RoomBoxPlayback20ABPlayerViewDelegate_")
@protocol ABPlayerViewDelegate <NSObject>
- (void)backButtonTapped;
@end


SWIFT_CLASS("_TtC15RoomBoxPlayback12AVPlayerView")
@interface AVPlayerView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@end


@interface AVPlayerView (SWIFT_EXTENSION(RoomBoxPlayback)) <CicadaRenderingDelegate>
@end


@interface AVPlayerView (SWIFT_EXTENSION(RoomBoxPlayback)) <CicadaAudioSessionDelegate>
- (BOOL)setActive:(BOOL)active error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setCategory:(NSString * _Null_unspecified)category withOptions:(AVAudioSessionCategoryOptions)options error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setCategory:(AVAudioSessionCategory _Null_unspecified)category mode:(AVAudioSessionMode _Null_unspecified)mode routeSharingPolicy:(AVAudioSessionRouteSharingPolicy)policy options:(AVAudioSessionCategoryOptions)options error:(NSError * _Nullable * _Nullable)error;
@end

@class AliPlayer;
@class AVPErrorModel;
@class AVPTrackInfo;

@interface AVPlayerView (SWIFT_EXTENSION(RoomBoxPlayback)) <AVPDelegate>
/// @brief 播放器事件回调
/// @param player 播放器player指针
/// @param eventType 播放器事件类型
/// @see AVPEventType
- (void)onPlayerEvent:(AliPlayer * _Null_unspecified)player eventType:(AVPEventType)eventType;
- (void)onPlayerEvent:(AliPlayer * _Null_unspecified)player eventWithString:(AVPEventWithString)eventWithString description:(NSString * _Null_unspecified)description;
- (void)onError:(AliPlayer * _Null_unspecified)player errorModel:(AVPErrorModel * _Null_unspecified)errorModel;
- (void)onVideoSizeChanged:(AliPlayer * _Null_unspecified)player width:(int32_t)width height:(int32_t)height rotation:(int32_t)rotation;
- (void)onCurrentPositionUpdate:(AliPlayer * _Null_unspecified)player position:(int64_t)position;
- (void)onBufferedPositionUpdate:(AliPlayer * _Null_unspecified)player position:(int64_t)position;
- (void)onLoadingProgress:(AliPlayer * _Null_unspecified)player progress:(float)progress;
- (void)onCurrentDownloadSpeed:(AliPlayer * _Null_unspecified)player speed:(int64_t)speed;
- (void)onTrackReady:(AliPlayer * _Null_unspecified)player info:(NSArray<AVPTrackInfo *> * _Null_unspecified)info;
- (int32_t)onChooseTrackIndex:(AliPlayer * _Null_unspecified)player info:(NSArray<AVPTrackInfo *> * _Null_unspecified)info SWIFT_WARN_UNUSED_RESULT;
- (void)onTrackChanged:(AliPlayer * _Null_unspecified)player info:(AVPTrackInfo * _Null_unspecified)info;
- (void)onSubtitleExtAdded:(AliPlayer * _Null_unspecified)player trackIndex:(int32_t)trackIndex URL:(NSString * _Null_unspecified)URL;
- (void)onSubtitleShow:(AliPlayer * _Null_unspecified)player trackIndex:(int32_t)trackIndex subtitleID:(NSInteger)subtitleID subtitle:(NSString * _Null_unspecified)subtitle;
- (void)onPlayerStatusChanged:(AliPlayer * _Null_unspecified)player oldStatus:(AVPStatus)oldStatus newStatus:(AVPStatus)newStatus;
- (void)onSEIData:(AliPlayer * _Null_unspecified)player type:(int32_t)type data:(NSData * _Null_unspecified)data;
- (void)onVideoRendered:(AliPlayer * _Null_unspecified)player timeMs:(int64_t)timeMs pts:(int64_t)pts;
@end


SWIFT_CLASS("_TtC15RoomBoxPlayback15AnswerSheetView")
@interface AnswerSheetView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC15RoomBoxPlayback10BrowerView")
@interface BrowerView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end



SWIFT_CLASS("_TtC15RoomBoxPlayback13ICWBrowerView")
@interface ICWBrowerView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end



SWIFT_CLASS("_TtC15RoomBoxPlayback19RoomBoxPlayerBundle")
@interface RoomBoxPlayerBundle : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIViewController;
@protocol RBPhotoProtocol;

SWIFT_CLASS("_TtC15RoomBoxPlayback35RoomBoxPlayerChatPreviewImageModule")
@interface RoomBoxPlayerChatPreviewImageModule : NSObject
+ (void)prepareConfig;
+ (UIViewController * _Nullable)previewImageWithUrls:(NSArray<NSString *> * _Nonnull)urls selectedIndex:(uint32_t)selectedIndex SWIFT_WARN_UNUSED_RESULT;
+ (NSArray<id <RBPhotoProtocol>> * _Nonnull)createPhotosWithUrls:(NSArray<NSString *> * _Nonnull)urls SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15RoomBoxPlayback24RoomBoxPlayerColorConfig")
@interface RoomBoxPlayerColorConfig : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15RoomBoxPlayback30RoomBoxPlayerColorPanelConvert")
@interface RoomBoxPlayerColorPanelConvert : NSObject
+ (NSString * _Nonnull)convertWithFro:(NSString * _Nonnull)fro SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class XDFThemeColorPicker;
@class XDFThemeCGColorPicker;

SWIFT_CLASS("_TtC15RoomBoxPlayback30RoomBoxPlayerColorPanelManager")
@interface RoomBoxPlayerColorPanelManager : NSObject
+ (void)config;
+ (XDFThemeColorPicker * _Nullable)colorThemePickerWithFro:(NSString * _Nonnull)fro SWIFT_WARN_UNUSED_RESULT;
+ (XDFThemeCGColorPicker * _Nullable)cgColorThemePickerWithFro:(NSString * _Nonnull)fro SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIImage;

SWIFT_CLASS("_TtC15RoomBoxPlayback30RoomBoxPlayerImageThemeManager")
@interface RoomBoxPlayerImageThemeManager : NSObject
+ (NSObject * _Nonnull)themeImageWithPrefix:(NSString * _Nonnull)prefix handle:(id _Nullable (^ _Nullable)(id _Nullable))handle SWIFT_WARN_UNUSED_RESULT;
+ (UIImage * _Nullable)ocImageWithPrefix:(NSString * _Nonnull)prefix themeValue:(NSString * _Nullable)themeValue SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15RoomBoxPlayback20RoomBoxPlayerLogUtil")
@interface RoomBoxPlayerLogUtil : NSObject
@property (nonatomic, copy) NSString * _Nullable cid;
@property (nonatomic, copy) NSString * _Nullable class_type;
@property (nonatomic, readonly, copy) NSString * _Nonnull RoomBoxPlayerLogEventActionKey;
@property (nonatomic, readonly, copy) NSString * _Nonnull RoomBoxPlayerLogEventPlayRecord;
@property (nonatomic, readonly, copy) NSString * _Nonnull RoomBoxPlayerLogEventDecodeVfps;
@property (nonatomic, readonly, copy) NSString * _Nonnull RoomBoxPlayerLogEventRenderVfps;
@property (nonatomic, readonly, copy) NSString * _Nonnull RoomBoxPlayerLogEventBitRate;
@property (nonatomic, readonly, copy) NSString * _Nonnull RoomBoxPlayerLogEventTCPSpeed;
@property (nonatomic, readonly, copy) NSString * _Nonnull RoomBoxPlayerLogEventPageIO;
@property (nonatomic, readonly, copy) NSString * _Nonnull RoomBoxPlayerLogEventPlayCtrl;
@property (nonatomic, readonly, copy) NSString * _Nonnull RoomBoxPlayerLogEventPlayResult;
@property (nonatomic, readonly, copy) NSString * _Nonnull RoomBoxPlayerLogEventSpeedCtrl;
@property (nonatomic, readonly, copy) NSString * _Nonnull RoomBoxPlayerLogEventAirplayPage;
@property (nonatomic, readonly, copy) NSString * _Nonnull RoomBoxPlayerLogEventAirplayCtrl;
@property (nonatomic, readonly, copy) NSString * _Nonnull RoomBoxPlayerLogEventKnowledgeView;
@property (nonatomic, readonly, copy) NSString * _Nonnull RoomBoxPlayerLogEventKnowledgeLocate;
@property (nonatomic, readonly, copy) NSString * _Nonnull RoomBoxPlayerLogEventKnowledgePage;
@property (nonatomic, readonly, copy) NSString * _Nonnull RoomBoxPlayerLogEventSurfingMode;
@property (nonatomic, readonly, copy) NSString * _Nonnull RoomBoxPlayerLogEventChatPage;
@property (nonatomic, readonly, copy) NSString * _Nonnull RoomBoxPlayerLogEventSnapshot;
@property (nonatomic, readonly, copy) NSString * _Nonnull RoomBoxPlayerLogEventMarkpoint;
- (void)addPlayerActionLogWithEventId:(NSString * _Nonnull)eventId;
- (void)addPlayerActionLogWithEventId:(NSString * _Nonnull)eventId key:(NSString * _Nonnull)key value:(NSString * _Nonnull)value;
- (void)addPlayerMatrixLogWithEventId:(NSString * _Nonnull)eventId key:(NSString * _Nonnull)key value:(NSString * _Nonnull)value;
- (void)addPlayerRecordLogWithMainId:(NSString * _Nullable)mainId records:(NSArray<NSNumber *> * _Nonnull)records lastRecord:(NSInteger)lastRecord;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15RoomBoxPlayback29RoomBoxPlayerRequestDataModel")
@interface RoomBoxPlayerRequestDataModel : NSObject
@property (nonatomic, copy) NSString * _Nullable code;
@property (nonatomic, copy) NSString * _Nullable msg;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable data;
@property (nonatomic, copy) NSString * _Nullable url;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15RoomBoxPlayback27RoomBoxPlayerRequestManager")
@interface RoomBoxPlayerRequestManager : NSObject
+ (void)requestAddKnowledgeMarkWithParameters:(NSDictionary<NSString *, id> * _Nullable)parameters token:(NSString * _Nonnull)token completionHandler:(void (^ _Nonnull)(RoomBoxPlayerRequestDataModel * _Nullable))completionHandler errorHandler:(void (^ _Nonnull)(RoomBoxPlayerRequestDataModel * _Nullable))errorHandler networkFailHandler:(void (^ _Nonnull)(NSError * _Nonnull))networkFailHandler;
+ (void)requestPlayBackInfoWithParameters:(NSDictionary<NSString *, id> * _Nullable)parameters token:(NSString * _Nonnull)token completionHandler:(void (^ _Nonnull)(RoomBoxPlayerRequestDataModel * _Nullable))completionHandler errorHandler:(void (^ _Nonnull)(RoomBoxPlayerRequestDataModel * _Nullable))errorHandler networkFailHandler:(void (^ _Nonnull)(NSError * _Nonnull))networkFailHandler;
+ (void)requestDeleteKnowledgeMarkWithNoteId:(NSString * _Nonnull)noteId token:(NSString * _Nonnull)token completionHandler:(void (^ _Nonnull)(RoomBoxPlayerRequestDataModel * _Nullable))completionHandler errorHandler:(void (^ _Nonnull)(RoomBoxPlayerRequestDataModel * _Nullable))errorHandler networkFailHandler:(void (^ _Nonnull)(NSError * _Nonnull))networkFailHandler;
+ (void)requestNoteListWithClassroomId:(NSString * _Nonnull)classroomId token:(NSString * _Nonnull)token completionHandler:(void (^ _Nonnull)(RoomBoxPlayerRequestDataModel * _Nullable))completionHandler errorHandler:(void (^ _Nonnull)(RoomBoxPlayerRequestDataModel * _Nullable))errorHandler networkFailHandler:(void (^ _Nonnull)(NSError * _Nonnull))networkFailHandler;
+ (void)requestRecordNoteListWithClassroomId:(NSString * _Nonnull)classroomId token:(NSString * _Nonnull)token completionHandler:(void (^ _Nonnull)(RoomBoxPlayerRequestDataModel * _Nullable))completionHandler errorHandler:(void (^ _Nonnull)(RoomBoxPlayerRequestDataModel * _Nullable))errorHandler networkFailHandler:(void (^ _Nonnull)(NSError * _Nonnull))networkFailHandler;
+ (void)requestChatHistoryWithCid:(NSString * _Nonnull)cid page:(NSInteger)page pageSize:(NSInteger)pageSize token:(NSString * _Nonnull)token completionHandler:(void (^ _Nonnull)(RoomBoxPlayerRequestDataModel * _Nullable))completionHandler errorHandler:(void (^ _Nonnull)(RoomBoxPlayerRequestDataModel * _Nullable))errorHandler networkFailHandler:(void (^ _Nonnull)(NSError * _Nonnull))networkFailHandler;
+ (void)requestRecordHistoryWithCid:(NSString * _Nonnull)cid token:(NSString * _Nonnull)token completionHandler:(void (^ _Nonnull)(RoomBoxPlayerRequestDataModel * _Nullable))completionHandler errorHandler:(void (^ _Nonnull)(RoomBoxPlayerRequestDataModel * _Nullable))errorHandler networkFailHandler:(void (^ _Nonnull)(NSError * _Nonnull))networkFailHandler;
+ (void)requestVideoConfigWithCid:(NSString * _Nonnull)cid token:(NSString * _Nonnull)token completionHandler:(void (^ _Nonnull)(RoomBoxPlayerRequestDataModel * _Nullable))completionHandler errorHandler:(void (^ _Nonnull)(RoomBoxPlayerRequestDataModel * _Nullable))errorHandler networkFailHandler:(void (^ _Nonnull)(NSError * _Nonnull))networkFailHandler;
+ (void)requestAddStarWithCid:(NSString * _Nonnull)cid token:(NSString * _Nonnull)token playTime:(NSString * _Nonnull)playTime completionHandler:(void (^ _Nonnull)(RoomBoxPlayerRequestDataModel * _Nullable))completionHandler errorHandler:(void (^ _Nonnull)(RoomBoxPlayerRequestDataModel * _Nullable))errorHandler networkFailHandler:(void (^ _Nonnull)(NSError * _Nonnull))networkFailHandler;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSBundle;

SWIFT_CLASS("_TtC15RoomBoxPlayback30RoomBoxPlayerSacQuizController")
@interface RoomBoxPlayerSacQuizController : RBBaseViewController
@property (nonatomic, copy) void (^ _Nullable closeClosure)(void);
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface RoomBoxPlayerSacQuizController (SWIFT_EXTENSION(RoomBoxPlayback)) <RBRotateProtocol>
- (BOOL)rbShouldAutorotate SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) UIInterfaceOrientationMask supportedInterfaceOrientations;
@end


@interface RoomBoxPlayerSacQuizController (SWIFT_EXTENSION(RoomBoxPlayback))
- (void)showOnView:(UIView * _Nonnull)onView urlString:(NSString * _Nonnull)urlString param:(NSDictionary<NSString *, NSString *> * _Nullable)param;
@end


SWIFT_CLASS("_TtC15RoomBoxPlayback32RoomBoxRecordKnowledgeCloseAlert")
@interface RoomBoxRecordKnowledgeCloseAlert : UIView
@property (nonatomic, copy) void (^ _Nullable closeClosure)(void);
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@end



@interface RoomBoxRecordKnowledgeCloseAlert (SWIFT_EXTENSION(RoomBoxPlayback))
- (void)hiddenCancleBtn;
@end


SWIFT_CLASS("_TtC15RoomBoxPlayback32RoomBoxRecordKnowledgeController")
@interface RoomBoxRecordKnowledgeController : RBBaseViewController
@property (nonatomic, copy) void (^ _Nullable closeClosure)(void);
- (void)configWebUrlWithUrlString:(NSString * _Nonnull)urlString param:(NSDictionary<NSString *, NSString *> * _Nullable)param;
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__ARM_ARCH_7A__) && __ARM_ARCH_7A__
// Generated by Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)
#ifndef ROOMBOXPLAYBACK_SWIFT_H
#define ROOMBOXPLAYBACK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import AVFoundation;
@import AliyunPlayer;
@import CoreGraphics;
@import Foundation;
@import ObjectiveC;
@import RoomBoxUtils;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="RoomBoxPlayback",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class NSCoder;

SWIFT_CLASS("_TtC15RoomBoxPlayback12ABPlayerCore")
@interface ABPlayerCore : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)layoutSubviews;
@end




SWIFT_PROTOCOL("_TtP15RoomBoxPlayback20ABPlayerCoreProtocol_")
@protocol ABPlayerCoreProtocol <NSObject>
- (void)play;
- (void)pause;
- (BOOL)isPlaying SWIFT_WARN_UNUSED_RESULT;
- (void)seekWithPosition:(int64_t)position;
- (void)setPlaySpeedWithSpeed:(float)speed;
- (void)muteWithMute:(BOOL)mute;
- (void)stop;
- (void)retry;
- (void)trialEnd;
@property (nonatomic) float rate;
@property (nonatomic) BOOL isMuted;
@property (nonatomic, readonly) int64_t duration;
@property (nonatomic, readonly) int64_t currentTime;
@end


@interface ABPlayerCore (SWIFT_EXTENSION(RoomBoxPlayback)) <ABPlayerCoreProtocol>
@property (nonatomic) float rate;
@property (nonatomic) BOOL isMuted;
@property (nonatomic, readonly) int64_t duration;
@property (nonatomic, readonly) int64_t currentTime;
- (void)pause;
- (void)stop;
- (void)play;
- (BOOL)isPlaying SWIFT_WARN_UNUSED_RESULT;
- (void)seekWithPosition:(int64_t)position;
- (void)setPlaySpeedWithSpeed:(float)speed;
- (void)muteWithMute:(BOOL)mute;
- (void)retry;
- (void)trialEnd;
@end


@protocol ABPlayerViewDelegate;

SWIFT_CLASS("_TtC15RoomBoxPlayback12ABPlayerView")
@interface ABPlayerView : UIView
@property (nonatomic, weak) id <ABPlayerViewDelegate> _Nullable delegate;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)InitAmazingBoxEnvWithType:(NSInteger)type;
- (void)EnterAmazingBoxWithType:(NSInteger)type uid:(NSString * _Nonnull)uid userToken:(NSString * _Nonnull)userToken cid:(NSString * _Nonnull)cid nickName:(NSString * _Nonnull)nickName;
- (void)Destroy;
@end




SWIFT_PROTOCOL("_TtP15RoomBoxPlayback20ABPlayerViewDelegate_")
@protocol ABPlayerViewDelegate <NSObject>
- (void)backButtonTapped;
@end


SWIFT_CLASS("_TtC15RoomBoxPlayback12AVPlayerView")
@interface AVPlayerView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@end


@interface AVPlayerView (SWIFT_EXTENSION(RoomBoxPlayback)) <CicadaRenderingDelegate>
@end


@interface AVPlayerView (SWIFT_EXTENSION(RoomBoxPlayback)) <CicadaAudioSessionDelegate>
- (BOOL)setActive:(BOOL)active error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setCategory:(NSString * _Null_unspecified)category withOptions:(AVAudioSessionCategoryOptions)options error:(NSError * _Nullable * _Nullable)error;
- (BOOL)setCategory:(AVAudioSessionCategory _Null_unspecified)category mode:(AVAudioSessionMode _Null_unspecified)mode routeSharingPolicy:(AVAudioSessionRouteSharingPolicy)policy options:(AVAudioSessionCategoryOptions)options error:(NSError * _Nullable * _Nullable)error;
@end

@class AliPlayer;
@class AVPErrorModel;
@class AVPTrackInfo;

@interface AVPlayerView (SWIFT_EXTENSION(RoomBoxPlayback)) <AVPDelegate>
/// @brief 播放器事件回调
/// @param player 播放器player指针
/// @param eventType 播放器事件类型
/// @see AVPEventType
- (void)onPlayerEvent:(AliPlayer * _Null_unspecified)player eventType:(AVPEventType)eventType;
- (void)onPlayerEvent:(AliPlayer * _Null_unspecified)player eventWithString:(AVPEventWithString)eventWithString description:(NSString * _Null_unspecified)description;
- (void)onError:(AliPlayer * _Null_unspecified)player errorModel:(AVPErrorModel * _Null_unspecified)errorModel;
- (void)onVideoSizeChanged:(AliPlayer * _Null_unspecified)player width:(int32_t)width height:(int32_t)height rotation:(int32_t)rotation;
- (void)onCurrentPositionUpdate:(AliPlayer * _Null_unspecified)player position:(int64_t)position;
- (void)onBufferedPositionUpdate:(AliPlayer * _Null_unspecified)player position:(int64_t)position;
- (void)onLoadingProgress:(AliPlayer * _Null_unspecified)player progress:(float)progress;
- (void)onCurrentDownloadSpeed:(AliPlayer * _Null_unspecified)player speed:(int64_t)speed;
- (void)onTrackReady:(AliPlayer * _Null_unspecified)player info:(NSArray<AVPTrackInfo *> * _Null_unspecified)info;
- (int32_t)onChooseTrackIndex:(AliPlayer * _Null_unspecified)player info:(NSArray<AVPTrackInfo *> * _Null_unspecified)info SWIFT_WARN_UNUSED_RESULT;
- (void)onTrackChanged:(AliPlayer * _Null_unspecified)player info:(AVPTrackInfo * _Null_unspecified)info;
- (void)onSubtitleExtAdded:(AliPlayer * _Null_unspecified)player trackIndex:(int32_t)trackIndex URL:(NSString * _Null_unspecified)URL;
- (void)onSubtitleShow:(AliPlayer * _Null_unspecified)player trackIndex:(int32_t)trackIndex subtitleID:(NSInteger)subtitleID subtitle:(NSString * _Null_unspecified)subtitle;
- (void)onPlayerStatusChanged:(AliPlayer * _Null_unspecified)player oldStatus:(AVPStatus)oldStatus newStatus:(AVPStatus)newStatus;
- (void)onSEIData:(AliPlayer * _Null_unspecified)player type:(int32_t)type data:(NSData * _Null_unspecified)data;
- (void)onVideoRendered:(AliPlayer * _Null_unspecified)player timeMs:(int64_t)timeMs pts:(int64_t)pts;
@end


SWIFT_CLASS("_TtC15RoomBoxPlayback15AnswerSheetView")
@interface AnswerSheetView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC15RoomBoxPlayback10BrowerView")
@interface BrowerView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end



SWIFT_CLASS("_TtC15RoomBoxPlayback13ICWBrowerView")
@interface ICWBrowerView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end



SWIFT_CLASS("_TtC15RoomBoxPlayback19RoomBoxPlayerBundle")
@interface RoomBoxPlayerBundle : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIViewController;
@protocol RBPhotoProtocol;

SWIFT_CLASS("_TtC15RoomBoxPlayback35RoomBoxPlayerChatPreviewImageModule")
@interface RoomBoxPlayerChatPreviewImageModule : NSObject
+ (void)prepareConfig;
+ (UIViewController * _Nullable)previewImageWithUrls:(NSArray<NSString *> * _Nonnull)urls selectedIndex:(uint32_t)selectedIndex SWIFT_WARN_UNUSED_RESULT;
+ (NSArray<id <RBPhotoProtocol>> * _Nonnull)createPhotosWithUrls:(NSArray<NSString *> * _Nonnull)urls SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15RoomBoxPlayback24RoomBoxPlayerColorConfig")
@interface RoomBoxPlayerColorConfig : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15RoomBoxPlayback30RoomBoxPlayerColorPanelConvert")
@interface RoomBoxPlayerColorPanelConvert : NSObject
+ (NSString * _Nonnull)convertWithFro:(NSString * _Nonnull)fro SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class XDFThemeColorPicker;
@class XDFThemeCGColorPicker;

SWIFT_CLASS("_TtC15RoomBoxPlayback30RoomBoxPlayerColorPanelManager")
@interface RoomBoxPlayerColorPanelManager : NSObject
+ (void)config;
+ (XDFThemeColorPicker * _Nullable)colorThemePickerWithFro:(NSString * _Nonnull)fro SWIFT_WARN_UNUSED_RESULT;
+ (XDFThemeCGColorPicker * _Nullable)cgColorThemePickerWithFro:(NSString * _Nonnull)fro SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIImage;

SWIFT_CLASS("_TtC15RoomBoxPlayback30RoomBoxPlayerImageThemeManager")
@interface RoomBoxPlayerImageThemeManager : NSObject
+ (NSObject * _Nonnull)themeImageWithPrefix:(NSString * _Nonnull)prefix handle:(id _Nullable (^ _Nullable)(id _Nullable))handle SWIFT_WARN_UNUSED_RESULT;
+ (UIImage * _Nullable)ocImageWithPrefix:(NSString * _Nonnull)prefix themeValue:(NSString * _Nullable)themeValue SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15RoomBoxPlayback20RoomBoxPlayerLogUtil")
@interface RoomBoxPlayerLogUtil : NSObject
@property (nonatomic, copy) NSString * _Nullable cid;
@property (nonatomic, copy) NSString * _Nullable class_type;
@property (nonatomic, readonly, copy) NSString * _Nonnull RoomBoxPlayerLogEventActionKey;
@property (nonatomic, readonly, copy) NSString * _Nonnull RoomBoxPlayerLogEventPlayRecord;
@property (nonatomic, readonly, copy) NSString * _Nonnull RoomBoxPlayerLogEventDecodeVfps;
@property (nonatomic, readonly, copy) NSString * _Nonnull RoomBoxPlayerLogEventRenderVfps;
@property (nonatomic, readonly, copy) NSString * _Nonnull RoomBoxPlayerLogEventBitRate;
@property (nonatomic, readonly, copy) NSString * _Nonnull RoomBoxPlayerLogEventTCPSpeed;
@property (nonatomic, readonly, copy) NSString * _Nonnull RoomBoxPlayerLogEventPageIO;
@property (nonatomic, readonly, copy) NSString * _Nonnull RoomBoxPlayerLogEventPlayCtrl;
@property (nonatomic, readonly, copy) NSString * _Nonnull RoomBoxPlayerLogEventPlayResult;
@property (nonatomic, readonly, copy) NSString * _Nonnull RoomBoxPlayerLogEventSpeedCtrl;
@property (nonatomic, readonly, copy) NSString * _Nonnull RoomBoxPlayerLogEventAirplayPage;
@property (nonatomic, readonly, copy) NSString * _Nonnull RoomBoxPlayerLogEventAirplayCtrl;
@property (nonatomic, readonly, copy) NSString * _Nonnull RoomBoxPlayerLogEventKnowledgeView;
@property (nonatomic, readonly, copy) NSString * _Nonnull RoomBoxPlayerLogEventKnowledgeLocate;
@property (nonatomic, readonly, copy) NSString * _Nonnull RoomBoxPlayerLogEventKnowledgePage;
@property (nonatomic, readonly, copy) NSString * _Nonnull RoomBoxPlayerLogEventSurfingMode;
@property (nonatomic, readonly, copy) NSString * _Nonnull RoomBoxPlayerLogEventChatPage;
@property (nonatomic, readonly, copy) NSString * _Nonnull RoomBoxPlayerLogEventSnapshot;
@property (nonatomic, readonly, copy) NSString * _Nonnull RoomBoxPlayerLogEventMarkpoint;
- (void)addPlayerActionLogWithEventId:(NSString * _Nonnull)eventId;
- (void)addPlayerActionLogWithEventId:(NSString * _Nonnull)eventId key:(NSString * _Nonnull)key value:(NSString * _Nonnull)value;
- (void)addPlayerMatrixLogWithEventId:(NSString * _Nonnull)eventId key:(NSString * _Nonnull)key value:(NSString * _Nonnull)value;
- (void)addPlayerRecordLogWithMainId:(NSString * _Nullable)mainId records:(NSArray<NSNumber *> * _Nonnull)records lastRecord:(NSInteger)lastRecord;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15RoomBoxPlayback29RoomBoxPlayerRequestDataModel")
@interface RoomBoxPlayerRequestDataModel : NSObject
@property (nonatomic, copy) NSString * _Nullable code;
@property (nonatomic, copy) NSString * _Nullable msg;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable data;
@property (nonatomic, copy) NSString * _Nullable url;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15RoomBoxPlayback27RoomBoxPlayerRequestManager")
@interface RoomBoxPlayerRequestManager : NSObject
+ (void)requestAddKnowledgeMarkWithParameters:(NSDictionary<NSString *, id> * _Nullable)parameters token:(NSString * _Nonnull)token completionHandler:(void (^ _Nonnull)(RoomBoxPlayerRequestDataModel * _Nullable))completionHandler errorHandler:(void (^ _Nonnull)(RoomBoxPlayerRequestDataModel * _Nullable))errorHandler networkFailHandler:(void (^ _Nonnull)(NSError * _Nonnull))networkFailHandler;
+ (void)requestPlayBackInfoWithParameters:(NSDictionary<NSString *, id> * _Nullable)parameters token:(NSString * _Nonnull)token completionHandler:(void (^ _Nonnull)(RoomBoxPlayerRequestDataModel * _Nullable))completionHandler errorHandler:(void (^ _Nonnull)(RoomBoxPlayerRequestDataModel * _Nullable))errorHandler networkFailHandler:(void (^ _Nonnull)(NSError * _Nonnull))networkFailHandler;
+ (void)requestDeleteKnowledgeMarkWithNoteId:(NSString * _Nonnull)noteId token:(NSString * _Nonnull)token completionHandler:(void (^ _Nonnull)(RoomBoxPlayerRequestDataModel * _Nullable))completionHandler errorHandler:(void (^ _Nonnull)(RoomBoxPlayerRequestDataModel * _Nullable))errorHandler networkFailHandler:(void (^ _Nonnull)(NSError * _Nonnull))networkFailHandler;
+ (void)requestNoteListWithClassroomId:(NSString * _Nonnull)classroomId token:(NSString * _Nonnull)token completionHandler:(void (^ _Nonnull)(RoomBoxPlayerRequestDataModel * _Nullable))completionHandler errorHandler:(void (^ _Nonnull)(RoomBoxPlayerRequestDataModel * _Nullable))errorHandler networkFailHandler:(void (^ _Nonnull)(NSError * _Nonnull))networkFailHandler;
+ (void)requestRecordNoteListWithClassroomId:(NSString * _Nonnull)classroomId token:(NSString * _Nonnull)token completionHandler:(void (^ _Nonnull)(RoomBoxPlayerRequestDataModel * _Nullable))completionHandler errorHandler:(void (^ _Nonnull)(RoomBoxPlayerRequestDataModel * _Nullable))errorHandler networkFailHandler:(void (^ _Nonnull)(NSError * _Nonnull))networkFailHandler;
+ (void)requestChatHistoryWithCid:(NSString * _Nonnull)cid page:(NSInteger)page pageSize:(NSInteger)pageSize token:(NSString * _Nonnull)token completionHandler:(void (^ _Nonnull)(RoomBoxPlayerRequestDataModel * _Nullable))completionHandler errorHandler:(void (^ _Nonnull)(RoomBoxPlayerRequestDataModel * _Nullable))errorHandler networkFailHandler:(void (^ _Nonnull)(NSError * _Nonnull))networkFailHandler;
+ (void)requestRecordHistoryWithCid:(NSString * _Nonnull)cid token:(NSString * _Nonnull)token completionHandler:(void (^ _Nonnull)(RoomBoxPlayerRequestDataModel * _Nullable))completionHandler errorHandler:(void (^ _Nonnull)(RoomBoxPlayerRequestDataModel * _Nullable))errorHandler networkFailHandler:(void (^ _Nonnull)(NSError * _Nonnull))networkFailHandler;
+ (void)requestVideoConfigWithCid:(NSString * _Nonnull)cid token:(NSString * _Nonnull)token completionHandler:(void (^ _Nonnull)(RoomBoxPlayerRequestDataModel * _Nullable))completionHandler errorHandler:(void (^ _Nonnull)(RoomBoxPlayerRequestDataModel * _Nullable))errorHandler networkFailHandler:(void (^ _Nonnull)(NSError * _Nonnull))networkFailHandler;
+ (void)requestAddStarWithCid:(NSString * _Nonnull)cid token:(NSString * _Nonnull)token playTime:(NSString * _Nonnull)playTime completionHandler:(void (^ _Nonnull)(RoomBoxPlayerRequestDataModel * _Nullable))completionHandler errorHandler:(void (^ _Nonnull)(RoomBoxPlayerRequestDataModel * _Nullable))errorHandler networkFailHandler:(void (^ _Nonnull)(NSError * _Nonnull))networkFailHandler;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSBundle;

SWIFT_CLASS("_TtC15RoomBoxPlayback30RoomBoxPlayerSacQuizController")
@interface RoomBoxPlayerSacQuizController : RBBaseViewController
@property (nonatomic, copy) void (^ _Nullable closeClosure)(void);
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface RoomBoxPlayerSacQuizController (SWIFT_EXTENSION(RoomBoxPlayback)) <RBRotateProtocol>
- (BOOL)rbShouldAutorotate SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) UIInterfaceOrientationMask supportedInterfaceOrientations;
@end


@interface RoomBoxPlayerSacQuizController (SWIFT_EXTENSION(RoomBoxPlayback))
- (void)showOnView:(UIView * _Nonnull)onView urlString:(NSString * _Nonnull)urlString param:(NSDictionary<NSString *, NSString *> * _Nullable)param;
@end


SWIFT_CLASS("_TtC15RoomBoxPlayback32RoomBoxRecordKnowledgeCloseAlert")
@interface RoomBoxRecordKnowledgeCloseAlert : UIView
@property (nonatomic, copy) void (^ _Nullable closeClosure)(void);
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
@end



@interface RoomBoxRecordKnowledgeCloseAlert (SWIFT_EXTENSION(RoomBoxPlayback))
- (void)hiddenCancleBtn;
@end


SWIFT_CLASS("_TtC15RoomBoxPlayback32RoomBoxRecordKnowledgeController")
@interface RoomBoxRecordKnowledgeController : RBBaseViewController
@property (nonatomic, copy) void (^ _Nullable closeClosure)(void);
- (void)configWebUrlWithUrlString:(NSString * _Nonnull)urlString param:(NSDictionary<NSString *, NSString *> * _Nullable)param;
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#endif
