#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)
#ifndef ROOMBOXCONFIGMANAGER_SWIFT_H
#define ROOMBOXCONFIGMANAGER_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import ObjectiveC;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="RoomBoxConfigManager",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

enum RoomBoxDevEnvironment : NSInteger;

SWIFT_CLASS("_TtC20RoomBoxConfigManager7RoomBox")
@interface RoomBox : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nullable appId;)
+ (NSString * _Nullable)appId SWIFT_WARN_UNUSED_RESULT;
+ (void)setAppId:(NSString * _Nullable)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nullable secretKey;)
+ (NSString * _Nullable)secretKey SWIFT_WARN_UNUSED_RESULT;
+ (void)setSecretKey:(NSString * _Nullable)value;
/// @return sdk当前的版本号
+ (NSString * _Nonnull)currentVersion SWIFT_WARN_UNUSED_RESULT;
+ (void)startWithAppId:(NSString * _Nonnull)appId secretKey:(NSString * _Nonnull)secretKey;
+ (void)setDebugMode:(BOOL)isDebug;
+ (BOOL)isDebugMode SWIFT_WARN_UNUSED_RESULT;
+ (void)setDevEnvironment:(enum RoomBoxDevEnvironment)environment;
+ (enum RoomBoxDevEnvironment)getDevEnvironment SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface RoomBox (SWIFT_EXTENSION(RoomBoxConfigManager))
+ (void)isAuthWithCompletion:(void (^ _Nonnull)(BOOL, NSError * _Nullable))completion;
@end


SWIFT_CLASS("_TtC20RoomBoxConfigManager16RoomBoxApiConfig")
@interface RoomBoxApiConfig : NSObject
+ (NSString * _Nonnull)getHttpHostUrl SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getH5HostUrl SWIFT_WARN_UNUSED_RESULT;
+ (NSArray<NSString *> * _Nonnull)getSvcHostUrls SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getCosHostUrl SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getDataUrl SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getWhiteBoardUrl SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getIMUrl SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getH5SSUrl SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC20RoomBoxConfigManager20RoomBoxConfigManager")
@interface RoomBoxConfigManager : NSObject
+ (void)setPersonalOrgAccountCharge:(BOOL)personalOrgAccountCharge;
+ (BOOL)getPersonalOrgAccountCharge SWIFT_WARN_UNUSED_RESULT;
+ (void)setPersonalOrgCertify:(BOOL)personalOrgCertify;
+ (BOOL)getPersonalOrgCertify SWIFT_WARN_UNUSED_RESULT;
+ (void)setQuickLive:(BOOL)quickLive;
+ (BOOL)getQuickLive SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)isDebug SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)isDebugMode SWIFT_WARN_UNUSED_RESULT;
+ (void)setOrganizationId:(NSString * _Nonnull)org;
+ (NSString * _Nonnull)getOrganizationId SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nullable)getClientData SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, RoomBoxDevEnvironment, open) {
  RoomBoxDevEnvironmentRelease = 1,
  RoomBoxDevEnvironmentBeta = 2,
  RoomBoxDevEnvironmentDev = 3,
  RoomBoxDevEnvironmentTest = 4,
  RoomBoxDevEnvironmentTest2 = 5,
  RoomBoxDevEnvironmentTest3 = 6,
  RoomBoxDevEnvironmentCustom = 7,
};


SWIFT_CLASS("_TtC20RoomBoxConfigManager17RoomBoxFuncConfig")
@interface RoomBoxFuncConfig : NSObject
+ (BOOL)atauthEnable SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)faceBeautyEnable SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)addressEnable SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)myStarEnable SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)airPlayEnable SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)profileEnable SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)findPasswordEnable SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)emergencyClassRoomEnable SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC20RoomBoxConfigManager19RoomBoxLiveCommerce")
@interface RoomBoxLiveCommerce : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nullable appId;)
+ (NSString * _Nullable)appId SWIFT_WARN_UNUSED_RESULT;
+ (void)setAppId:(NSString * _Nullable)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nullable secretKey;)
+ (NSString * _Nullable)secretKey SWIFT_WARN_UNUSED_RESULT;
+ (void)setSecretKey:(NSString * _Nullable)value;
/// @return sdk当前的版本号
+ (NSString * _Nonnull)currentVersion SWIFT_WARN_UNUSED_RESULT;
+ (void)startWithAppId:(NSString * _Nonnull)appId secretKey:(NSString * _Nonnull)secretKey;
+ (void)setDebugMode:(BOOL)isDebug;
+ (BOOL)isDebugMode SWIFT_WARN_UNUSED_RESULT;
+ (void)setDevEnvironment:(enum RoomBoxDevEnvironment)environment;
+ (enum RoomBoxDevEnvironment)getDevEnvironment SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface RoomBoxLiveCommerce (SWIFT_EXTENSION(RoomBoxConfigManager))
+ (void)isAuthWithCompletion:(void (^ _Nonnull)(BOOL, NSError * _Nullable))completion;
@end


SWIFT_CLASS("_TtC20RoomBoxConfigManager17RoomBoxLiveConfig")
@interface RoomBoxLiveConfig : NSObject
+ (void)setAgoraId:(NSString * _Nonnull)agoraId;
+ (NSString * _Nullable)getAgoraId SWIFT_WARN_UNUSED_RESULT;
+ (void)setXdfRtcId:(NSString * _Nonnull)xdfRtcId;
+ (NSString * _Nullable)getXdfRtcId SWIFT_WARN_UNUSED_RESULT;
+ (void)setQuanShiId:(NSString * _Nonnull)QuanshiId;
+ (NSString * _Nullable)getQuanShiId SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC20RoomBoxConfigManager16RoomBoxLogConfig")
@interface RoomBoxLogConfig : NSObject
+ (NSString * _Nonnull)getGoldenEyeProject SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getLogProject SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC20RoomBoxConfigManager17RoomBoxTextConfig")
@interface RoomBoxTextConfig : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull copyrightInfo;)
+ (NSString * _Nonnull)copyrightInfo SWIFT_WARN_UNUSED_RESULT;
+ (void)setCopyrightInfo:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull roomBoxProgressUnStart;)
+ (NSString * _Nonnull)roomBoxProgressUnStart SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull roomBoxProgressStart;)
+ (NSString * _Nonnull)roomBoxProgressStart SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull roomBoxProgressFinished;)
+ (NSString * _Nonnull)roomBoxProgressFinished SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull roomBoxMemberListTitle;)
+ (NSString * _Nonnull)roomBoxMemberListTitle SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull userPrivacyText;)
+ (NSString * _Nonnull)userPrivacyText SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface RoomBoxTextConfig (SWIFT_EXTENSION(RoomBoxConfigManager))
+ (NSString * _Nonnull)getCopyrightTest SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC20RoomBoxConfigManager21RoomBoxThirdSDKConfig")
@interface RoomBoxThirdSDKConfig : NSObject
+ (NSString * _Nonnull)getGrowingIOInfo SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getTingyunInfo SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getBonreeInfo SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getLeBoAppId SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getLeBoAppSec SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getATAuthInfo SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__ARM_ARCH_7A__) && __ARM_ARCH_7A__
// Generated by Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)
#ifndef ROOMBOXCONFIGMANAGER_SWIFT_H
#define ROOMBOXCONFIGMANAGER_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import ObjectiveC;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="RoomBoxConfigManager",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

enum RoomBoxDevEnvironment : NSInteger;

SWIFT_CLASS("_TtC20RoomBoxConfigManager7RoomBox")
@interface RoomBox : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nullable appId;)
+ (NSString * _Nullable)appId SWIFT_WARN_UNUSED_RESULT;
+ (void)setAppId:(NSString * _Nullable)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nullable secretKey;)
+ (NSString * _Nullable)secretKey SWIFT_WARN_UNUSED_RESULT;
+ (void)setSecretKey:(NSString * _Nullable)value;
/// @return sdk当前的版本号
+ (NSString * _Nonnull)currentVersion SWIFT_WARN_UNUSED_RESULT;
+ (void)startWithAppId:(NSString * _Nonnull)appId secretKey:(NSString * _Nonnull)secretKey;
+ (void)setDebugMode:(BOOL)isDebug;
+ (BOOL)isDebugMode SWIFT_WARN_UNUSED_RESULT;
+ (void)setDevEnvironment:(enum RoomBoxDevEnvironment)environment;
+ (enum RoomBoxDevEnvironment)getDevEnvironment SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface RoomBox (SWIFT_EXTENSION(RoomBoxConfigManager))
+ (void)isAuthWithCompletion:(void (^ _Nonnull)(BOOL, NSError * _Nullable))completion;
@end


SWIFT_CLASS("_TtC20RoomBoxConfigManager16RoomBoxApiConfig")
@interface RoomBoxApiConfig : NSObject
+ (NSString * _Nonnull)getHttpHostUrl SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getH5HostUrl SWIFT_WARN_UNUSED_RESULT;
+ (NSArray<NSString *> * _Nonnull)getSvcHostUrls SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getCosHostUrl SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getDataUrl SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getWhiteBoardUrl SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getIMUrl SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getH5SSUrl SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC20RoomBoxConfigManager20RoomBoxConfigManager")
@interface RoomBoxConfigManager : NSObject
+ (void)setPersonalOrgAccountCharge:(BOOL)personalOrgAccountCharge;
+ (BOOL)getPersonalOrgAccountCharge SWIFT_WARN_UNUSED_RESULT;
+ (void)setPersonalOrgCertify:(BOOL)personalOrgCertify;
+ (BOOL)getPersonalOrgCertify SWIFT_WARN_UNUSED_RESULT;
+ (void)setQuickLive:(BOOL)quickLive;
+ (BOOL)getQuickLive SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)isDebug SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)isDebugMode SWIFT_WARN_UNUSED_RESULT;
+ (void)setOrganizationId:(NSString * _Nonnull)org;
+ (NSString * _Nonnull)getOrganizationId SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nullable)getClientData SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, RoomBoxDevEnvironment, open) {
  RoomBoxDevEnvironmentRelease = 1,
  RoomBoxDevEnvironmentBeta = 2,
  RoomBoxDevEnvironmentDev = 3,
  RoomBoxDevEnvironmentTest = 4,
  RoomBoxDevEnvironmentTest2 = 5,
  RoomBoxDevEnvironmentTest3 = 6,
  RoomBoxDevEnvironmentCustom = 7,
};


SWIFT_CLASS("_TtC20RoomBoxConfigManager17RoomBoxFuncConfig")
@interface RoomBoxFuncConfig : NSObject
+ (BOOL)atauthEnable SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)faceBeautyEnable SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)addressEnable SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)myStarEnable SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)airPlayEnable SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)profileEnable SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)findPasswordEnable SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)emergencyClassRoomEnable SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC20RoomBoxConfigManager19RoomBoxLiveCommerce")
@interface RoomBoxLiveCommerce : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nullable appId;)
+ (NSString * _Nullable)appId SWIFT_WARN_UNUSED_RESULT;
+ (void)setAppId:(NSString * _Nullable)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nullable secretKey;)
+ (NSString * _Nullable)secretKey SWIFT_WARN_UNUSED_RESULT;
+ (void)setSecretKey:(NSString * _Nullable)value;
/// @return sdk当前的版本号
+ (NSString * _Nonnull)currentVersion SWIFT_WARN_UNUSED_RESULT;
+ (void)startWithAppId:(NSString * _Nonnull)appId secretKey:(NSString * _Nonnull)secretKey;
+ (void)setDebugMode:(BOOL)isDebug;
+ (BOOL)isDebugMode SWIFT_WARN_UNUSED_RESULT;
+ (void)setDevEnvironment:(enum RoomBoxDevEnvironment)environment;
+ (enum RoomBoxDevEnvironment)getDevEnvironment SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface RoomBoxLiveCommerce (SWIFT_EXTENSION(RoomBoxConfigManager))
+ (void)isAuthWithCompletion:(void (^ _Nonnull)(BOOL, NSError * _Nullable))completion;
@end


SWIFT_CLASS("_TtC20RoomBoxConfigManager17RoomBoxLiveConfig")
@interface RoomBoxLiveConfig : NSObject
+ (void)setAgoraId:(NSString * _Nonnull)agoraId;
+ (NSString * _Nullable)getAgoraId SWIFT_WARN_UNUSED_RESULT;
+ (void)setXdfRtcId:(NSString * _Nonnull)xdfRtcId;
+ (NSString * _Nullable)getXdfRtcId SWIFT_WARN_UNUSED_RESULT;
+ (void)setQuanShiId:(NSString * _Nonnull)QuanshiId;
+ (NSString * _Nullable)getQuanShiId SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC20RoomBoxConfigManager16RoomBoxLogConfig")
@interface RoomBoxLogConfig : NSObject
+ (NSString * _Nonnull)getGoldenEyeProject SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getLogProject SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC20RoomBoxConfigManager17RoomBoxTextConfig")
@interface RoomBoxTextConfig : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull copyrightInfo;)
+ (NSString * _Nonnull)copyrightInfo SWIFT_WARN_UNUSED_RESULT;
+ (void)setCopyrightInfo:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull roomBoxProgressUnStart;)
+ (NSString * _Nonnull)roomBoxProgressUnStart SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull roomBoxProgressStart;)
+ (NSString * _Nonnull)roomBoxProgressStart SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull roomBoxProgressFinished;)
+ (NSString * _Nonnull)roomBoxProgressFinished SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull roomBoxMemberListTitle;)
+ (NSString * _Nonnull)roomBoxMemberListTitle SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull userPrivacyText;)
+ (NSString * _Nonnull)userPrivacyText SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface RoomBoxTextConfig (SWIFT_EXTENSION(RoomBoxConfigManager))
+ (NSString * _Nonnull)getCopyrightTest SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC20RoomBoxConfigManager21RoomBoxThirdSDKConfig")
@interface RoomBoxThirdSDKConfig : NSObject
+ (NSString * _Nonnull)getGrowingIOInfo SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getTingyunInfo SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getBonreeInfo SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getLeBoAppId SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getLeBoAppSec SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getATAuthInfo SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#endif
