// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: class.v1.tcp.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class ClassV1DefinitionsActiveInfo;
@class ClassV1DefinitionsActiveQuery;
@class ClassV1DefinitionsClassActiveInfo;
@class ClassV1DefinitionsClassCusData;
@class ClassV1DefinitionsClassGrades;
@class ClassV1DefinitionsClassId;
@class ClassV1DefinitionsClassInfoWithActive;
@class ClassV1DefinitionsClassInfoWithOnline;
@class ClassV1DefinitionsClassNumKvAdd;
@class ClassV1DefinitionsClassSimpleWithActive;
@class ClassV1DefinitionsClassStatic;
@class ClassV1DefinitionsClassStaticKvs;
@class ClassV1DefinitionsClassStudentsNumbers;
@class ClassV1DefinitionsClassTimeAt;
@class ClassV1DefinitionsClassVersionPageQuery;
@class ClassV1DefinitionsCommonSetUpdate;
@class ClassV1DefinitionsCommonSetUpdateReply;
@class ClassV1DefinitionsEnterInfo;
@class ClassV1DefinitionsExitInfo;
@class ClassV1DefinitionsModeUpdate;
@class ClassV1DefinitionsMsgDel;
@class ClassV1DefinitionsRosterQuery;
@class ClassV1DefinitionsRosters;
@class ClassV1DefinitionsSkin;
@class ClassV1DefinitionsStatusDeviceUpdate;
@class ClassV1DefinitionsStatusStaticUpdate;
@class ClassV1DefinitionsStudentQuery;
@class ClassV1DefinitionsStudentQueryInfo;
@class ClassV1DefinitionsStudentRandomQuery;
@class ClassV1DefinitionsStudentStatics;
@class ClassV1DefinitionsStudents;
@class ClassV1DefinitionsStudentsNumber;
@class ClassV1DefinitionsStudentsSetUpdate;
@class ClassV1DefinitionsTeacherSimple;
@class ClassV1DefinitionsUserActiveInfo;
@class ClassV1DefinitionsUserInfo;
@class ClassV1DefinitionsUserStatusUpdate;
@class ClassV1DefinitionsVersionManagers;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - ClassV1TcpRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface ClassV1TcpRoot : GPBRootObject
@end

#pragma mark - ClassV1PostActiveRequest

typedef GPB_ENUM(ClassV1PostActiveRequest_FieldNumber) {
  ClassV1PostActiveRequest_FieldNumber_Body = 1,
};

@interface ClassV1PostActiveRequest : GPBMessage

/** 教室动态信息请求 */
@property(nonatomic, readwrite, strong, null_resettable) ClassV1DefinitionsActiveQuery *body;
/** Test to see if @c body has been set. */
@property(nonatomic, readwrite) BOOL hasBody;

@end

#pragma mark - ClassV1PostCommonSetUpdateRequest

typedef GPB_ENUM(ClassV1PostCommonSetUpdateRequest_FieldNumber) {
  ClassV1PostCommonSetUpdateRequest_FieldNumber_Body = 1,
};

@interface ClassV1PostCommonSetUpdateRequest : GPBMessage

/** 更新教室权限 */
@property(nonatomic, readwrite, strong, null_resettable) ClassV1DefinitionsCommonSetUpdate *body;
/** Test to see if @c body has been set. */
@property(nonatomic, readwrite) BOOL hasBody;

@end

#pragma mark - ClassV1PostEnterRequest

typedef GPB_ENUM(ClassV1PostEnterRequest_FieldNumber) {
  ClassV1PostEnterRequest_FieldNumber_Body = 1,
};

@interface ClassV1PostEnterRequest : GPBMessage

/** 进入教室传入参数 */
@property(nonatomic, readwrite, strong, null_resettable) ClassV1DefinitionsClassCusData *body;
/** Test to see if @c body has been set. */
@property(nonatomic, readwrite) BOOL hasBody;

@end

#pragma mark - ClassV1PostExitRequest

typedef GPB_ENUM(ClassV1PostExitRequest_FieldNumber) {
  ClassV1PostExitRequest_FieldNumber_Body = 1,
};

@interface ClassV1PostExitRequest : GPBMessage

/** 离开教室传入参数 */
@property(nonatomic, readwrite, strong, null_resettable) ClassV1DefinitionsClassId *body;
/** Test to see if @c body has been set. */
@property(nonatomic, readwrite) BOOL hasBody;

@end

#pragma mark - ClassV1PostGradesRequest

typedef GPB_ENUM(ClassV1PostGradesRequest_FieldNumber) {
  ClassV1PostGradesRequest_FieldNumber_Body = 1,
};

@interface ClassV1PostGradesRequest : GPBMessage

/** 获取教室信息 */
@property(nonatomic, readwrite, strong, null_resettable) ClassV1DefinitionsClassVersionPageQuery *body;
/** Test to see if @c body has been set. */
@property(nonatomic, readwrite) BOOL hasBody;

@end

#pragma mark - ClassV1PostInfoRequest

typedef GPB_ENUM(ClassV1PostInfoRequest_FieldNumber) {
  ClassV1PostInfoRequest_FieldNumber_Body = 1,
};

@interface ClassV1PostInfoRequest : GPBMessage

/** 获取教室信息 */
@property(nonatomic, readwrite, strong, null_resettable) ClassV1DefinitionsClassId *body;
/** Test to see if @c body has been set. */
@property(nonatomic, readwrite) BOOL hasBody;

@end

#pragma mark - ClassV1PostModeUpdateRequest

typedef GPB_ENUM(ClassV1PostModeUpdateRequest_FieldNumber) {
  ClassV1PostModeUpdateRequest_FieldNumber_Body = 1,
};

@interface ClassV1PostModeUpdateRequest : GPBMessage

/** 更新教室模式 */
@property(nonatomic, readwrite, strong, null_resettable) ClassV1DefinitionsModeUpdate *body;
/** Test to see if @c body has been set. */
@property(nonatomic, readwrite) BOOL hasBody;

@end

#pragma mark - ClassV1PostMsgDelRequest

typedef GPB_ENUM(ClassV1PostMsgDelRequest_FieldNumber) {
  ClassV1PostMsgDelRequest_FieldNumber_Body = 1,
};

@interface ClassV1PostMsgDelRequest : GPBMessage

/** 消息删除 */
@property(nonatomic, readwrite, strong, null_resettable) ClassV1DefinitionsMsgDel *body;
/** Test to see if @c body has been set. */
@property(nonatomic, readwrite) BOOL hasBody;

@end

#pragma mark - ClassV1PostPanelModeUpdateRequest

typedef GPB_ENUM(ClassV1PostPanelModeUpdateRequest_FieldNumber) {
  ClassV1PostPanelModeUpdateRequest_FieldNumber_Body = 1,
};

@interface ClassV1PostPanelModeUpdateRequest : GPBMessage

/** 更新教室面板模式 */
@property(nonatomic, readwrite, strong, null_resettable) ClassV1DefinitionsModeUpdate *body;
/** Test to see if @c body has been set. */
@property(nonatomic, readwrite) BOOL hasBody;

@end

#pragma mark - ClassV1PostRecorderModeUpdateRequest

typedef GPB_ENUM(ClassV1PostRecorderModeUpdateRequest_FieldNumber) {
  ClassV1PostRecorderModeUpdateRequest_FieldNumber_Body = 1,
};

@interface ClassV1PostRecorderModeUpdateRequest : GPBMessage

/** 更新（上课时）教室录播播放模式 */
@property(nonatomic, readwrite, strong, null_resettable) ClassV1DefinitionsModeUpdate *body;
/** Test to see if @c body has been set. */
@property(nonatomic, readwrite) BOOL hasBody;

@end

#pragma mark - ClassV1PostRostersRequest

typedef GPB_ENUM(ClassV1PostRostersRequest_FieldNumber) {
  ClassV1PostRostersRequest_FieldNumber_Body = 1,
};

@interface ClassV1PostRostersRequest : GPBMessage

/** 教室花名册获取 */
@property(nonatomic, readwrite, strong, null_resettable) ClassV1DefinitionsRosterQuery *body;
/** Test to see if @c body has been set. */
@property(nonatomic, readwrite) BOOL hasBody;

@end

#pragma mark - ClassV1PostStaticUpdateRequest

typedef GPB_ENUM(ClassV1PostStaticUpdateRequest_FieldNumber) {
  ClassV1PostStaticUpdateRequest_FieldNumber_Body = 1,
};

@interface ClassV1PostStaticUpdateRequest : GPBMessage

/** 教室统计上报 */
@property(nonatomic, readwrite, strong, null_resettable) ClassV1DefinitionsClassNumKvAdd *body;
/** Test to see if @c body has been set. */
@property(nonatomic, readwrite) BOOL hasBody;

@end

#pragma mark - ClassV1PostStudentsDeviceStatusRequest

typedef GPB_ENUM(ClassV1PostStudentsDeviceStatusRequest_FieldNumber) {
  ClassV1PostStudentsDeviceStatusRequest_FieldNumber_Body = 1,
};

@interface ClassV1PostStudentsDeviceStatusRequest : GPBMessage

/** 教室设备感知 */
@property(nonatomic, readwrite, strong, null_resettable) ClassV1DefinitionsStatusDeviceUpdate *body;
/** Test to see if @c body has been set. */
@property(nonatomic, readwrite) BOOL hasBody;

@end

#pragma mark - ClassV1PostStudentsInfosRequest

typedef GPB_ENUM(ClassV1PostStudentsInfosRequest_FieldNumber) {
  ClassV1PostStudentsInfosRequest_FieldNumber_Body = 1,
};

@interface ClassV1PostStudentsInfosRequest : GPBMessage

/** 批量获取学员信息 */
@property(nonatomic, readwrite, strong, null_resettable) ClassV1DefinitionsStudentQuery *body;
/** Test to see if @c body has been set. */
@property(nonatomic, readwrite) BOOL hasBody;

@end

#pragma mark - ClassV1PostStudentsNumbersRequest

typedef GPB_ENUM(ClassV1PostStudentsNumbersRequest_FieldNumber) {
  ClassV1PostStudentsNumbersRequest_FieldNumber_Body = 1,
};

@interface ClassV1PostStudentsNumbersRequest : GPBMessage

/** 学生数量，获取所有子班的学生数量 */
@property(nonatomic, readwrite, strong, null_resettable) ClassV1DefinitionsClassId *body;
/** Test to see if @c body has been set. */
@property(nonatomic, readwrite) BOOL hasBody;

@end

#pragma mark - ClassV1PostStudentsRandomRequest

typedef GPB_ENUM(ClassV1PostStudentsRandomRequest_FieldNumber) {
  ClassV1PostStudentsRandomRequest_FieldNumber_Body = 1,
};

@interface ClassV1PostStudentsRandomRequest : GPBMessage

/** 随机获取学生 */
@property(nonatomic, readwrite, strong, null_resettable) ClassV1DefinitionsStudentRandomQuery *body;
/** Test to see if @c body has been set. */
@property(nonatomic, readwrite) BOOL hasBody;

@end

#pragma mark - ClassV1PostStudentsRequest

typedef GPB_ENUM(ClassV1PostStudentsRequest_FieldNumber) {
  ClassV1PostStudentsRequest_FieldNumber_Body = 1,
};

@interface ClassV1PostStudentsRequest : GPBMessage

/** 教室学员列表获取 */
@property(nonatomic, readwrite, strong, null_resettable) ClassV1DefinitionsClassVersionPageQuery *body;
/** Test to see if @c body has been set. */
@property(nonatomic, readwrite) BOOL hasBody;

@end

#pragma mark - ClassV1PostStudentsStaticUpdateRequest

typedef GPB_ENUM(ClassV1PostStudentsStaticUpdateRequest_FieldNumber) {
  ClassV1PostStudentsStaticUpdateRequest_FieldNumber_Body = 1,
};

@interface ClassV1PostStudentsStaticUpdateRequest : GPBMessage

/** 教室统计信息更新 */
@property(nonatomic, readwrite, strong, null_resettable) ClassV1DefinitionsStatusStaticUpdate *body;
/** Test to see if @c body has been set. */
@property(nonatomic, readwrite) BOOL hasBody;

@end

#pragma mark - ClassV1PostUserInfoRequest

typedef GPB_ENUM(ClassV1PostUserInfoRequest_FieldNumber) {
  ClassV1PostUserInfoRequest_FieldNumber_Body = 1,
};

@interface ClassV1PostUserInfoRequest : GPBMessage

/** 获取用户信息 */
@property(nonatomic, readwrite, strong, null_resettable) ClassV1DefinitionsClassId *body;
/** Test to see if @c body has been set. */
@property(nonatomic, readwrite) BOOL hasBody;

@end

#pragma mark - ClassV1PostUsersRightUpdateRequest

typedef GPB_ENUM(ClassV1PostUsersRightUpdateRequest_FieldNumber) {
  ClassV1PostUsersRightUpdateRequest_FieldNumber_Body = 1,
};

@interface ClassV1PostUsersRightUpdateRequest : GPBMessage

/** 教室学员学员权限更新 */
@property(nonatomic, readwrite, strong, null_resettable) ClassV1DefinitionsStudentsSetUpdate *body;
/** Test to see if @c body has been set. */
@property(nonatomic, readwrite) BOOL hasBody;

@end

#pragma mark - ClassV1PostUsersStatusUpdateRequest

typedef GPB_ENUM(ClassV1PostUsersStatusUpdateRequest_FieldNumber) {
  ClassV1PostUsersStatusUpdateRequest_FieldNumber_Body = 1,
};

@interface ClassV1PostUsersStatusUpdateRequest : GPBMessage

/** 用户状态更新 */
@property(nonatomic, readwrite, strong, null_resettable) ClassV1DefinitionsUserStatusUpdate *body;
/** Test to see if @c body has been set. */
@property(nonatomic, readwrite) BOOL hasBody;

@end

#pragma mark - ClassV1PostUsersSwitchUpdateRequest

typedef GPB_ENUM(ClassV1PostUsersSwitchUpdateRequest_FieldNumber) {
  ClassV1PostUsersSwitchUpdateRequest_FieldNumber_Body = 1,
};

@interface ClassV1PostUsersSwitchUpdateRequest : GPBMessage

/** 教室学员开关更新 */
@property(nonatomic, readwrite, strong, null_resettable) ClassV1DefinitionsStudentsSetUpdate *body;
/** Test to see if @c body has been set. */
@property(nonatomic, readwrite) BOOL hasBody;

@end

#pragma mark - ClassV1PostVersionsManagersRequest

typedef GPB_ENUM(ClassV1PostVersionsManagersRequest_FieldNumber) {
  ClassV1PostVersionsManagersRequest_FieldNumber_Body = 1,
};

@interface ClassV1PostVersionsManagersRequest : GPBMessage

/** 班级版本管理 */
@property(nonatomic, readwrite, strong, null_resettable) ClassV1DefinitionsClassId *body;
/** Test to see if @c body has been set. */
@property(nonatomic, readwrite) BOOL hasBody;

@end

#pragma mark - ClassV1PostActiveReply

typedef GPB_ENUM(ClassV1PostActiveReply_FieldNumber) {
  ClassV1PostActiveReply_FieldNumber_HTTPCode = 1,
  ClassV1PostActiveReply_FieldNumber_ErrCode = 2,
  ClassV1PostActiveReply_FieldNumber_ErrMsg = 3,
  ClassV1PostActiveReply_FieldNumber_Data_p = 15,
};

@interface ClassV1PostActiveReply : GPBMessage

@property(nonatomic, readwrite) uint32_t HTTPCode;

@property(nonatomic, readwrite) uint32_t errCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errMsg;

@property(nonatomic, readwrite, strong, null_resettable) ClassV1DefinitionsActiveInfo *data_p;
/** Test to see if @c data_p has been set. */
@property(nonatomic, readwrite) BOOL hasData_p;

@end

#pragma mark - ClassV1PostCommonSetUpdateReply

typedef GPB_ENUM(ClassV1PostCommonSetUpdateReply_FieldNumber) {
  ClassV1PostCommonSetUpdateReply_FieldNumber_HTTPCode = 1,
  ClassV1PostCommonSetUpdateReply_FieldNumber_ErrCode = 2,
  ClassV1PostCommonSetUpdateReply_FieldNumber_ErrMsg = 3,
  ClassV1PostCommonSetUpdateReply_FieldNumber_Data_p = 15,
};

@interface ClassV1PostCommonSetUpdateReply : GPBMessage

@property(nonatomic, readwrite) uint32_t HTTPCode;

@property(nonatomic, readwrite) uint32_t errCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errMsg;

@property(nonatomic, readwrite, strong, null_resettable) ClassV1DefinitionsCommonSetUpdateReply *data_p;
/** Test to see if @c data_p has been set. */
@property(nonatomic, readwrite) BOOL hasData_p;

@end

#pragma mark - ClassV1PostEnterReply

typedef GPB_ENUM(ClassV1PostEnterReply_FieldNumber) {
  ClassV1PostEnterReply_FieldNumber_HTTPCode = 1,
  ClassV1PostEnterReply_FieldNumber_ErrCode = 2,
  ClassV1PostEnterReply_FieldNumber_ErrMsg = 3,
  ClassV1PostEnterReply_FieldNumber_Data_p = 15,
};

@interface ClassV1PostEnterReply : GPBMessage

@property(nonatomic, readwrite) uint32_t HTTPCode;

@property(nonatomic, readwrite) uint32_t errCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errMsg;

@property(nonatomic, readwrite, strong, null_resettable) ClassV1DefinitionsEnterInfo *data_p;
/** Test to see if @c data_p has been set. */
@property(nonatomic, readwrite) BOOL hasData_p;

@end

#pragma mark - ClassV1PostExitReply

typedef GPB_ENUM(ClassV1PostExitReply_FieldNumber) {
  ClassV1PostExitReply_FieldNumber_HTTPCode = 1,
  ClassV1PostExitReply_FieldNumber_ErrCode = 2,
  ClassV1PostExitReply_FieldNumber_ErrMsg = 3,
  ClassV1PostExitReply_FieldNumber_Data_p = 15,
};

@interface ClassV1PostExitReply : GPBMessage

@property(nonatomic, readwrite) uint32_t HTTPCode;

@property(nonatomic, readwrite) uint32_t errCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errMsg;

@property(nonatomic, readwrite, strong, null_resettable) ClassV1DefinitionsExitInfo *data_p;
/** Test to see if @c data_p has been set. */
@property(nonatomic, readwrite) BOOL hasData_p;

@end

#pragma mark - ClassV1PostGradesReply

typedef GPB_ENUM(ClassV1PostGradesReply_FieldNumber) {
  ClassV1PostGradesReply_FieldNumber_HTTPCode = 1,
  ClassV1PostGradesReply_FieldNumber_ErrCode = 2,
  ClassV1PostGradesReply_FieldNumber_ErrMsg = 3,
  ClassV1PostGradesReply_FieldNumber_Data_p = 15,
};

@interface ClassV1PostGradesReply : GPBMessage

@property(nonatomic, readwrite) uint32_t HTTPCode;

@property(nonatomic, readwrite) uint32_t errCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errMsg;

@property(nonatomic, readwrite, strong, null_resettable) ClassV1DefinitionsClassGrades *data_p;
/** Test to see if @c data_p has been set. */
@property(nonatomic, readwrite) BOOL hasData_p;

@end

#pragma mark - ClassV1PostInfoReply

typedef GPB_ENUM(ClassV1PostInfoReply_FieldNumber) {
  ClassV1PostInfoReply_FieldNumber_HTTPCode = 1,
  ClassV1PostInfoReply_FieldNumber_ErrCode = 2,
  ClassV1PostInfoReply_FieldNumber_ErrMsg = 3,
  ClassV1PostInfoReply_FieldNumber_Data_p = 15,
};

@interface ClassV1PostInfoReply : GPBMessage

@property(nonatomic, readwrite) uint32_t HTTPCode;

@property(nonatomic, readwrite) uint32_t errCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errMsg;

@property(nonatomic, readwrite, strong, null_resettable) ClassV1DefinitionsClassInfoWithActive *data_p;
/** Test to see if @c data_p has been set. */
@property(nonatomic, readwrite) BOOL hasData_p;

@end

#pragma mark - ClassV1PostModeUpdateReply

typedef GPB_ENUM(ClassV1PostModeUpdateReply_FieldNumber) {
  ClassV1PostModeUpdateReply_FieldNumber_HTTPCode = 1,
  ClassV1PostModeUpdateReply_FieldNumber_ErrCode = 2,
  ClassV1PostModeUpdateReply_FieldNumber_ErrMsg = 3,
};

@interface ClassV1PostModeUpdateReply : GPBMessage

@property(nonatomic, readwrite) uint32_t HTTPCode;

@property(nonatomic, readwrite) uint32_t errCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errMsg;

@end

#pragma mark - ClassV1PostMsgDelReply

typedef GPB_ENUM(ClassV1PostMsgDelReply_FieldNumber) {
  ClassV1PostMsgDelReply_FieldNumber_HTTPCode = 1,
  ClassV1PostMsgDelReply_FieldNumber_ErrCode = 2,
  ClassV1PostMsgDelReply_FieldNumber_ErrMsg = 3,
};

@interface ClassV1PostMsgDelReply : GPBMessage

@property(nonatomic, readwrite) uint32_t HTTPCode;

@property(nonatomic, readwrite) uint32_t errCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errMsg;

@end

#pragma mark - ClassV1PostPanelModeUpdateReply

typedef GPB_ENUM(ClassV1PostPanelModeUpdateReply_FieldNumber) {
  ClassV1PostPanelModeUpdateReply_FieldNumber_HTTPCode = 1,
  ClassV1PostPanelModeUpdateReply_FieldNumber_ErrCode = 2,
  ClassV1PostPanelModeUpdateReply_FieldNumber_ErrMsg = 3,
};

@interface ClassV1PostPanelModeUpdateReply : GPBMessage

@property(nonatomic, readwrite) uint32_t HTTPCode;

@property(nonatomic, readwrite) uint32_t errCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errMsg;

@end

#pragma mark - ClassV1PostRecorderModeUpdateReply

typedef GPB_ENUM(ClassV1PostRecorderModeUpdateReply_FieldNumber) {
  ClassV1PostRecorderModeUpdateReply_FieldNumber_HTTPCode = 1,
  ClassV1PostRecorderModeUpdateReply_FieldNumber_ErrCode = 2,
  ClassV1PostRecorderModeUpdateReply_FieldNumber_ErrMsg = 3,
};

@interface ClassV1PostRecorderModeUpdateReply : GPBMessage

@property(nonatomic, readwrite) uint32_t HTTPCode;

@property(nonatomic, readwrite) uint32_t errCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errMsg;

@end

#pragma mark - ClassV1PostRostersReply

typedef GPB_ENUM(ClassV1PostRostersReply_FieldNumber) {
  ClassV1PostRostersReply_FieldNumber_HTTPCode = 1,
  ClassV1PostRostersReply_FieldNumber_ErrCode = 2,
  ClassV1PostRostersReply_FieldNumber_ErrMsg = 3,
  ClassV1PostRostersReply_FieldNumber_Data_p = 15,
};

@interface ClassV1PostRostersReply : GPBMessage

@property(nonatomic, readwrite) uint32_t HTTPCode;

@property(nonatomic, readwrite) uint32_t errCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errMsg;

@property(nonatomic, readwrite, strong, null_resettable) ClassV1DefinitionsRosters *data_p;
/** Test to see if @c data_p has been set. */
@property(nonatomic, readwrite) BOOL hasData_p;

@end

#pragma mark - ClassV1PostStaticUpdateReply

typedef GPB_ENUM(ClassV1PostStaticUpdateReply_FieldNumber) {
  ClassV1PostStaticUpdateReply_FieldNumber_HTTPCode = 1,
  ClassV1PostStaticUpdateReply_FieldNumber_ErrCode = 2,
  ClassV1PostStaticUpdateReply_FieldNumber_ErrMsg = 3,
  ClassV1PostStaticUpdateReply_FieldNumber_Data_p = 15,
};

@interface ClassV1PostStaticUpdateReply : GPBMessage

@property(nonatomic, readwrite) uint32_t HTTPCode;

@property(nonatomic, readwrite) uint32_t errCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errMsg;

@property(nonatomic, readwrite, strong, null_resettable) ClassV1DefinitionsClassStaticKvs *data_p;
/** Test to see if @c data_p has been set. */
@property(nonatomic, readwrite) BOOL hasData_p;

@end

#pragma mark - ClassV1PostStudentsReply

typedef GPB_ENUM(ClassV1PostStudentsReply_FieldNumber) {
  ClassV1PostStudentsReply_FieldNumber_HTTPCode = 1,
  ClassV1PostStudentsReply_FieldNumber_ErrCode = 2,
  ClassV1PostStudentsReply_FieldNumber_ErrMsg = 3,
  ClassV1PostStudentsReply_FieldNumber_Data_p = 15,
};

@interface ClassV1PostStudentsReply : GPBMessage

@property(nonatomic, readwrite) uint32_t HTTPCode;

@property(nonatomic, readwrite) uint32_t errCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errMsg;

@property(nonatomic, readwrite, strong, null_resettable) ClassV1DefinitionsStudents *data_p;
/** Test to see if @c data_p has been set. */
@property(nonatomic, readwrite) BOOL hasData_p;

@end

#pragma mark - ClassV1PostStudentsDeviceStatusReply

typedef GPB_ENUM(ClassV1PostStudentsDeviceStatusReply_FieldNumber) {
  ClassV1PostStudentsDeviceStatusReply_FieldNumber_HTTPCode = 1,
  ClassV1PostStudentsDeviceStatusReply_FieldNumber_ErrCode = 2,
  ClassV1PostStudentsDeviceStatusReply_FieldNumber_ErrMsg = 3,
};

@interface ClassV1PostStudentsDeviceStatusReply : GPBMessage

@property(nonatomic, readwrite) uint32_t HTTPCode;

@property(nonatomic, readwrite) uint32_t errCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errMsg;

@end

#pragma mark - ClassV1PostStudentsInfosReply

typedef GPB_ENUM(ClassV1PostStudentsInfosReply_FieldNumber) {
  ClassV1PostStudentsInfosReply_FieldNumber_HTTPCode = 1,
  ClassV1PostStudentsInfosReply_FieldNumber_ErrCode = 2,
  ClassV1PostStudentsInfosReply_FieldNumber_ErrMsg = 3,
  ClassV1PostStudentsInfosReply_FieldNumber_Data_p = 15,
};

@interface ClassV1PostStudentsInfosReply : GPBMessage

@property(nonatomic, readwrite) uint32_t HTTPCode;

@property(nonatomic, readwrite) uint32_t errCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errMsg;

@property(nonatomic, readwrite, strong, null_resettable) ClassV1DefinitionsStudents *data_p;
/** Test to see if @c data_p has been set. */
@property(nonatomic, readwrite) BOOL hasData_p;

@end

#pragma mark - ClassV1PostStudentsNumbersReply

typedef GPB_ENUM(ClassV1PostStudentsNumbersReply_FieldNumber) {
  ClassV1PostStudentsNumbersReply_FieldNumber_HTTPCode = 1,
  ClassV1PostStudentsNumbersReply_FieldNumber_ErrCode = 2,
  ClassV1PostStudentsNumbersReply_FieldNumber_ErrMsg = 3,
  ClassV1PostStudentsNumbersReply_FieldNumber_Data_p = 15,
};

@interface ClassV1PostStudentsNumbersReply : GPBMessage

@property(nonatomic, readwrite) uint32_t HTTPCode;

@property(nonatomic, readwrite) uint32_t errCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errMsg;

@property(nonatomic, readwrite, strong, null_resettable) ClassV1DefinitionsClassStudentsNumbers *data_p;
/** Test to see if @c data_p has been set. */
@property(nonatomic, readwrite) BOOL hasData_p;

@end

#pragma mark - ClassV1PostStudentsRandomReply

typedef GPB_ENUM(ClassV1PostStudentsRandomReply_FieldNumber) {
  ClassV1PostStudentsRandomReply_FieldNumber_HTTPCode = 1,
  ClassV1PostStudentsRandomReply_FieldNumber_ErrCode = 2,
  ClassV1PostStudentsRandomReply_FieldNumber_ErrMsg = 3,
  ClassV1PostStudentsRandomReply_FieldNumber_Data_p = 15,
};

@interface ClassV1PostStudentsRandomReply : GPBMessage

@property(nonatomic, readwrite) uint32_t HTTPCode;

@property(nonatomic, readwrite) uint32_t errCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errMsg;

@property(nonatomic, readwrite, strong, null_resettable) ClassV1DefinitionsStudents *data_p;
/** Test to see if @c data_p has been set. */
@property(nonatomic, readwrite) BOOL hasData_p;

@end

#pragma mark - ClassV1PostStudentsStaticUpdateReply

typedef GPB_ENUM(ClassV1PostStudentsStaticUpdateReply_FieldNumber) {
  ClassV1PostStudentsStaticUpdateReply_FieldNumber_HTTPCode = 1,
  ClassV1PostStudentsStaticUpdateReply_FieldNumber_ErrCode = 2,
  ClassV1PostStudentsStaticUpdateReply_FieldNumber_ErrMsg = 3,
};

@interface ClassV1PostStudentsStaticUpdateReply : GPBMessage

@property(nonatomic, readwrite) uint32_t HTTPCode;

@property(nonatomic, readwrite) uint32_t errCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errMsg;

@end

#pragma mark - ClassV1PostUserInfoReply

typedef GPB_ENUM(ClassV1PostUserInfoReply_FieldNumber) {
  ClassV1PostUserInfoReply_FieldNumber_HTTPCode = 1,
  ClassV1PostUserInfoReply_FieldNumber_ErrCode = 2,
  ClassV1PostUserInfoReply_FieldNumber_ErrMsg = 3,
  ClassV1PostUserInfoReply_FieldNumber_Data_p = 15,
};

@interface ClassV1PostUserInfoReply : GPBMessage

@property(nonatomic, readwrite) uint32_t HTTPCode;

@property(nonatomic, readwrite) uint32_t errCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errMsg;

@property(nonatomic, readwrite, strong, null_resettable) ClassV1DefinitionsUserInfo *data_p;
/** Test to see if @c data_p has been set. */
@property(nonatomic, readwrite) BOOL hasData_p;

@end

#pragma mark - ClassV1PostUsersRightUpdateReply

typedef GPB_ENUM(ClassV1PostUsersRightUpdateReply_FieldNumber) {
  ClassV1PostUsersRightUpdateReply_FieldNumber_HTTPCode = 1,
  ClassV1PostUsersRightUpdateReply_FieldNumber_ErrCode = 2,
  ClassV1PostUsersRightUpdateReply_FieldNumber_ErrMsg = 3,
};

@interface ClassV1PostUsersRightUpdateReply : GPBMessage

@property(nonatomic, readwrite) uint32_t HTTPCode;

@property(nonatomic, readwrite) uint32_t errCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errMsg;

@end

#pragma mark - ClassV1PostUsersStatusUpdateReply

typedef GPB_ENUM(ClassV1PostUsersStatusUpdateReply_FieldNumber) {
  ClassV1PostUsersStatusUpdateReply_FieldNumber_HTTPCode = 1,
  ClassV1PostUsersStatusUpdateReply_FieldNumber_ErrCode = 2,
  ClassV1PostUsersStatusUpdateReply_FieldNumber_ErrMsg = 3,
};

@interface ClassV1PostUsersStatusUpdateReply : GPBMessage

@property(nonatomic, readwrite) uint32_t HTTPCode;

@property(nonatomic, readwrite) uint32_t errCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errMsg;

@end

#pragma mark - ClassV1PostUsersSwitchUpdateReply

typedef GPB_ENUM(ClassV1PostUsersSwitchUpdateReply_FieldNumber) {
  ClassV1PostUsersSwitchUpdateReply_FieldNumber_HTTPCode = 1,
  ClassV1PostUsersSwitchUpdateReply_FieldNumber_ErrCode = 2,
  ClassV1PostUsersSwitchUpdateReply_FieldNumber_ErrMsg = 3,
};

@interface ClassV1PostUsersSwitchUpdateReply : GPBMessage

@property(nonatomic, readwrite) uint32_t HTTPCode;

@property(nonatomic, readwrite) uint32_t errCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errMsg;

@end

#pragma mark - ClassV1PostVersionsManagersReply

typedef GPB_ENUM(ClassV1PostVersionsManagersReply_FieldNumber) {
  ClassV1PostVersionsManagersReply_FieldNumber_HTTPCode = 1,
  ClassV1PostVersionsManagersReply_FieldNumber_ErrCode = 2,
  ClassV1PostVersionsManagersReply_FieldNumber_ErrMsg = 3,
  ClassV1PostVersionsManagersReply_FieldNumber_Data_p = 15,
};

@interface ClassV1PostVersionsManagersReply : GPBMessage

@property(nonatomic, readwrite) uint32_t HTTPCode;

@property(nonatomic, readwrite) uint32_t errCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errMsg;

@property(nonatomic, readwrite, strong, null_resettable) ClassV1DefinitionsVersionManagers *data_p;
/** Test to see if @c data_p has been set. */
@property(nonatomic, readwrite) BOOL hasData_p;

@end

#pragma mark - ClassV1DefinitionsActiveInfo

typedef GPB_ENUM(ClassV1DefinitionsActiveInfo_FieldNumber) {
  ClassV1DefinitionsActiveInfo_FieldNumber_ClassCurVersion = 1,
  ClassV1DefinitionsActiveInfo_FieldNumber_UserActiveInfo = 2,
  ClassV1DefinitionsActiveInfo_FieldNumber_SessionOnline = 3,
  ClassV1DefinitionsActiveInfo_FieldNumber_ClassActiveInfo = 4,
  ClassV1DefinitionsActiveInfo_FieldNumber_VersionManagerVer = 5,
  ClassV1DefinitionsActiveInfo_FieldNumber_UserCurVersion = 6,
  ClassV1DefinitionsActiveInfo_FieldNumber_ClassStatic = 7,
};

@interface ClassV1DefinitionsActiveInfo : GPBMessage

/** 教室当前版本 */
@property(nonatomic, readwrite) uint32_t classCurVersion;

/** 用户动态信息 */
@property(nonatomic, readwrite, strong, null_resettable) ClassV1DefinitionsUserActiveInfo *userActiveInfo;
/** Test to see if @c userActiveInfo has been set. */
@property(nonatomic, readwrite) BOOL hasUserActiveInfo;

/** 此链接是否在线，如果为否, 请断开链接，重新进教室。 */
@property(nonatomic, readwrite) BOOL sessionOnline;

/** 教室重要信息 */
@property(nonatomic, readwrite, strong, null_resettable) ClassV1DefinitionsClassActiveInfo *classActiveInfo;
/** Test to see if @c classActiveInfo has been set. */
@property(nonatomic, readwrite) BOOL hasClassActiveInfo;

/** 教室当前版本 */
@property(nonatomic, readwrite) uint32_t versionManagerVer;

/** 用户当前版本 */
@property(nonatomic, readwrite) uint32_t userCurVersion;

@property(nonatomic, readwrite, strong, null_resettable) ClassV1DefinitionsClassStatic *classStatic;
/** Test to see if @c classStatic has been set. */
@property(nonatomic, readwrite) BOOL hasClassStatic;

@end

#pragma mark - ClassV1DefinitionsActiveQuery

typedef GPB_ENUM(ClassV1DefinitionsActiveQuery_FieldNumber) {
  ClassV1DefinitionsActiveQuery_FieldNumber_Cid = 1,
};

@interface ClassV1DefinitionsActiveQuery : GPBMessage

/** 班级id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

@end

#pragma mark - ClassV1DefinitionsBadge

typedef GPB_ENUM(ClassV1DefinitionsBadge_FieldNumber) {
  ClassV1DefinitionsBadge_FieldNumber_CategoryType = 1,
  ClassV1DefinitionsBadge_FieldNumber_ItemId = 3,
};

@interface ClassV1DefinitionsBadge : GPBMessage

/** 徽章类型 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *categoryType;

/** 徽章id */
@property(nonatomic, readwrite) uint32_t itemId;

@end

#pragma mark - ClassV1DefinitionsClassActiveInfo

typedef GPB_ENUM(ClassV1DefinitionsClassActiveInfo_FieldNumber) {
  ClassV1DefinitionsClassActiveInfo_FieldNumber_RtcSdk = 17,
  ClassV1DefinitionsClassActiveInfo_FieldNumber_Mode = 18,
  ClassV1DefinitionsClassActiveInfo_FieldNumber_PanelMode = 19,
  ClassV1DefinitionsClassActiveInfo_FieldNumber_RecorderMode = 20,
  ClassV1DefinitionsClassActiveInfo_FieldNumber_CommonSet = 22,
  ClassV1DefinitionsClassActiveInfo_FieldNumber_IsClosed = 23,
};

@interface ClassV1DefinitionsClassActiveInfo : GPBMessage

/** rtc_sdk类型 ｜ 1、声网  2、自研sdk  3、全时 */
@property(nonatomic, readwrite) uint32_t rtcSdk;

/** 演讲模式 | 0：助教讲课模式   1：老师上课模式 2：老师助教同时上课 */
@property(nonatomic, readwrite) uint32_t mode;

/** 教室面板模式 ｜1：教学模式 2：面板模式 3：视频模式 */
@property(nonatomic, readwrite) uint32_t panelMode;

/** （上课时）录制播放模式，0： 播放  1：老师答疑 */
@property(nonatomic, readwrite) uint32_t recorderMode;

/** 教室授权 */
@property(nonatomic, readwrite) uint32_t commonSet;

/** 教室是否关闭 */
@property(nonatomic, readwrite) BOOL isClosed;

@end

#pragma mark - ClassV1DefinitionsClassCusData

typedef GPB_ENUM(ClassV1DefinitionsClassCusData_FieldNumber) {
  ClassV1DefinitionsClassCusData_FieldNumber_Cid = 1,
  ClassV1DefinitionsClassCusData_FieldNumber_CusData = 2,
  ClassV1DefinitionsClassCusData_FieldNumber_Status = 3,
};

@interface ClassV1DefinitionsClassCusData : GPBMessage

/** 班级id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

/** 额外信息 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *cusData;

/** 用户进入教室默认的状态 */
@property(nonatomic, readwrite) uint32_t status;

@end

#pragma mark - ClassV1DefinitionsClassGrades

typedef GPB_ENUM(ClassV1DefinitionsClassGrades_FieldNumber) {
  ClassV1DefinitionsClassGrades_FieldNumber_Total = 1,
  ClassV1DefinitionsClassGrades_FieldNumber_GradesArray = 2,
  ClassV1DefinitionsClassGrades_FieldNumber_Version = 3,
};

@interface ClassV1DefinitionsClassGrades : GPBMessage

/** 班级总数量 */
@property(nonatomic, readwrite) uint32_t total;

/** 分组教室 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ClassV1DefinitionsClassInfoWithOnline*> *gradesArray;
/** The number of items in @c gradesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger gradesArray_Count;

/** 版本信息 */
@property(nonatomic, readwrite) uint32_t version;

@end

#pragma mark - ClassV1DefinitionsClassId

typedef GPB_ENUM(ClassV1DefinitionsClassId_FieldNumber) {
  ClassV1DefinitionsClassId_FieldNumber_Cid = 1,
};

@interface ClassV1DefinitionsClassId : GPBMessage

/** 班级id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

@end

#pragma mark - ClassV1DefinitionsClassInfo

typedef GPB_ENUM(ClassV1DefinitionsClassInfo_FieldNumber) {
  ClassV1DefinitionsClassInfo_FieldNumber_Cid = 1,
  ClassV1DefinitionsClassInfo_FieldNumber_Name = 2,
  ClassV1DefinitionsClassInfo_FieldNumber_Ename = 3,
  ClassV1DefinitionsClassInfo_FieldNumber_Rid = 4,
  ClassV1DefinitionsClassInfo_FieldNumber_Pid = 5,
  ClassV1DefinitionsClassInfo_FieldNumber_Type = 6,
  ClassV1DefinitionsClassInfo_FieldNumber_Avatar = 7,
  ClassV1DefinitionsClassInfo_FieldNumber_RosterNum = 8,
  ClassV1DefinitionsClassInfo_FieldNumber_TimeAt = 9,
  ClassV1DefinitionsClassInfo_FieldNumber_Version = 10,
  ClassV1DefinitionsClassInfo_FieldNumber_OrgId = 11,
  ClassV1DefinitionsClassInfo_FieldNumber_SubOrgId = 12,
  ClassV1DefinitionsClassInfo_FieldNumber_Level = 13,
  ClassV1DefinitionsClassInfo_FieldNumber_TechName = 14,
  ClassV1DefinitionsClassInfo_FieldNumber_ControlCid = 15,
  ClassV1DefinitionsClassInfo_FieldNumber_ShowOnlineNum = 16,
  ClassV1DefinitionsClassInfo_FieldNumber_TeacherArray = 33,
  ClassV1DefinitionsClassInfo_FieldNumber_AssistantArray = 34,
};

@interface ClassV1DefinitionsClassInfo : GPBMessage

/** 教室id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

/** 课程名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** 教室英文名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ename;

/** 教室主班id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *rid;

/** 教室助教id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *pid;

/** 教室类型 ｜ 1、小班  2、双师班  3、大班  4、vip班  5、超大班 */
@property(nonatomic, readwrite) uint32_t type;

/** 课程头像url */
@property(nonatomic, readwrite, copy, null_resettable) NSString *avatar;

/** 报名学生数量 */
@property(nonatomic, readwrite) uint32_t rosterNum;

/** 教室的时间 */
@property(nonatomic, readwrite, strong, null_resettable) ClassV1DefinitionsClassTimeAt *timeAt;
/** Test to see if @c timeAt has been set. */
@property(nonatomic, readwrite) BOOL hasTimeAt;

/** 教室基础信息版本信息 */
@property(nonatomic, readwrite) uint32_t version;

/** 云教室主机构id */
@property(nonatomic, readwrite) uint32_t orgId;

/** 云教室子机构id */
@property(nonatomic, readwrite) uint32_t subOrgId;

/** 教室层级 ｜ 0、老师（主）教室  1、助教（中）教室  2、学生（子）教室 */
@property(nonatomic, readwrite) uint32_t level;

/** 老师教室名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *techName;

/** 主控cid */
@property(nonatomic, readwrite, copy, null_resettable) NSString *controlCid;

/** 是否显示在线人数 0 不展示 1 展示 */
@property(nonatomic, readwrite) uint32_t showOnlineNum;

/** 老师列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ClassV1DefinitionsTeacherSimple*> *teacherArray;
/** The number of items in @c teacherArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger teacherArray_Count;

/** 助教列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ClassV1DefinitionsTeacherSimple*> *assistantArray;
/** The number of items in @c assistantArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger assistantArray_Count;

@end

#pragma mark - ClassV1DefinitionsClassInfoWithActive

typedef GPB_ENUM(ClassV1DefinitionsClassInfoWithActive_FieldNumber) {
  ClassV1DefinitionsClassInfoWithActive_FieldNumber_Cid = 1,
  ClassV1DefinitionsClassInfoWithActive_FieldNumber_Name = 2,
  ClassV1DefinitionsClassInfoWithActive_FieldNumber_Ename = 3,
  ClassV1DefinitionsClassInfoWithActive_FieldNumber_Rid = 4,
  ClassV1DefinitionsClassInfoWithActive_FieldNumber_Pid = 5,
  ClassV1DefinitionsClassInfoWithActive_FieldNumber_Type = 6,
  ClassV1DefinitionsClassInfoWithActive_FieldNumber_Avatar = 7,
  ClassV1DefinitionsClassInfoWithActive_FieldNumber_RosterNum = 8,
  ClassV1DefinitionsClassInfoWithActive_FieldNumber_TimeAt = 9,
  ClassV1DefinitionsClassInfoWithActive_FieldNumber_Version = 10,
  ClassV1DefinitionsClassInfoWithActive_FieldNumber_OrgId = 11,
  ClassV1DefinitionsClassInfoWithActive_FieldNumber_SubOrgId = 12,
  ClassV1DefinitionsClassInfoWithActive_FieldNumber_Level = 13,
  ClassV1DefinitionsClassInfoWithActive_FieldNumber_TechName = 14,
  ClassV1DefinitionsClassInfoWithActive_FieldNumber_ControlCid = 15,
  ClassV1DefinitionsClassInfoWithActive_FieldNumber_ShowOnlineNum = 16,
  ClassV1DefinitionsClassInfoWithActive_FieldNumber_RtcSdk = 17,
  ClassV1DefinitionsClassInfoWithActive_FieldNumber_Mode = 18,
  ClassV1DefinitionsClassInfoWithActive_FieldNumber_PanelMode = 19,
  ClassV1DefinitionsClassInfoWithActive_FieldNumber_RecorderMode = 20,
  ClassV1DefinitionsClassInfoWithActive_FieldNumber_CommonSet = 22,
  ClassV1DefinitionsClassInfoWithActive_FieldNumber_IsClosed = 23,
  ClassV1DefinitionsClassInfoWithActive_FieldNumber_TeacherArray = 33,
  ClassV1DefinitionsClassInfoWithActive_FieldNumber_AssistantArray = 34,
};

@interface ClassV1DefinitionsClassInfoWithActive : GPBMessage

/** 教室id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

/** 课程名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** 教室英文名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ename;

/** 教室主班id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *rid;

/** 教室助教id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *pid;

/** 教室类型 ｜ 1、小班  2、双师班  3、大班  4、vip班  5、超大班 */
@property(nonatomic, readwrite) uint32_t type;

/** 课程头像url */
@property(nonatomic, readwrite, copy, null_resettable) NSString *avatar;

/** 报名学生数量 */
@property(nonatomic, readwrite) uint32_t rosterNum;

/** 教室的时间 */
@property(nonatomic, readwrite, strong, null_resettable) ClassV1DefinitionsClassTimeAt *timeAt;
/** Test to see if @c timeAt has been set. */
@property(nonatomic, readwrite) BOOL hasTimeAt;

/** 教室基础信息版本信息 */
@property(nonatomic, readwrite) uint32_t version;

/** 云教室主机构id */
@property(nonatomic, readwrite) uint32_t orgId;

/** 云教室子机构id */
@property(nonatomic, readwrite) uint32_t subOrgId;

/** 教室层级 ｜ 0、老师（主）教室  1、助教（中）教室  2、学生（子）教室 */
@property(nonatomic, readwrite) uint32_t level;

/** 老师教室名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *techName;

/** 主控cid */
@property(nonatomic, readwrite, copy, null_resettable) NSString *controlCid;

/** 是否显示在线人数 0 不展示 1 展示 */
@property(nonatomic, readwrite) uint32_t showOnlineNum;

/** rtc_sdk类型 ｜ 1、声网  2、自研sdk  3、全时 */
@property(nonatomic, readwrite) uint32_t rtcSdk;

/** 演讲模式 | 0：助教讲课模式   1：老师上课模式 2：老师助教同时上课 */
@property(nonatomic, readwrite) uint32_t mode;

/** 教室面板模式 ｜1：教学模式 2：面板模式 3：视频模式 */
@property(nonatomic, readwrite) uint32_t panelMode;

/** （上课时）录制播放模式，0： 播放  1：老师答疑 */
@property(nonatomic, readwrite) uint32_t recorderMode;

/** 教室授权 */
@property(nonatomic, readwrite) uint32_t commonSet;

/** 教室是否关闭 */
@property(nonatomic, readwrite) BOOL isClosed;

/** 老师列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ClassV1DefinitionsTeacherSimple*> *teacherArray;
/** The number of items in @c teacherArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger teacherArray_Count;

/** 助教列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ClassV1DefinitionsTeacherSimple*> *assistantArray;
/** The number of items in @c assistantArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger assistantArray_Count;

@end

#pragma mark - ClassV1DefinitionsClassInfoWithOnline

typedef GPB_ENUM(ClassV1DefinitionsClassInfoWithOnline_FieldNumber) {
  ClassV1DefinitionsClassInfoWithOnline_FieldNumber_Cid = 1,
  ClassV1DefinitionsClassInfoWithOnline_FieldNumber_Name = 2,
  ClassV1DefinitionsClassInfoWithOnline_FieldNumber_Ename = 3,
  ClassV1DefinitionsClassInfoWithOnline_FieldNumber_Rid = 4,
  ClassV1DefinitionsClassInfoWithOnline_FieldNumber_Pid = 5,
  ClassV1DefinitionsClassInfoWithOnline_FieldNumber_Type = 6,
  ClassV1DefinitionsClassInfoWithOnline_FieldNumber_Avatar = 7,
  ClassV1DefinitionsClassInfoWithOnline_FieldNumber_RosterNum = 8,
  ClassV1DefinitionsClassInfoWithOnline_FieldNumber_TimeAt = 9,
  ClassV1DefinitionsClassInfoWithOnline_FieldNumber_Version = 10,
  ClassV1DefinitionsClassInfoWithOnline_FieldNumber_OrgId = 11,
  ClassV1DefinitionsClassInfoWithOnline_FieldNumber_SubOrgId = 12,
  ClassV1DefinitionsClassInfoWithOnline_FieldNumber_Level = 13,
  ClassV1DefinitionsClassInfoWithOnline_FieldNumber_TechName = 14,
  ClassV1DefinitionsClassInfoWithOnline_FieldNumber_ControlCid = 15,
  ClassV1DefinitionsClassInfoWithOnline_FieldNumber_ShowOnlineNum = 16,
  ClassV1DefinitionsClassInfoWithOnline_FieldNumber_OnlineNum = 20,
  ClassV1DefinitionsClassInfoWithOnline_FieldNumber_JoinNum = 21,
  ClassV1DefinitionsClassInfoWithOnline_FieldNumber_HighNum = 22,
  ClassV1DefinitionsClassInfoWithOnline_FieldNumber_PerNum = 23,
  ClassV1DefinitionsClassInfoWithOnline_FieldNumber_TeacherArray = 33,
  ClassV1DefinitionsClassInfoWithOnline_FieldNumber_AssistantArray = 34,
};

@interface ClassV1DefinitionsClassInfoWithOnline : GPBMessage

/** 教室id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

/** 课程名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** 教室英文名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ename;

/** 教室主班id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *rid;

/** 教室助教id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *pid;

/** 教室类型 ｜ 1、小班  2、双师班  3、大班  4、vip班  5、超大班 */
@property(nonatomic, readwrite) uint32_t type;

/** 课程头像url */
@property(nonatomic, readwrite, copy, null_resettable) NSString *avatar;

/** 报名学生数量 */
@property(nonatomic, readwrite) uint32_t rosterNum;

/** 教室的时间 */
@property(nonatomic, readwrite, strong, null_resettable) ClassV1DefinitionsClassTimeAt *timeAt;
/** Test to see if @c timeAt has been set. */
@property(nonatomic, readwrite) BOOL hasTimeAt;

/** 教室基础信息版本信息 */
@property(nonatomic, readwrite) uint32_t version;

/** 云教室主机构id */
@property(nonatomic, readwrite) uint32_t orgId;

/** 云教室子机构id */
@property(nonatomic, readwrite) uint32_t subOrgId;

/** 教室层级 ｜ 0、老师（主）教室  1、助教（中）教室  2、学生（子）教室 */
@property(nonatomic, readwrite) uint32_t level;

/** 老师教室名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *techName;

/** 主控cid */
@property(nonatomic, readwrite, copy, null_resettable) NSString *controlCid;

/** 是否显示在线人数 0 不展示 1 展示 */
@property(nonatomic, readwrite) uint32_t showOnlineNum;

/** 在线人数 */
@property(nonatomic, readwrite) uint32_t onlineNum;

/** 进入教室人数 */
@property(nonatomic, readwrite) uint32_t joinNum;

/** 最高在线人数 */
@property(nonatomic, readwrite) uint32_t highNum;

/** 人次 */
@property(nonatomic, readwrite) uint32_t perNum;

/** 老师列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ClassV1DefinitionsTeacherSimple*> *teacherArray;
/** The number of items in @c teacherArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger teacherArray_Count;

/** 助教列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ClassV1DefinitionsTeacherSimple*> *assistantArray;
/** The number of items in @c assistantArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger assistantArray_Count;

@end

#pragma mark - ClassV1DefinitionsClassNumKvAdd

typedef GPB_ENUM(ClassV1DefinitionsClassNumKvAdd_FieldNumber) {
  ClassV1DefinitionsClassNumKvAdd_FieldNumber_Cid = 1,
  ClassV1DefinitionsClassNumKvAdd_FieldNumber_Key = 2,
  ClassV1DefinitionsClassNumKvAdd_FieldNumber_Value = 3,
  ClassV1DefinitionsClassNumKvAdd_FieldNumber_Mode = 4,
};

@interface ClassV1DefinitionsClassNumKvAdd : GPBMessage

/** 当前所在的班级id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

/** 数据类型(like_num - 点赞， follow_num - 关注数据) */
@property(nonatomic, readwrite, copy, null_resettable) NSString *key;

/** 数据的值 */
@property(nonatomic, readwrite) uint32_t value;

/** 数据覆盖的类型( 0 覆盖 1 增加 2 减少) */
@property(nonatomic, readwrite) uint32_t mode;

@end

#pragma mark - ClassV1DefinitionsClassSimple

typedef GPB_ENUM(ClassV1DefinitionsClassSimple_FieldNumber) {
  ClassV1DefinitionsClassSimple_FieldNumber_Cid = 1,
  ClassV1DefinitionsClassSimple_FieldNumber_Name = 2,
  ClassV1DefinitionsClassSimple_FieldNumber_Ename = 3,
  ClassV1DefinitionsClassSimple_FieldNumber_Rid = 4,
  ClassV1DefinitionsClassSimple_FieldNumber_Pid = 5,
  ClassV1DefinitionsClassSimple_FieldNumber_Type = 6,
  ClassV1DefinitionsClassSimple_FieldNumber_Avatar = 7,
  ClassV1DefinitionsClassSimple_FieldNumber_RosterNum = 8,
  ClassV1DefinitionsClassSimple_FieldNumber_TimeAt = 9,
  ClassV1DefinitionsClassSimple_FieldNumber_Version = 10,
  ClassV1DefinitionsClassSimple_FieldNumber_OrgId = 11,
  ClassV1DefinitionsClassSimple_FieldNumber_SubOrgId = 12,
  ClassV1DefinitionsClassSimple_FieldNumber_Level = 13,
  ClassV1DefinitionsClassSimple_FieldNumber_TechName = 14,
  ClassV1DefinitionsClassSimple_FieldNumber_ControlCid = 15,
  ClassV1DefinitionsClassSimple_FieldNumber_ShowOnlineNum = 16,
};

@interface ClassV1DefinitionsClassSimple : GPBMessage

/** 教室id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

/** 课程名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** 教室英文名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ename;

/** 教室主班id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *rid;

/** 教室助教id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *pid;

/** 教室类型 ｜ 1、小班  2、双师班  3、大班  4、vip班  5、超大班 */
@property(nonatomic, readwrite) uint32_t type;

/** 课程头像url */
@property(nonatomic, readwrite, copy, null_resettable) NSString *avatar;

/** 报名学生数量 */
@property(nonatomic, readwrite) uint32_t rosterNum;

/** 教室的时间 */
@property(nonatomic, readwrite, strong, null_resettable) ClassV1DefinitionsClassTimeAt *timeAt;
/** Test to see if @c timeAt has been set. */
@property(nonatomic, readwrite) BOOL hasTimeAt;

/** 教室基础信息版本信息 */
@property(nonatomic, readwrite) uint32_t version;

/** 云教室主机构id */
@property(nonatomic, readwrite) uint32_t orgId;

/** 云教室子机构id */
@property(nonatomic, readwrite) uint32_t subOrgId;

/** 教室层级 ｜ 0、老师（主）教室  1、助教（中）教室  2、学生（子）教室 */
@property(nonatomic, readwrite) uint32_t level;

/** 老师教室名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *techName;

/** 主控cid */
@property(nonatomic, readwrite, copy, null_resettable) NSString *controlCid;

/** 是否显示在线人数 0 不展示 1 展示 */
@property(nonatomic, readwrite) uint32_t showOnlineNum;

@end

#pragma mark - ClassV1DefinitionsClassSimpleWithActive

typedef GPB_ENUM(ClassV1DefinitionsClassSimpleWithActive_FieldNumber) {
  ClassV1DefinitionsClassSimpleWithActive_FieldNumber_Cid = 1,
  ClassV1DefinitionsClassSimpleWithActive_FieldNumber_Name = 2,
  ClassV1DefinitionsClassSimpleWithActive_FieldNumber_Ename = 3,
  ClassV1DefinitionsClassSimpleWithActive_FieldNumber_Rid = 4,
  ClassV1DefinitionsClassSimpleWithActive_FieldNumber_Pid = 5,
  ClassV1DefinitionsClassSimpleWithActive_FieldNumber_Type = 6,
  ClassV1DefinitionsClassSimpleWithActive_FieldNumber_Avatar = 7,
  ClassV1DefinitionsClassSimpleWithActive_FieldNumber_RosterNum = 8,
  ClassV1DefinitionsClassSimpleWithActive_FieldNumber_TimeAt = 9,
  ClassV1DefinitionsClassSimpleWithActive_FieldNumber_Version = 10,
  ClassV1DefinitionsClassSimpleWithActive_FieldNumber_OrgId = 11,
  ClassV1DefinitionsClassSimpleWithActive_FieldNumber_SubOrgId = 12,
  ClassV1DefinitionsClassSimpleWithActive_FieldNumber_Level = 13,
  ClassV1DefinitionsClassSimpleWithActive_FieldNumber_TechName = 14,
  ClassV1DefinitionsClassSimpleWithActive_FieldNumber_ControlCid = 15,
  ClassV1DefinitionsClassSimpleWithActive_FieldNumber_ShowOnlineNum = 16,
  ClassV1DefinitionsClassSimpleWithActive_FieldNumber_RtcSdk = 17,
  ClassV1DefinitionsClassSimpleWithActive_FieldNumber_Mode = 18,
  ClassV1DefinitionsClassSimpleWithActive_FieldNumber_PanelMode = 19,
  ClassV1DefinitionsClassSimpleWithActive_FieldNumber_RecorderMode = 20,
  ClassV1DefinitionsClassSimpleWithActive_FieldNumber_CommonSet = 22,
  ClassV1DefinitionsClassSimpleWithActive_FieldNumber_IsClosed = 23,
};

@interface ClassV1DefinitionsClassSimpleWithActive : GPBMessage

/** 教室id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

/** 课程名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** 教室英文名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ename;

/** 教室主班id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *rid;

/** 教室助教id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *pid;

/** 教室类型 ｜ 1、小班  2、双师班  3、大班  4、vip班  5、超大班 */
@property(nonatomic, readwrite) uint32_t type;

/** 课程头像url */
@property(nonatomic, readwrite, copy, null_resettable) NSString *avatar;

/** 报名学生数量 */
@property(nonatomic, readwrite) uint32_t rosterNum;

/** 教室的时间 */
@property(nonatomic, readwrite, strong, null_resettable) ClassV1DefinitionsClassTimeAt *timeAt;
/** Test to see if @c timeAt has been set. */
@property(nonatomic, readwrite) BOOL hasTimeAt;

/** 教室基础信息版本信息 */
@property(nonatomic, readwrite) uint32_t version;

/** 云教室主机构id */
@property(nonatomic, readwrite) uint32_t orgId;

/** 云教室子机构id */
@property(nonatomic, readwrite) uint32_t subOrgId;

/** 教室层级 ｜ 0、老师（主）教室  1、助教（中）教室  2、学生（子）教室 */
@property(nonatomic, readwrite) uint32_t level;

/** 老师教室名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *techName;

/** 主控cid */
@property(nonatomic, readwrite, copy, null_resettable) NSString *controlCid;

/** 是否显示在线人数 0 不展示 1 展示 */
@property(nonatomic, readwrite) uint32_t showOnlineNum;

/** rtc_sdk类型 ｜ 1、声网  2、自研sdk  3、全时 */
@property(nonatomic, readwrite) uint32_t rtcSdk;

/** 演讲模式 | 0：助教讲课模式   1：老师上课模式 2：老师助教同时上课 */
@property(nonatomic, readwrite) uint32_t mode;

/** 教室面板模式 ｜1：教学模式 2：面板模式 3：视频模式 */
@property(nonatomic, readwrite) uint32_t panelMode;

/** （上课时）录制播放模式，0： 播放  1：老师答疑 */
@property(nonatomic, readwrite) uint32_t recorderMode;

/** 教室授权 */
@property(nonatomic, readwrite) uint32_t commonSet;

/** 教室是否关闭 */
@property(nonatomic, readwrite) BOOL isClosed;

@end

#pragma mark - ClassV1DefinitionsClassStatic

typedef GPB_ENUM(ClassV1DefinitionsClassStatic_FieldNumber) {
  ClassV1DefinitionsClassStatic_FieldNumber_OnlineNum = 20,
  ClassV1DefinitionsClassStatic_FieldNumber_JoinNum = 21,
  ClassV1DefinitionsClassStatic_FieldNumber_HighNum = 22,
  ClassV1DefinitionsClassStatic_FieldNumber_PerNum = 23,
  ClassV1DefinitionsClassStatic_FieldNumber_Kvs = 30,
};

@interface ClassV1DefinitionsClassStatic : GPBMessage

/** 在线人数 */
@property(nonatomic, readwrite) uint32_t onlineNum;

/** 进入教室人数 */
@property(nonatomic, readwrite) uint32_t joinNum;

/** 最高在线人数 */
@property(nonatomic, readwrite) uint32_t highNum;

/** 人次 */
@property(nonatomic, readwrite) uint32_t perNum;

/** 数据信息 */
@property(nonatomic, readwrite, strong, null_resettable) GPBStringInt64Dictionary *kvs;
/** The number of items in @c kvs without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger kvs_Count;

@end

#pragma mark - ClassV1DefinitionsClassStaticKvs

typedef GPB_ENUM(ClassV1DefinitionsClassStaticKvs_FieldNumber) {
  ClassV1DefinitionsClassStaticKvs_FieldNumber_Kvs = 30,
};

@interface ClassV1DefinitionsClassStaticKvs : GPBMessage

/** 数据信息 */
@property(nonatomic, readwrite, strong, null_resettable) GPBStringInt64Dictionary *kvs;
/** The number of items in @c kvs without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger kvs_Count;

@end

#pragma mark - ClassV1DefinitionsClassStudentsNumbers

typedef GPB_ENUM(ClassV1DefinitionsClassStudentsNumbers_FieldNumber) {
  ClassV1DefinitionsClassStudentsNumbers_FieldNumber_ClassNumberArray = 1,
  ClassV1DefinitionsClassStudentsNumbers_FieldNumber_Version = 2,
};

@interface ClassV1DefinitionsClassStudentsNumbers : GPBMessage

/** 学生数量 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ClassV1DefinitionsStudentsNumber*> *classNumberArray;
/** The number of items in @c classNumberArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger classNumberArray_Count;

/** 版本信息 */
@property(nonatomic, readwrite) uint32_t version;

@end

#pragma mark - ClassV1DefinitionsClassTimeAt

typedef GPB_ENUM(ClassV1DefinitionsClassTimeAt_FieldNumber) {
  ClassV1DefinitionsClassTimeAt_FieldNumber_BeginAt = 1,
  ClassV1DefinitionsClassTimeAt_FieldNumber_EndAt = 2,
  ClassV1DefinitionsClassTimeAt_FieldNumber_EnterAt = 3,
  ClassV1DefinitionsClassTimeAt_FieldNumber_LastAt = 4,
};

@interface ClassV1DefinitionsClassTimeAt : GPBMessage

/** 教室开始时间 */
@property(nonatomic, readwrite) uint64_t beginAt;

/** 教室结束时间 */
@property(nonatomic, readwrite) uint64_t endAt;

/** 教室开始进入时间 */
@property(nonatomic, readwrite) uint64_t enterAt;

/** 教室拖堂时间 */
@property(nonatomic, readwrite) uint64_t lastAt;

@end

#pragma mark - ClassV1DefinitionsClassUpdate

typedef GPB_ENUM(ClassV1DefinitionsClassUpdate_FieldNumber) {
  ClassV1DefinitionsClassUpdate_FieldNumber_Cid = 1,
};

@interface ClassV1DefinitionsClassUpdate : GPBMessage

/** 教室id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

@end

#pragma mark - ClassV1DefinitionsClassUserNums

typedef GPB_ENUM(ClassV1DefinitionsClassUserNums_FieldNumber) {
  ClassV1DefinitionsClassUserNums_FieldNumber_OnlineNum = 20,
  ClassV1DefinitionsClassUserNums_FieldNumber_JoinNum = 21,
  ClassV1DefinitionsClassUserNums_FieldNumber_HighNum = 22,
  ClassV1DefinitionsClassUserNums_FieldNumber_PerNum = 23,
};

@interface ClassV1DefinitionsClassUserNums : GPBMessage

/** 在线人数 */
@property(nonatomic, readwrite) uint32_t onlineNum;

/** 进入教室人数 */
@property(nonatomic, readwrite) uint32_t joinNum;

/** 最高在线人数 */
@property(nonatomic, readwrite) uint32_t highNum;

/** 人次 */
@property(nonatomic, readwrite) uint32_t perNum;

@end

#pragma mark - ClassV1DefinitionsClassVersionPageQuery

typedef GPB_ENUM(ClassV1DefinitionsClassVersionPageQuery_FieldNumber) {
  ClassV1DefinitionsClassVersionPageQuery_FieldNumber_Cid = 1,
  ClassV1DefinitionsClassVersionPageQuery_FieldNumber_Page = 3,
  ClassV1DefinitionsClassVersionPageQuery_FieldNumber_Prepage = 4,
};

@interface ClassV1DefinitionsClassVersionPageQuery : GPBMessage

/** 班级id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

/** 页码，从1开始, 默认1 */
@property(nonatomic, readwrite) uint32_t page;

/** 每页数量，默认200 */
@property(nonatomic, readwrite) uint32_t prepage;

@end

#pragma mark - ClassV1DefinitionsCommonSetUpdate

typedef GPB_ENUM(ClassV1DefinitionsCommonSetUpdate_FieldNumber) {
  ClassV1DefinitionsCommonSetUpdate_FieldNumber_Cid = 1,
  ClassV1DefinitionsCommonSetUpdate_FieldNumber_OpType = 3,
  ClassV1DefinitionsCommonSetUpdate_FieldNumber_Offset = 4,
  ClassV1DefinitionsCommonSetUpdate_FieldNumber_Set = 5,
};

@interface ClassV1DefinitionsCommonSetUpdate : GPBMessage

/** 班级id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

/** 类型  1：按照偏移设置   0：设置全量(不支持这种方式，会报错) */
@property(nonatomic, readwrite) uint32_t opType;

/** 按位存储set 0 -->31 */
@property(nonatomic, readwrite) uint32_t offset;

/** 如果op_type 为0，这里会全部覆盖，否则set 值 0 or 1 */
@property(nonatomic, readwrite) uint32_t set;

@end

#pragma mark - ClassV1DefinitionsCommonSetUpdateReply

typedef GPB_ENUM(ClassV1DefinitionsCommonSetUpdateReply_FieldNumber) {
  ClassV1DefinitionsCommonSetUpdateReply_FieldNumber_Set = 1,
};

@interface ClassV1DefinitionsCommonSetUpdateReply : GPBMessage

/** 返回最新set的全量 */
@property(nonatomic, readwrite) uint32_t set;

@end

#pragma mark - ClassV1DefinitionsEnterInfo

typedef GPB_ENUM(ClassV1DefinitionsEnterInfo_FieldNumber) {
  ClassV1DefinitionsEnterInfo_FieldNumber_Cid = 1,
  ClassV1DefinitionsEnterInfo_FieldNumber_UserInfo = 2,
  ClassV1DefinitionsEnterInfo_FieldNumber_ClassInfo = 3,
  ClassV1DefinitionsEnterInfo_FieldNumber_ActiveTime = 4,
  ClassV1DefinitionsEnterInfo_FieldNumber_MsgTips = 5,
  ClassV1DefinitionsEnterInfo_FieldNumber_ClassStatic = 6,
};

@interface ClassV1DefinitionsEnterInfo : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

@property(nonatomic, readwrite, strong, null_resettable) ClassV1DefinitionsUserInfo *userInfo;
/** Test to see if @c userInfo has been set. */
@property(nonatomic, readwrite) BOOL hasUserInfo;

@property(nonatomic, readwrite, strong, null_resettable) ClassV1DefinitionsClassSimpleWithActive *classInfo;
/** Test to see if @c classInfo has been set. */
@property(nonatomic, readwrite) BOOL hasClassInfo;

/** 定时请求active接口时间，秒级，如果为0，默认30s */
@property(nonatomic, readwrite) uint32_t activeTime;

/** 消息的系统提示 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *msgTips;

@property(nonatomic, readwrite, strong, null_resettable) ClassV1DefinitionsClassStatic *classStatic;
/** Test to see if @c classStatic has been set. */
@property(nonatomic, readwrite) BOOL hasClassStatic;

@end

#pragma mark - ClassV1DefinitionsExitInfo

typedef GPB_ENUM(ClassV1DefinitionsExitInfo_FieldNumber) {
  ClassV1DefinitionsExitInfo_FieldNumber_OnlineNum = 20,
  ClassV1DefinitionsExitInfo_FieldNumber_JoinNum = 21,
  ClassV1DefinitionsExitInfo_FieldNumber_HighNum = 22,
  ClassV1DefinitionsExitInfo_FieldNumber_PerNum = 23,
  ClassV1DefinitionsExitInfo_FieldNumber_Kvs = 30,
  ClassV1DefinitionsExitInfo_FieldNumber_OnlineTs = 31,
};

@interface ClassV1DefinitionsExitInfo : GPBMessage

/** 在线人数 */
@property(nonatomic, readwrite) uint32_t onlineNum;

/** 进入教室人数 */
@property(nonatomic, readwrite) uint32_t joinNum;

/** 最高在线人数 */
@property(nonatomic, readwrite) uint32_t highNum;

/** 人次 */
@property(nonatomic, readwrite) uint32_t perNum;

/** 数据信息 */
@property(nonatomic, readwrite, strong, null_resettable) GPBStringInt64Dictionary *kvs;
/** The number of items in @c kvs without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger kvs_Count;

/** 累计在线时常(秒)（提前+课中+拖堂累计时长） */
@property(nonatomic, readwrite) uint32_t onlineTs;

@end

#pragma mark - ClassV1DefinitionsModeUpdate

typedef GPB_ENUM(ClassV1DefinitionsModeUpdate_FieldNumber) {
  ClassV1DefinitionsModeUpdate_FieldNumber_Cid = 1,
  ClassV1DefinitionsModeUpdate_FieldNumber_Mode = 2,
};

@interface ClassV1DefinitionsModeUpdate : GPBMessage

/** 班级id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

/** 模式 */
@property(nonatomic, readwrite) uint32_t mode;

@end

#pragma mark - ClassV1DefinitionsMsgDel

typedef GPB_ENUM(ClassV1DefinitionsMsgDel_FieldNumber) {
  ClassV1DefinitionsMsgDel_FieldNumber_Cid = 1,
  ClassV1DefinitionsMsgDel_FieldNumber_MsgId = 2,
};

@interface ClassV1DefinitionsMsgDel : GPBMessage

/** 当前所在教室的id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

/** 消息id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *msgId;

@end

#pragma mark - ClassV1DefinitionsRightUpdate

typedef GPB_ENUM(ClassV1DefinitionsRightUpdate_FieldNumber) {
  ClassV1DefinitionsRightUpdate_FieldNumber_Uid = 1,
  ClassV1DefinitionsRightUpdate_FieldNumber_Right = 2,
};

@interface ClassV1DefinitionsRightUpdate : GPBMessage

/** 用户id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *uid;

/** 用户权限 */
@property(nonatomic, readwrite) uint32_t right;

@end

#pragma mark - ClassV1DefinitionsRosterQuery

typedef GPB_ENUM(ClassV1DefinitionsRosterQuery_FieldNumber) {
  ClassV1DefinitionsRosterQuery_FieldNumber_Cid = 1,
  ClassV1DefinitionsRosterQuery_FieldNumber_Page = 3,
  ClassV1DefinitionsRosterQuery_FieldNumber_Prepage = 4,
  ClassV1DefinitionsRosterQuery_FieldNumber_Online = 5,
  ClassV1DefinitionsRosterQuery_FieldNumber_Joined = 6,
  ClassV1DefinitionsRosterQuery_FieldNumber_Name = 7,
  ClassV1DefinitionsRosterQuery_FieldNumber_AllClass = 8,
};

@interface ClassV1DefinitionsRosterQuery : GPBMessage

/** 班级id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

/** 页码，从1开始, 默认1 */
@property(nonatomic, readwrite) uint32_t page;

/** 每页数量，默认200 */
@property(nonatomic, readwrite) uint32_t prepage;

/** 在线状态：0：全部 1：在线 2：离线 */
@property(nonatomic, readwrite) uint32_t online;

/** 出席： 0：全部 1：出席 2：未出席 */
@property(nonatomic, readwrite) uint32_t joined;

/** 姓名搜索 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** 是否全部 0：否 为0时需要传入子班uid   1：是 传入主班或助教班cid 有频次限制，最多2秒一次 */
@property(nonatomic, readwrite) uint32_t allClass;

@end

#pragma mark - ClassV1DefinitionsRosters

typedef GPB_ENUM(ClassV1DefinitionsRosters_FieldNumber) {
  ClassV1DefinitionsRosters_FieldNumber_Total = 1,
  ClassV1DefinitionsRosters_FieldNumber_UsersArray = 2,
  ClassV1DefinitionsRosters_FieldNumber_Version = 3,
};

@interface ClassV1DefinitionsRosters : GPBMessage

/** 总数量 */
@property(nonatomic, readwrite) uint32_t total;

/** 学生列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ClassV1DefinitionsUserInfo*> *usersArray;
/** The number of items in @c usersArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger usersArray_Count;

/** 版本号 */
@property(nonatomic, readwrite) uint32_t version;

@end

#pragma mark - ClassV1DefinitionsSetUpdateBase

typedef GPB_ENUM(ClassV1DefinitionsSetUpdateBase_FieldNumber) {
  ClassV1DefinitionsSetUpdateBase_FieldNumber_OpType = 3,
  ClassV1DefinitionsSetUpdateBase_FieldNumber_Offset = 4,
  ClassV1DefinitionsSetUpdateBase_FieldNumber_Set = 5,
};

@interface ClassV1DefinitionsSetUpdateBase : GPBMessage

/** 类型  1：按照偏移设置   0：设置全量(不支持这种方式，会报错) */
@property(nonatomic, readwrite) uint32_t opType;

/** 按位存储set 0 -->31 */
@property(nonatomic, readwrite) uint32_t offset;

/** 如果op_type 为0，这里会全部覆盖，否则set 值 0 or 1 */
@property(nonatomic, readwrite) uint32_t set;

@end

#pragma mark - ClassV1DefinitionsSkin

typedef GPB_ENUM(ClassV1DefinitionsSkin_FieldNumber) {
  ClassV1DefinitionsSkin_FieldNumber_CategoryId = 1,
  ClassV1DefinitionsSkin_FieldNumber_ExpireAt = 2,
  ClassV1DefinitionsSkin_FieldNumber_SystemItemId = 3,
  ClassV1DefinitionsSkin_FieldNumber_ItemId = 4,
};

@interface ClassV1DefinitionsSkin : GPBMessage

/** 挂件类型 */
@property(nonatomic, readwrite) uint32_t categoryId;

/** 挂件过期时间 */
@property(nonatomic, readwrite) int64_t expireAt;

/** 挂件系统id */
@property(nonatomic, readwrite) uint32_t systemItemId;

/** 挂件id */
@property(nonatomic, readwrite) uint32_t itemId;

@end

#pragma mark - ClassV1DefinitionsStatusDeviceUpdate

typedef GPB_ENUM(ClassV1DefinitionsStatusDeviceUpdate_FieldNumber) {
  ClassV1DefinitionsStatusDeviceUpdate_FieldNumber_Cid = 1,
  ClassV1DefinitionsStatusDeviceUpdate_FieldNumber_Uid = 2,
  ClassV1DefinitionsStatusDeviceUpdate_FieldNumber_Status = 4,
};

@interface ClassV1DefinitionsStatusDeviceUpdate : GPBMessage

/** 班级id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

/** 学生id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *uid;

/** json字符串，设备感知定义，端上定义json */
@property(nonatomic, readwrite, copy, null_resettable) NSString *status;

@end

#pragma mark - ClassV1DefinitionsStatusStaticUpdate

typedef GPB_ENUM(ClassV1DefinitionsStatusStaticUpdate_FieldNumber) {
  ClassV1DefinitionsStatusStaticUpdate_FieldNumber_Cid = 1,
  ClassV1DefinitionsStatusStaticUpdate_FieldNumber_Uid = 2,
  ClassV1DefinitionsStatusStaticUpdate_FieldNumber_MsgNum = 3,
  ClassV1DefinitionsStatusStaticUpdate_FieldNumber_Status = 4,
  ClassV1DefinitionsStatusStaticUpdate_FieldNumber_RecordedHistory = 5,
};

@interface ClassV1DefinitionsStatusStaticUpdate : GPBMessage

/** 班级id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

/** 学生id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *uid;

/** 聊天数量 */
@property(nonatomic, readwrite) uint32_t msgNum;

/** json字符串，统计定义。目前：{"device_type"：int（im注册的devicetype）, "network_status"："根据网络质量"} */
@property(nonatomic, readwrite, copy, null_resettable) NSString *status;

/** 观看录播的历史记录｜单位：秒，观看了多少秒, 0 表示忽略，1 表示开始。 */
@property(nonatomic, readwrite) uint32_t recordedHistory;

@end

#pragma mark - ClassV1DefinitionsStudentQuery

typedef GPB_ENUM(ClassV1DefinitionsStudentQuery_FieldNumber) {
  ClassV1DefinitionsStudentQuery_FieldNumber_StudentsArray = 2,
};

@interface ClassV1DefinitionsStudentQuery : GPBMessage

/** 学生信息列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ClassV1DefinitionsStudentQueryInfo*> *studentsArray;
/** The number of items in @c studentsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger studentsArray_Count;

@end

#pragma mark - ClassV1DefinitionsStudentQueryInfo

typedef GPB_ENUM(ClassV1DefinitionsStudentQueryInfo_FieldNumber) {
  ClassV1DefinitionsStudentQueryInfo_FieldNumber_Cid = 1,
  ClassV1DefinitionsStudentQueryInfo_FieldNumber_Uid = 2,
};

@interface ClassV1DefinitionsStudentQueryInfo : GPBMessage

/** 班级id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

/** 学生uid */
@property(nonatomic, readwrite, copy, null_resettable) NSString *uid;

@end

#pragma mark - ClassV1DefinitionsStudentRandomQuery

typedef GPB_ENUM(ClassV1DefinitionsStudentRandomQuery_FieldNumber) {
  ClassV1DefinitionsStudentRandomQuery_FieldNumber_Cid = 1,
  ClassV1DefinitionsStudentRandomQuery_FieldNumber_Num = 2,
};

@interface ClassV1DefinitionsStudentRandomQuery : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

/** 随机学生数量 */
@property(nonatomic, readwrite) uint32_t num;

@end

#pragma mark - ClassV1DefinitionsStudentStatics

typedef GPB_ENUM(ClassV1DefinitionsStudentStatics_FieldNumber) {
  ClassV1DefinitionsStudentStatics_FieldNumber_StarNum = 1,
  ClassV1DefinitionsStudentStatics_FieldNumber_RecordedHistory = 6,
};

@interface ClassV1DefinitionsStudentStatics : GPBMessage

/** 星星数 */
@property(nonatomic, readwrite) uint32_t starNum;

/** 观看录播的历史记录｜单位：秒，观看了多少秒。 */
@property(nonatomic, readwrite) uint32_t recordedHistory;

@end

#pragma mark - ClassV1DefinitionsStudents

typedef GPB_ENUM(ClassV1DefinitionsStudents_FieldNumber) {
  ClassV1DefinitionsStudents_FieldNumber_Total = 1,
  ClassV1DefinitionsStudents_FieldNumber_UsersArray = 2,
  ClassV1DefinitionsStudents_FieldNumber_Version = 3,
};

@interface ClassV1DefinitionsStudents : GPBMessage

/** 总数量 */
@property(nonatomic, readwrite) uint32_t total;

/** 学生列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ClassV1DefinitionsUserInfo*> *usersArray;
/** The number of items in @c usersArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger usersArray_Count;

/** 版本号 */
@property(nonatomic, readwrite) uint32_t version;

@end

#pragma mark - ClassV1DefinitionsStudentsNumber

typedef GPB_ENUM(ClassV1DefinitionsStudentsNumber_FieldNumber) {
  ClassV1DefinitionsStudentsNumber_FieldNumber_Cid = 1,
  ClassV1DefinitionsStudentsNumber_FieldNumber_OnlineNum = 2,
  ClassV1DefinitionsStudentsNumber_FieldNumber_JoinNum = 3,
  ClassV1DefinitionsStudentsNumber_FieldNumber_RosterNum = 4,
};

@interface ClassV1DefinitionsStudentsNumber : GPBMessage

/** 教室id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

/** 在线人数 */
@property(nonatomic, readwrite) uint32_t onlineNum;

/** 进入教室人数 */
@property(nonatomic, readwrite) uint32_t joinNum;

/** 报名学生数量 */
@property(nonatomic, readwrite) uint32_t rosterNum;

@end

#pragma mark - ClassV1DefinitionsStudentsSetUpdate

typedef GPB_ENUM(ClassV1DefinitionsStudentsSetUpdate_FieldNumber) {
  ClassV1DefinitionsStudentsSetUpdate_FieldNumber_Cid = 1,
  ClassV1DefinitionsStudentsSetUpdate_FieldNumber_Uid = 2,
  ClassV1DefinitionsStudentsSetUpdate_FieldNumber_OpType = 3,
  ClassV1DefinitionsStudentsSetUpdate_FieldNumber_Offset = 4,
  ClassV1DefinitionsStudentsSetUpdate_FieldNumber_Set = 5,
};

@interface ClassV1DefinitionsStudentsSetUpdate : GPBMessage

/** 学生所在的班级id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

/** 学生uid */
@property(nonatomic, readwrite, copy, null_resettable) NSString *uid;

/** 类型  1：按照偏移设置   0：设置全量(不支持这种方式，会报错) */
@property(nonatomic, readwrite) uint32_t opType;

/** 按位存储set 0 -->31 */
@property(nonatomic, readwrite) uint32_t offset;

/** 如果op_type 为0，这里会全部覆盖，否则set 值 0 or 1 */
@property(nonatomic, readwrite) uint32_t set;

@end

#pragma mark - ClassV1DefinitionsTeacherSimple

typedef GPB_ENUM(ClassV1DefinitionsTeacherSimple_FieldNumber) {
  ClassV1DefinitionsTeacherSimple_FieldNumber_Uid = 1,
  ClassV1DefinitionsTeacherSimple_FieldNumber_Name = 2,
  ClassV1DefinitionsTeacherSimple_FieldNumber_RealName = 3,
  ClassV1DefinitionsTeacherSimple_FieldNumber_Avatar = 4,
  ClassV1DefinitionsTeacherSimple_FieldNumber_Identity = 5,
  ClassV1DefinitionsTeacherSimple_FieldNumber_SubOrgId = 7,
  ClassV1DefinitionsTeacherSimple_FieldNumber_OnlineStat = 11,
  ClassV1DefinitionsTeacherSimple_FieldNumber_Right = 12,
  ClassV1DefinitionsTeacherSimple_FieldNumber_UserSwitch = 13,
  ClassV1DefinitionsTeacherSimple_FieldNumber_UserStatus = 14,
};

@interface ClassV1DefinitionsTeacherSimple : GPBMessage

/** 用户id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *uid;

/** 昵称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** 真实姓名 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *realName;

/** 头像 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *avatar;

/** 用户身份 */
@property(nonatomic, readwrite) uint32_t identity;

/** 云教室子机构id */
@property(nonatomic, readwrite) uint32_t subOrgId;

/** 用户在线状态 ｜ 0 离线 1 在线 */
@property(nonatomic, readwrite) uint32_t onlineStat;

/** 用户权限 */
@property(nonatomic, readwrite) uint32_t right;

/** 用户开关 */
@property(nonatomic, readwrite) uint32_t userSwitch;

/** 用户状态 */
@property(nonatomic, readwrite) uint32_t userStatus;

@end

#pragma mark - ClassV1DefinitionsUserActiveInfo

typedef GPB_ENUM(ClassV1DefinitionsUserActiveInfo_FieldNumber) {
  ClassV1DefinitionsUserActiveInfo_FieldNumber_OnlineStat = 11,
  ClassV1DefinitionsUserActiveInfo_FieldNumber_Right = 12,
  ClassV1DefinitionsUserActiveInfo_FieldNumber_UserSwitch = 13,
  ClassV1DefinitionsUserActiveInfo_FieldNumber_Statics = 17,
};

@interface ClassV1DefinitionsUserActiveInfo : GPBMessage

/** 用户在线状态 ｜ 0 离线 1 在线 */
@property(nonatomic, readwrite) uint32_t onlineStat;

/** 用户权限 */
@property(nonatomic, readwrite) uint32_t right;

/** 用户开关 */
@property(nonatomic, readwrite) uint32_t userSwitch;

/** 统计数据 */
@property(nonatomic, readwrite, strong, null_resettable) ClassV1DefinitionsStudentStatics *statics;
/** Test to see if @c statics has been set. */
@property(nonatomic, readwrite) BOOL hasStatics;

@end

#pragma mark - ClassV1DefinitionsUserInfo

typedef GPB_ENUM(ClassV1DefinitionsUserInfo_FieldNumber) {
  ClassV1DefinitionsUserInfo_FieldNumber_Uid = 1,
  ClassV1DefinitionsUserInfo_FieldNumber_Name = 2,
  ClassV1DefinitionsUserInfo_FieldNumber_RealName = 3,
  ClassV1DefinitionsUserInfo_FieldNumber_Avatar = 4,
  ClassV1DefinitionsUserInfo_FieldNumber_Identity = 5,
  ClassV1DefinitionsUserInfo_FieldNumber_SubOrgId = 7,
  ClassV1DefinitionsUserInfo_FieldNumber_OnlineStat = 11,
  ClassV1DefinitionsUserInfo_FieldNumber_Right = 12,
  ClassV1DefinitionsUserInfo_FieldNumber_UserSwitch = 13,
  ClassV1DefinitionsUserInfo_FieldNumber_GroupId = 14,
  ClassV1DefinitionsUserInfo_FieldNumber_GroupIndex = 15,
  ClassV1DefinitionsUserInfo_FieldNumber_SkinsArray = 16,
  ClassV1DefinitionsUserInfo_FieldNumber_Statics = 17,
  ClassV1DefinitionsUserInfo_FieldNumber_Version = 18,
  ClassV1DefinitionsUserInfo_FieldNumber_Cid = 19,
  ClassV1DefinitionsUserInfo_FieldNumber_IsSigned = 21,
  ClassV1DefinitionsUserInfo_FieldNumber_DeviceStatus = 22,
  ClassV1DefinitionsUserInfo_FieldNumber_GroupUserOrder = 23,
  ClassV1DefinitionsUserInfo_FieldNumber_UserStatus = 24,
};

@interface ClassV1DefinitionsUserInfo : GPBMessage

/** 用户id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *uid;

/** 昵称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** 真实姓名 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *realName;

/** 头像 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *avatar;

/** 用户身份 */
@property(nonatomic, readwrite) uint32_t identity;

/** 云教室子机构id */
@property(nonatomic, readwrite) uint32_t subOrgId;

/** 用户在线状态 ｜ 0 离线 1 在线 */
@property(nonatomic, readwrite) uint32_t onlineStat;

/** 用户权限 */
@property(nonatomic, readwrite) uint32_t right;

/** 用户开关 */
@property(nonatomic, readwrite) uint32_t userSwitch;

/** 分组id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupId;

/** 分组序号 */
@property(nonatomic, readwrite) uint32_t groupIndex;

/** 挂件/皮肤 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ClassV1DefinitionsSkin*> *skinsArray;
/** The number of items in @c skinsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger skinsArray_Count;

/** 统计数据 */
@property(nonatomic, readwrite, strong, null_resettable) ClassV1DefinitionsStudentStatics *statics;
/** Test to see if @c statics has been set. */
@property(nonatomic, readwrite) BOOL hasStatics;

/** 动态信息版本 */
@property(nonatomic, readwrite) uint32_t version;

/** 用户所在cid */
@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

/** 是否签到 */
@property(nonatomic, readwrite) BOOL isSigned;

/** 用户设备信息，用于设备感知显示 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceStatus;

/** 分组排序值 */
@property(nonatomic, readwrite) uint32_t groupUserOrder;

/** 用户进入状态 */
@property(nonatomic, readwrite) uint32_t userStatus;

@end

#pragma mark - ClassV1DefinitionsUserQueryInfo

typedef GPB_ENUM(ClassV1DefinitionsUserQueryInfo_FieldNumber) {
  ClassV1DefinitionsUserQueryInfo_FieldNumber_Cid = 1,
  ClassV1DefinitionsUserQueryInfo_FieldNumber_Uid = 2,
};

@interface ClassV1DefinitionsUserQueryInfo : GPBMessage

/** 学生所在的班级id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

/** 学生uid */
@property(nonatomic, readwrite, copy, null_resettable) NSString *uid;

@end

#pragma mark - ClassV1DefinitionsUserSimple

typedef GPB_ENUM(ClassV1DefinitionsUserSimple_FieldNumber) {
  ClassV1DefinitionsUserSimple_FieldNumber_Uid = 1,
  ClassV1DefinitionsUserSimple_FieldNumber_Name = 2,
  ClassV1DefinitionsUserSimple_FieldNumber_RealName = 3,
  ClassV1DefinitionsUserSimple_FieldNumber_Avatar = 4,
  ClassV1DefinitionsUserSimple_FieldNumber_Identity = 5,
  ClassV1DefinitionsUserSimple_FieldNumber_SubOrgId = 7,
};

@interface ClassV1DefinitionsUserSimple : GPBMessage

/** 用户id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *uid;

/** 昵称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** 真实姓名 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *realName;

/** 头像 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *avatar;

/** 用户身份 */
@property(nonatomic, readwrite) uint32_t identity;

/** 云教室子机构id */
@property(nonatomic, readwrite) uint32_t subOrgId;

@end

#pragma mark - ClassV1DefinitionsUserStatusUpdate

typedef GPB_ENUM(ClassV1DefinitionsUserStatusUpdate_FieldNumber) {
  ClassV1DefinitionsUserStatusUpdate_FieldNumber_Cid = 1,
  ClassV1DefinitionsUserStatusUpdate_FieldNumber_Uid = 2,
  ClassV1DefinitionsUserStatusUpdate_FieldNumber_Status = 3,
};

@interface ClassV1DefinitionsUserStatusUpdate : GPBMessage

/** 学生所在的班级id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

/** 学生uid */
@property(nonatomic, readwrite, copy, null_resettable) NSString *uid;

/** 需要更新的用户状态 */
@property(nonatomic, readwrite) uint32_t status;

@end

#pragma mark - ClassV1DefinitionsVersionManagers

typedef GPB_ENUM(ClassV1DefinitionsVersionManagers_FieldNumber) {
  ClassV1DefinitionsVersionManagers_FieldNumber_VerManager = 1,
  ClassV1DefinitionsVersionManagers_FieldNumber_Version = 2,
};

@interface ClassV1DefinitionsVersionManagers : GPBMessage

/** 版本管理 */
@property(nonatomic, readwrite, strong, null_resettable) GPBStringUInt32Dictionary *verManager;
/** The number of items in @c verManager without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger verManager_Count;

/** 版本管理的版本 */
@property(nonatomic, readwrite) uint32_t version;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
