// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: norma.v1.tcp.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class NormaV1DefinitionsAVControl;
@class NormaV1DefinitionsAVControlBaseDataPlat_area;
@class NormaV1DefinitionsAVControlGet;
@class NormaV1DefinitionsAVControlPlatform_data;
@class NormaV1DefinitionsAVControlReplay;
@class NormaV1DefinitionsAVControlReplayPlat_area;
@class NormaV1DefinitionsAVControlUpdate;
@class NormaV1DefinitionsAVControlUpdatePlat_area;
@class NormaV1DefinitionsAVControlUpdateReplay;
@class NormaV1DefinitionsClassVersionQuery;
@class NormaV1DefinitionsClassVideoInfo;
@class NormaV1DefinitionsHandsUpClearInfo;
@class NormaV1DefinitionsHandsUpInfo;
@class NormaV1DefinitionsHandsUpListGet;
@class NormaV1DefinitionsHandsUpListReplay;
@class NormaV1DefinitionsHandsUpResponseInfo;
@class NormaV1DefinitionsHandsUpStarInfo;
@class NormaV1DefinitionsHandsUpSwitchInfo;
@class NormaV1DefinitionsHandsUpUserSimpleInfo;
@class NormaV1DefinitionsStarInfo;
@class NormaV1DefinitionsStarSignConf;
@class NormaV1DefinitionsStarSignConfReply;
@class NormaV1DefinitionsStarSignInfo;
@class NormaV1DefinitionsStarSignInfoReply;
@class NormaV1DefinitionsStarUserInfo;
@class NormaV1DefinitionsSubscribeGet;
@class NormaV1DefinitionsSubscribeInfo;
@class NormaV1DefinitionsSubscribeUpdate;
@class NormaV1DefinitionsSubscribeUpdateReplay;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - NormaV1TcpRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface NormaV1TcpRoot : GPBRootObject
@end

#pragma mark - NormaV1PostAvcontrolGetRequest

typedef GPB_ENUM(NormaV1PostAvcontrolGetRequest_FieldNumber) {
  NormaV1PostAvcontrolGetRequest_FieldNumber_Body = 1,
};

@interface NormaV1PostAvcontrolGetRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NormaV1DefinitionsAVControlGet *body;
/** Test to see if @c body has been set. */
@property(nonatomic, readwrite) BOOL hasBody;

@end

#pragma mark - NormaV1PostAvcontrolUpdateRequest

typedef GPB_ENUM(NormaV1PostAvcontrolUpdateRequest_FieldNumber) {
  NormaV1PostAvcontrolUpdateRequest_FieldNumber_Body = 1,
};

@interface NormaV1PostAvcontrolUpdateRequest : GPBMessage

/** 全量更新上墙连麦和轮台数据 */
@property(nonatomic, readwrite, strong, null_resettable) NormaV1DefinitionsAVControlUpdate *body;
/** Test to see if @c body has been set. */
@property(nonatomic, readwrite) BOOL hasBody;

@end

#pragma mark - NormaV1PostHandsUpClearRequest

typedef GPB_ENUM(NormaV1PostHandsUpClearRequest_FieldNumber) {
  NormaV1PostHandsUpClearRequest_FieldNumber_Body = 1,
};

@interface NormaV1PostHandsUpClearRequest : GPBMessage

/** 清除学生举手信息 */
@property(nonatomic, readwrite, strong, null_resettable) NormaV1DefinitionsHandsUpClearInfo *body;
/** Test to see if @c body has been set. */
@property(nonatomic, readwrite) BOOL hasBody;

@end

#pragma mark - NormaV1PostHandsUpHandsRequest

typedef GPB_ENUM(NormaV1PostHandsUpHandsRequest_FieldNumber) {
  NormaV1PostHandsUpHandsRequest_FieldNumber_Body = 1,
};

@interface NormaV1PostHandsUpHandsRequest : GPBMessage

/** 学生举手信息 */
@property(nonatomic, readwrite, strong, null_resettable) NormaV1DefinitionsHandsUpInfo *body;
/** Test to see if @c body has been set. */
@property(nonatomic, readwrite) BOOL hasBody;

@end

#pragma mark - NormaV1PostHandsUpListRequest

typedef GPB_ENUM(NormaV1PostHandsUpListRequest_FieldNumber) {
  NormaV1PostHandsUpListRequest_FieldNumber_Body = 1,
};

@interface NormaV1PostHandsUpListRequest : GPBMessage

/** 学生举手信息列表信息 */
@property(nonatomic, readwrite, strong, null_resettable) NormaV1DefinitionsHandsUpListGet *body;
/** Test to see if @c body has been set. */
@property(nonatomic, readwrite) BOOL hasBody;

@end

#pragma mark - NormaV1PostHandsUpResponseRequest

typedef GPB_ENUM(NormaV1PostHandsUpResponseRequest_FieldNumber) {
  NormaV1PostHandsUpResponseRequest_FieldNumber_Body = 1,
};

@interface NormaV1PostHandsUpResponseRequest : GPBMessage

/** 举手学生信息 */
@property(nonatomic, readwrite, strong, null_resettable) NormaV1DefinitionsHandsUpResponseInfo *body;
/** Test to see if @c body has been set. */
@property(nonatomic, readwrite) BOOL hasBody;

@end

#pragma mark - NormaV1PostHandsUpStarRequest

typedef GPB_ENUM(NormaV1PostHandsUpStarRequest_FieldNumber) {
  NormaV1PostHandsUpStarRequest_FieldNumber_Body = 1,
};

@interface NormaV1PostHandsUpStarRequest : GPBMessage

/** 给学生发星星 */
@property(nonatomic, readwrite, strong, null_resettable) NormaV1DefinitionsHandsUpStarInfo *body;
/** Test to see if @c body has been set. */
@property(nonatomic, readwrite) BOOL hasBody;

@end

#pragma mark - NormaV1PostHandsUpSwitchRequest

typedef GPB_ENUM(NormaV1PostHandsUpSwitchRequest_FieldNumber) {
  NormaV1PostHandsUpSwitchRequest_FieldNumber_Body = 1,
};

@interface NormaV1PostHandsUpSwitchRequest : GPBMessage

/** 举手功能开关信息 */
@property(nonatomic, readwrite, strong, null_resettable) NormaV1DefinitionsHandsUpSwitchInfo *body;
/** Test to see if @c body has been set. */
@property(nonatomic, readwrite) BOOL hasBody;

@end

#pragma mark - NormaV1PostStarAddRequest

typedef GPB_ENUM(NormaV1PostStarAddRequest_FieldNumber) {
  NormaV1PostStarAddRequest_FieldNumber_Body = 1,
};

@interface NormaV1PostStarAddRequest : GPBMessage

/** 给学生发星星 */
@property(nonatomic, readwrite, strong, null_resettable) NormaV1DefinitionsStarInfo *body;
/** Test to see if @c body has been set. */
@property(nonatomic, readwrite) BOOL hasBody;

@end

#pragma mark - NormaV1PostStarSignConfRequest

typedef GPB_ENUM(NormaV1PostStarSignConfRequest_FieldNumber) {
  NormaV1PostStarSignConfRequest_FieldNumber_Body = 1,
};

@interface NormaV1PostStarSignConfRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NormaV1DefinitionsStarSignConf *body;
/** Test to see if @c body has been set. */
@property(nonatomic, readwrite) BOOL hasBody;

@end

#pragma mark - NormaV1PostStarSignRequest

typedef GPB_ENUM(NormaV1PostStarSignRequest_FieldNumber) {
  NormaV1PostStarSignRequest_FieldNumber_Body = 1,
};

@interface NormaV1PostStarSignRequest : GPBMessage

/** 签到发星星 */
@property(nonatomic, readwrite, strong, null_resettable) NormaV1DefinitionsStarSignInfo *body;
/** Test to see if @c body has been set. */
@property(nonatomic, readwrite) BOOL hasBody;

@end

#pragma mark - NormaV1PostSubscribeInfoRequest

typedef GPB_ENUM(NormaV1PostSubscribeInfoRequest_FieldNumber) {
  NormaV1PostSubscribeInfoRequest_FieldNumber_Body = 1,
};

@interface NormaV1PostSubscribeInfoRequest : GPBMessage

/** 查询订阅 */
@property(nonatomic, readwrite, strong, null_resettable) NormaV1DefinitionsSubscribeGet *body;
/** Test to see if @c body has been set. */
@property(nonatomic, readwrite) BOOL hasBody;

@end

#pragma mark - NormaV1PostSubscribeRequest

typedef GPB_ENUM(NormaV1PostSubscribeRequest_FieldNumber) {
  NormaV1PostSubscribeRequest_FieldNumber_Body = 1,
};

@interface NormaV1PostSubscribeRequest : GPBMessage

/** 更新订阅 */
@property(nonatomic, readwrite, strong, null_resettable) NormaV1DefinitionsSubscribeUpdate *body;
/** Test to see if @c body has been set. */
@property(nonatomic, readwrite) BOOL hasBody;

@end

#pragma mark - NormaV1PostVideosRequest

typedef GPB_ENUM(NormaV1PostVideosRequest_FieldNumber) {
  NormaV1PostVideosRequest_FieldNumber_Body = 1,
};

@interface NormaV1PostVideosRequest : GPBMessage

/** 获取教室视频控制 */
@property(nonatomic, readwrite, strong, null_resettable) NormaV1DefinitionsClassVersionQuery *body;
/** Test to see if @c body has been set. */
@property(nonatomic, readwrite) BOOL hasBody;

@end

#pragma mark - NormaV1PostVideosUpdateRequest

typedef GPB_ENUM(NormaV1PostVideosUpdateRequest_FieldNumber) {
  NormaV1PostVideosUpdateRequest_FieldNumber_Body = 1,
};

@interface NormaV1PostVideosUpdateRequest : GPBMessage

/** 更新教室视频控制 */
@property(nonatomic, readwrite, strong, null_resettable) NormaV1DefinitionsClassVideoInfo *body;
/** Test to see if @c body has been set. */
@property(nonatomic, readwrite) BOOL hasBody;

@end

#pragma mark - NormaV1PostAvcontrolGetReply

typedef GPB_ENUM(NormaV1PostAvcontrolGetReply_FieldNumber) {
  NormaV1PostAvcontrolGetReply_FieldNumber_HTTPCode = 1,
  NormaV1PostAvcontrolGetReply_FieldNumber_ErrCode = 2,
  NormaV1PostAvcontrolGetReply_FieldNumber_ErrMsg = 3,
  NormaV1PostAvcontrolGetReply_FieldNumber_Data_p = 15,
};

@interface NormaV1PostAvcontrolGetReply : GPBMessage

@property(nonatomic, readwrite) uint32_t HTTPCode;

@property(nonatomic, readwrite) uint32_t errCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errMsg;

@property(nonatomic, readwrite, strong, null_resettable) NormaV1DefinitionsAVControlReplay *data_p;
/** Test to see if @c data_p has been set. */
@property(nonatomic, readwrite) BOOL hasData_p;

@end

#pragma mark - NormaV1PostAvcontrolUpdateReply

typedef GPB_ENUM(NormaV1PostAvcontrolUpdateReply_FieldNumber) {
  NormaV1PostAvcontrolUpdateReply_FieldNumber_HTTPCode = 1,
  NormaV1PostAvcontrolUpdateReply_FieldNumber_ErrCode = 2,
  NormaV1PostAvcontrolUpdateReply_FieldNumber_ErrMsg = 3,
  NormaV1PostAvcontrolUpdateReply_FieldNumber_Data_p = 15,
};

@interface NormaV1PostAvcontrolUpdateReply : GPBMessage

@property(nonatomic, readwrite) uint32_t HTTPCode;

@property(nonatomic, readwrite) uint32_t errCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errMsg;

@property(nonatomic, readwrite, strong, null_resettable) NormaV1DefinitionsAVControlUpdateReplay *data_p;
/** Test to see if @c data_p has been set. */
@property(nonatomic, readwrite) BOOL hasData_p;

@end

#pragma mark - NormaV1PostHandsUpClearReply

typedef GPB_ENUM(NormaV1PostHandsUpClearReply_FieldNumber) {
  NormaV1PostHandsUpClearReply_FieldNumber_HTTPCode = 1,
  NormaV1PostHandsUpClearReply_FieldNumber_ErrCode = 2,
  NormaV1PostHandsUpClearReply_FieldNumber_ErrMsg = 3,
};

@interface NormaV1PostHandsUpClearReply : GPBMessage

@property(nonatomic, readwrite) uint32_t HTTPCode;

@property(nonatomic, readwrite) uint32_t errCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errMsg;

@end

#pragma mark - NormaV1PostHandsUpHandsReply

typedef GPB_ENUM(NormaV1PostHandsUpHandsReply_FieldNumber) {
  NormaV1PostHandsUpHandsReply_FieldNumber_HTTPCode = 1,
  NormaV1PostHandsUpHandsReply_FieldNumber_ErrCode = 2,
  NormaV1PostHandsUpHandsReply_FieldNumber_ErrMsg = 3,
};

@interface NormaV1PostHandsUpHandsReply : GPBMessage

@property(nonatomic, readwrite) uint32_t HTTPCode;

@property(nonatomic, readwrite) uint32_t errCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errMsg;

@end

#pragma mark - NormaV1PostHandsUpListReply

typedef GPB_ENUM(NormaV1PostHandsUpListReply_FieldNumber) {
  NormaV1PostHandsUpListReply_FieldNumber_HTTPCode = 1,
  NormaV1PostHandsUpListReply_FieldNumber_ErrCode = 2,
  NormaV1PostHandsUpListReply_FieldNumber_ErrMsg = 3,
  NormaV1PostHandsUpListReply_FieldNumber_Data_p = 15,
};

@interface NormaV1PostHandsUpListReply : GPBMessage

@property(nonatomic, readwrite) uint32_t HTTPCode;

@property(nonatomic, readwrite) uint32_t errCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errMsg;

@property(nonatomic, readwrite, strong, null_resettable) NormaV1DefinitionsHandsUpListReplay *data_p;
/** Test to see if @c data_p has been set. */
@property(nonatomic, readwrite) BOOL hasData_p;

@end

#pragma mark - NormaV1PostHandsUpResponseReply

typedef GPB_ENUM(NormaV1PostHandsUpResponseReply_FieldNumber) {
  NormaV1PostHandsUpResponseReply_FieldNumber_HTTPCode = 1,
  NormaV1PostHandsUpResponseReply_FieldNumber_ErrCode = 2,
  NormaV1PostHandsUpResponseReply_FieldNumber_ErrMsg = 3,
};

@interface NormaV1PostHandsUpResponseReply : GPBMessage

@property(nonatomic, readwrite) uint32_t HTTPCode;

@property(nonatomic, readwrite) uint32_t errCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errMsg;

@end

#pragma mark - NormaV1PostHandsUpStarReply

typedef GPB_ENUM(NormaV1PostHandsUpStarReply_FieldNumber) {
  NormaV1PostHandsUpStarReply_FieldNumber_HTTPCode = 1,
  NormaV1PostHandsUpStarReply_FieldNumber_ErrCode = 2,
  NormaV1PostHandsUpStarReply_FieldNumber_ErrMsg = 3,
};

@interface NormaV1PostHandsUpStarReply : GPBMessage

@property(nonatomic, readwrite) uint32_t HTTPCode;

@property(nonatomic, readwrite) uint32_t errCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errMsg;

@end

#pragma mark - NormaV1PostHandsUpSwitchReply

typedef GPB_ENUM(NormaV1PostHandsUpSwitchReply_FieldNumber) {
  NormaV1PostHandsUpSwitchReply_FieldNumber_HTTPCode = 1,
  NormaV1PostHandsUpSwitchReply_FieldNumber_ErrCode = 2,
  NormaV1PostHandsUpSwitchReply_FieldNumber_ErrMsg = 3,
};

@interface NormaV1PostHandsUpSwitchReply : GPBMessage

@property(nonatomic, readwrite) uint32_t HTTPCode;

@property(nonatomic, readwrite) uint32_t errCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errMsg;

@end

#pragma mark - NormaV1PostStarAddReply

typedef GPB_ENUM(NormaV1PostStarAddReply_FieldNumber) {
  NormaV1PostStarAddReply_FieldNumber_HTTPCode = 1,
  NormaV1PostStarAddReply_FieldNumber_ErrCode = 2,
  NormaV1PostStarAddReply_FieldNumber_ErrMsg = 3,
};

@interface NormaV1PostStarAddReply : GPBMessage

@property(nonatomic, readwrite) uint32_t HTTPCode;

@property(nonatomic, readwrite) uint32_t errCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errMsg;

@end

#pragma mark - NormaV1PostStarSignReply

typedef GPB_ENUM(NormaV1PostStarSignReply_FieldNumber) {
  NormaV1PostStarSignReply_FieldNumber_HTTPCode = 1,
  NormaV1PostStarSignReply_FieldNumber_ErrCode = 2,
  NormaV1PostStarSignReply_FieldNumber_ErrMsg = 3,
  NormaV1PostStarSignReply_FieldNumber_Data_p = 15,
};

@interface NormaV1PostStarSignReply : GPBMessage

@property(nonatomic, readwrite) uint32_t HTTPCode;

@property(nonatomic, readwrite) uint32_t errCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errMsg;

@property(nonatomic, readwrite, strong, null_resettable) NormaV1DefinitionsStarSignInfoReply *data_p;
/** Test to see if @c data_p has been set. */
@property(nonatomic, readwrite) BOOL hasData_p;

@end

#pragma mark - NormaV1PostStarSignConfReply

typedef GPB_ENUM(NormaV1PostStarSignConfReply_FieldNumber) {
  NormaV1PostStarSignConfReply_FieldNumber_HTTPCode = 1,
  NormaV1PostStarSignConfReply_FieldNumber_ErrCode = 2,
  NormaV1PostStarSignConfReply_FieldNumber_ErrMsg = 3,
  NormaV1PostStarSignConfReply_FieldNumber_Data_p = 15,
};

@interface NormaV1PostStarSignConfReply : GPBMessage

@property(nonatomic, readwrite) uint32_t HTTPCode;

@property(nonatomic, readwrite) uint32_t errCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errMsg;

@property(nonatomic, readwrite, strong, null_resettable) NormaV1DefinitionsStarSignConfReply *data_p;
/** Test to see if @c data_p has been set. */
@property(nonatomic, readwrite) BOOL hasData_p;

@end

#pragma mark - NormaV1PostSubscribeReply

typedef GPB_ENUM(NormaV1PostSubscribeReply_FieldNumber) {
  NormaV1PostSubscribeReply_FieldNumber_HTTPCode = 1,
  NormaV1PostSubscribeReply_FieldNumber_ErrCode = 2,
  NormaV1PostSubscribeReply_FieldNumber_ErrMsg = 3,
  NormaV1PostSubscribeReply_FieldNumber_Data_p = 15,
};

@interface NormaV1PostSubscribeReply : GPBMessage

@property(nonatomic, readwrite) uint32_t HTTPCode;

@property(nonatomic, readwrite) uint32_t errCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errMsg;

@property(nonatomic, readwrite, strong, null_resettable) NormaV1DefinitionsSubscribeUpdateReplay *data_p;
/** Test to see if @c data_p has been set. */
@property(nonatomic, readwrite) BOOL hasData_p;

@end

#pragma mark - NormaV1PostSubscribeInfoReply

typedef GPB_ENUM(NormaV1PostSubscribeInfoReply_FieldNumber) {
  NormaV1PostSubscribeInfoReply_FieldNumber_HTTPCode = 1,
  NormaV1PostSubscribeInfoReply_FieldNumber_ErrCode = 2,
  NormaV1PostSubscribeInfoReply_FieldNumber_ErrMsg = 3,
  NormaV1PostSubscribeInfoReply_FieldNumber_Data_p = 15,
};

@interface NormaV1PostSubscribeInfoReply : GPBMessage

@property(nonatomic, readwrite) uint32_t HTTPCode;

@property(nonatomic, readwrite) uint32_t errCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errMsg;

@property(nonatomic, readwrite, strong, null_resettable) NormaV1DefinitionsSubscribeInfo *data_p;
/** Test to see if @c data_p has been set. */
@property(nonatomic, readwrite) BOOL hasData_p;

@end

#pragma mark - NormaV1PostVideosReply

typedef GPB_ENUM(NormaV1PostVideosReply_FieldNumber) {
  NormaV1PostVideosReply_FieldNumber_HTTPCode = 1,
  NormaV1PostVideosReply_FieldNumber_ErrCode = 2,
  NormaV1PostVideosReply_FieldNumber_ErrMsg = 3,
  NormaV1PostVideosReply_FieldNumber_Data_p = 15,
};

@interface NormaV1PostVideosReply : GPBMessage

@property(nonatomic, readwrite) uint32_t HTTPCode;

@property(nonatomic, readwrite) uint32_t errCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errMsg;

@property(nonatomic, readwrite, strong, null_resettable) NormaV1DefinitionsClassVideoInfo *data_p;
/** Test to see if @c data_p has been set. */
@property(nonatomic, readwrite) BOOL hasData_p;

@end

#pragma mark - NormaV1PostVideosUpdateReply

typedef GPB_ENUM(NormaV1PostVideosUpdateReply_FieldNumber) {
  NormaV1PostVideosUpdateReply_FieldNumber_HTTPCode = 1,
  NormaV1PostVideosUpdateReply_FieldNumber_ErrCode = 2,
  NormaV1PostVideosUpdateReply_FieldNumber_ErrMsg = 3,
  NormaV1PostVideosUpdateReply_FieldNumber_Data_p = 15,
};

@interface NormaV1PostVideosUpdateReply : GPBMessage

@property(nonatomic, readwrite) uint32_t HTTPCode;

@property(nonatomic, readwrite) uint32_t errCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errMsg;

@property(nonatomic, readwrite, strong, null_resettable) NormaV1DefinitionsClassVersionQuery *data_p;
/** Test to see if @c data_p has been set. */
@property(nonatomic, readwrite) BOOL hasData_p;

@end

#pragma mark - NormaV1DefinitionsAVControl

typedef GPB_ENUM(NormaV1DefinitionsAVControl_FieldNumber) {
  NormaV1DefinitionsAVControl_FieldNumber_Uid = 1,
  NormaV1DefinitionsAVControl_FieldNumber_Cid = 2,
  NormaV1DefinitionsAVControl_FieldNumber_Type = 3,
  NormaV1DefinitionsAVControl_FieldNumber_PlatformData = 4,
  NormaV1DefinitionsAVControl_FieldNumber_Index = 5,
  NormaV1DefinitionsAVControl_FieldNumber_VideoState = 6,
  NormaV1DefinitionsAVControl_FieldNumber_AudioState = 7,
  NormaV1DefinitionsAVControl_FieldNumber_UserData = 8,
};

@interface NormaV1DefinitionsAVControl : GPBMessage

/** 用户（学生，老师）ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *uid;

/** 用户（学生，老师）教室ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

/** 状态（轮台，讲台，连麦） */
@property(nonatomic, readwrite) uint32_t type;

/** 上讲台视频位置信息 */
@property(nonatomic, readwrite, strong, null_resettable) NormaV1DefinitionsAVControlPlatform_data *platformData;
/** Test to see if @c platformData has been set. */
@property(nonatomic, readwrite) BOOL hasPlatformData;

/** 轮台Index */
@property(nonatomic, readwrite) uint32_t index;

/** 视频状态 */
@property(nonatomic, readwrite) uint32_t videoState;

/** 音频状态 */
@property(nonatomic, readwrite) uint32_t audioState;

/** 用户自定义数据 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userData;

@end

#pragma mark - NormaV1DefinitionsAVControlPlatform_data

typedef GPB_ENUM(NormaV1DefinitionsAVControlPlatform_data_FieldNumber) {
  NormaV1DefinitionsAVControlPlatform_data_FieldNumber_PosX = 1,
  NormaV1DefinitionsAVControlPlatform_data_FieldNumber_PosY = 2,
  NormaV1DefinitionsAVControlPlatform_data_FieldNumber_Width = 3,
  NormaV1DefinitionsAVControlPlatform_data_FieldNumber_Height = 4,
  NormaV1DefinitionsAVControlPlatform_data_FieldNumber_Scale = 5,
  NormaV1DefinitionsAVControlPlatform_data_FieldNumber_Zorder = 6,
};

@interface NormaV1DefinitionsAVControlPlatform_data : GPBMessage

/** 左上X */
@property(nonatomic, readwrite) uint64_t posX;

/** 左上Y */
@property(nonatomic, readwrite) uint64_t posY;

/** 宽 */
@property(nonatomic, readwrite) uint64_t width;

/** 高 */
@property(nonatomic, readwrite) uint64_t height;

/** 缩放 */
@property(nonatomic, readwrite) uint64_t scale;

/** 前后顺序 */
@property(nonatomic, readwrite) uint64_t zorder;

@end

#pragma mark - NormaV1DefinitionsAVControlBaseData

typedef GPB_ENUM(NormaV1DefinitionsAVControlBaseData_FieldNumber) {
  NormaV1DefinitionsAVControlBaseData_FieldNumber_ControlListArray = 1,
  NormaV1DefinitionsAVControlBaseData_FieldNumber_PlatArea = 2,
  NormaV1DefinitionsAVControlBaseData_FieldNumber_MainAudioState = 3,
};

@interface NormaV1DefinitionsAVControlBaseData : GPBMessage

/** 音视频控制列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NormaV1DefinitionsAVControl*> *controlListArray;
/** The number of items in @c controlListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger controlListArray_Count;

/** 讲台区域 */
@property(nonatomic, readwrite, strong, null_resettable) NormaV1DefinitionsAVControlBaseDataPlat_area *platArea;
/** Test to see if @c platArea has been set. */
@property(nonatomic, readwrite) BOOL hasPlatArea;

/** 总音频状态--集体静音 */
@property(nonatomic, readwrite) uint32_t mainAudioState;

@end

#pragma mark - NormaV1DefinitionsAVControlBaseDataPlat_area

typedef GPB_ENUM(NormaV1DefinitionsAVControlBaseDataPlat_area_FieldNumber) {
  NormaV1DefinitionsAVControlBaseDataPlat_area_FieldNumber_Width = 1,
  NormaV1DefinitionsAVControlBaseDataPlat_area_FieldNumber_Height = 2,
};

@interface NormaV1DefinitionsAVControlBaseDataPlat_area : GPBMessage

/** 讲台宽 */
@property(nonatomic, readwrite) uint64_t width;

/** 讲台高 */
@property(nonatomic, readwrite) uint64_t height;

@end

#pragma mark - NormaV1DefinitionsAVControlGet

typedef GPB_ENUM(NormaV1DefinitionsAVControlGet_FieldNumber) {
  NormaV1DefinitionsAVControlGet_FieldNumber_Cid = 1,
  NormaV1DefinitionsAVControlGet_FieldNumber_Version = 2,
};

@interface NormaV1DefinitionsAVControlGet : GPBMessage

/** 教室ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

/** 音视频控制版本 */
@property(nonatomic, readwrite) uint32_t version;

@end

#pragma mark - NormaV1DefinitionsAVControlReplay

typedef GPB_ENUM(NormaV1DefinitionsAVControlReplay_FieldNumber) {
  NormaV1DefinitionsAVControlReplay_FieldNumber_ControlListArray = 1,
  NormaV1DefinitionsAVControlReplay_FieldNumber_PlatArea = 2,
  NormaV1DefinitionsAVControlReplay_FieldNumber_MainAudioState = 3,
  NormaV1DefinitionsAVControlReplay_FieldNumber_Version = 4,
  NormaV1DefinitionsAVControlReplay_FieldNumber_OptUid = 5,
};

@interface NormaV1DefinitionsAVControlReplay : GPBMessage

/** 音视频控制列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NormaV1DefinitionsAVControl*> *controlListArray;
/** The number of items in @c controlListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger controlListArray_Count;

/** 讲台区域 */
@property(nonatomic, readwrite, strong, null_resettable) NormaV1DefinitionsAVControlReplayPlat_area *platArea;
/** Test to see if @c platArea has been set. */
@property(nonatomic, readwrite) BOOL hasPlatArea;

/** 总音频状态--集体静音 */
@property(nonatomic, readwrite) uint32_t mainAudioState;

/** 音视频信息版本 */
@property(nonatomic, readwrite) uint32_t version;

/** 操作者uid */
@property(nonatomic, readwrite, copy, null_resettable) NSString *optUid;

@end

#pragma mark - NormaV1DefinitionsAVControlReplayPlat_area

typedef GPB_ENUM(NormaV1DefinitionsAVControlReplayPlat_area_FieldNumber) {
  NormaV1DefinitionsAVControlReplayPlat_area_FieldNumber_Width = 1,
  NormaV1DefinitionsAVControlReplayPlat_area_FieldNumber_Height = 2,
};

@interface NormaV1DefinitionsAVControlReplayPlat_area : GPBMessage

/** 讲台宽 */
@property(nonatomic, readwrite) uint64_t width;

/** 讲台高 */
@property(nonatomic, readwrite) uint64_t height;

@end

#pragma mark - NormaV1DefinitionsAVControlUpdate

typedef GPB_ENUM(NormaV1DefinitionsAVControlUpdate_FieldNumber) {
  NormaV1DefinitionsAVControlUpdate_FieldNumber_ControlListArray = 1,
  NormaV1DefinitionsAVControlUpdate_FieldNumber_PlatArea = 2,
  NormaV1DefinitionsAVControlUpdate_FieldNumber_MainAudioState = 3,
  NormaV1DefinitionsAVControlUpdate_FieldNumber_Cid = 4,
  NormaV1DefinitionsAVControlUpdate_FieldNumber_Uid = 5,
};

@interface NormaV1DefinitionsAVControlUpdate : GPBMessage

/** 音视频控制列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NormaV1DefinitionsAVControl*> *controlListArray;
/** The number of items in @c controlListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger controlListArray_Count;

/** 讲台区域 */
@property(nonatomic, readwrite, strong, null_resettable) NormaV1DefinitionsAVControlUpdatePlat_area *platArea;
/** Test to see if @c platArea has been set. */
@property(nonatomic, readwrite) BOOL hasPlatArea;

/** 总音频状态--集体静音 */
@property(nonatomic, readwrite) uint32_t mainAudioState;

/** 操作者所在教室id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

/** 操作者uid */
@property(nonatomic, readwrite, copy, null_resettable) NSString *uid;

@end

#pragma mark - NormaV1DefinitionsAVControlUpdatePlat_area

typedef GPB_ENUM(NormaV1DefinitionsAVControlUpdatePlat_area_FieldNumber) {
  NormaV1DefinitionsAVControlUpdatePlat_area_FieldNumber_Width = 1,
  NormaV1DefinitionsAVControlUpdatePlat_area_FieldNumber_Height = 2,
};

@interface NormaV1DefinitionsAVControlUpdatePlat_area : GPBMessage

/** 讲台宽 */
@property(nonatomic, readwrite) uint64_t width;

/** 讲台高 */
@property(nonatomic, readwrite) uint64_t height;

@end

#pragma mark - NormaV1DefinitionsAVControlUpdateReplay

typedef GPB_ENUM(NormaV1DefinitionsAVControlUpdateReplay_FieldNumber) {
  NormaV1DefinitionsAVControlUpdateReplay_FieldNumber_Version = 1,
};

@interface NormaV1DefinitionsAVControlUpdateReplay : GPBMessage

/** 音视频控制版本 */
@property(nonatomic, readwrite) uint32_t version;

@end

#pragma mark - NormaV1DefinitionsClassVersionQuery

typedef GPB_ENUM(NormaV1DefinitionsClassVersionQuery_FieldNumber) {
  NormaV1DefinitionsClassVersionQuery_FieldNumber_Cid = 1,
  NormaV1DefinitionsClassVersionQuery_FieldNumber_Version = 2,
};

@interface NormaV1DefinitionsClassVersionQuery : GPBMessage

/** 班级id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

/** 版本信息 */
@property(nonatomic, readwrite) uint32_t version;

@end

#pragma mark - NormaV1DefinitionsClassVideoInfo

typedef GPB_ENUM(NormaV1DefinitionsClassVideoInfo_FieldNumber) {
  NormaV1DefinitionsClassVideoInfo_FieldNumber_Cid = 1,
  NormaV1DefinitionsClassVideoInfo_FieldNumber_Uid = 2,
  NormaV1DefinitionsClassVideoInfo_FieldNumber_URL = 3,
  NormaV1DefinitionsClassVideoInfo_FieldNumber_Type = 4,
  NormaV1DefinitionsClassVideoInfo_FieldNumber_State = 5,
  NormaV1DefinitionsClassVideoInfo_FieldNumber_Seek = 6,
  NormaV1DefinitionsClassVideoInfo_FieldNumber_SeekAt = 7,
  NormaV1DefinitionsClassVideoInfo_FieldNumber_Version = 8,
  NormaV1DefinitionsClassVideoInfo_FieldNumber_FileName = 9,
};

@interface NormaV1DefinitionsClassVideoInfo : GPBMessage

/** 教室id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

/** 投放者id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *uid;

/** 播放视频的url */
@property(nonatomic, readwrite, copy, null_resettable) NSString *URL;

/** 类型 (0=mp3，1=mp4) */
@property(nonatomic, readwrite) uint32_t type;

/** 播放状态 */
@property(nonatomic, readwrite) uint32_t state;

/** 跳转控制 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *seek;

/** 跳转控制同步时间 */
@property(nonatomic, readwrite) uint32_t seekAt;

/** ClassVideo版本 */
@property(nonatomic, readwrite) uint32_t version;

/** 文件名 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *fileName;

@end

#pragma mark - NormaV1DefinitionsHandsUpClassInfo

typedef GPB_ENUM(NormaV1DefinitionsHandsUpClassInfo_FieldNumber) {
  NormaV1DefinitionsHandsUpClassInfo_FieldNumber_Cid = 1,
};

@interface NormaV1DefinitionsHandsUpClassInfo : GPBMessage

/** 教室ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

@end

#pragma mark - NormaV1DefinitionsHandsUpClearInfo

typedef GPB_ENUM(NormaV1DefinitionsHandsUpClearInfo_FieldNumber) {
  NormaV1DefinitionsHandsUpClearInfo_FieldNumber_Cid = 1,
  NormaV1DefinitionsHandsUpClearInfo_FieldNumber_Uid = 2,
};

@interface NormaV1DefinitionsHandsUpClearInfo : GPBMessage

/** 教室ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

/** 操作者id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *uid;

@end

#pragma mark - NormaV1DefinitionsHandsUpInfo

typedef GPB_ENUM(NormaV1DefinitionsHandsUpInfo_FieldNumber) {
  NormaV1DefinitionsHandsUpInfo_FieldNumber_Uid = 1,
  NormaV1DefinitionsHandsUpInfo_FieldNumber_Cid = 2,
  NormaV1DefinitionsHandsUpInfo_FieldNumber_HandsUp = 3,
};

@interface NormaV1DefinitionsHandsUpInfo : GPBMessage

/** 学生ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *uid;

/** 教室ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

/** 是否举手 */
@property(nonatomic, readwrite) uint32_t handsUp;

@end

#pragma mark - NormaV1DefinitionsHandsUpListGet

typedef GPB_ENUM(NormaV1DefinitionsHandsUpListGet_FieldNumber) {
  NormaV1DefinitionsHandsUpListGet_FieldNumber_Cid = 1,
  NormaV1DefinitionsHandsUpListGet_FieldNumber_Page = 2,
  NormaV1DefinitionsHandsUpListGet_FieldNumber_Perpage = 3,
};

@interface NormaV1DefinitionsHandsUpListGet : GPBMessage

/** 教室ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

/** 页码 */
@property(nonatomic, readwrite) uint32_t page;

/** 页宽 */
@property(nonatomic, readwrite) uint32_t perpage;

@end

#pragma mark - NormaV1DefinitionsHandsUpListReplay

typedef GPB_ENUM(NormaV1DefinitionsHandsUpListReplay_FieldNumber) {
  NormaV1DefinitionsHandsUpListReplay_FieldNumber_UsersArray = 1,
  NormaV1DefinitionsHandsUpListReplay_FieldNumber_Total = 2,
};

@interface NormaV1DefinitionsHandsUpListReplay : GPBMessage

/** 学生举手列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NormaV1DefinitionsHandsUpUserSimpleInfo*> *usersArray;
/** The number of items in @c usersArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger usersArray_Count;

/** 列表总数 */
@property(nonatomic, readwrite) uint32_t total;

@end

#pragma mark - NormaV1DefinitionsHandsUpResponseInfo

typedef GPB_ENUM(NormaV1DefinitionsHandsUpResponseInfo_FieldNumber) {
  NormaV1DefinitionsHandsUpResponseInfo_FieldNumber_Uid = 1,
  NormaV1DefinitionsHandsUpResponseInfo_FieldNumber_Cid = 2,
  NormaV1DefinitionsHandsUpResponseInfo_FieldNumber_StdUid = 3,
  NormaV1DefinitionsHandsUpResponseInfo_FieldNumber_StdCid = 4,
};

@interface NormaV1DefinitionsHandsUpResponseInfo : GPBMessage

/** 老师ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *uid;

/** 老师教室ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

/** 学生ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *stdUid;

/** 学生教室ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *stdCid;

@end

#pragma mark - NormaV1DefinitionsHandsUpStarInfo

typedef GPB_ENUM(NormaV1DefinitionsHandsUpStarInfo_FieldNumber) {
  NormaV1DefinitionsHandsUpStarInfo_FieldNumber_Cid = 1,
  NormaV1DefinitionsHandsUpStarInfo_FieldNumber_Uid = 2,
  NormaV1DefinitionsHandsUpStarInfo_FieldNumber_StarCnt = 3,
};

@interface NormaV1DefinitionsHandsUpStarInfo : GPBMessage

/** 发送者教室ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

/** 发送者ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *uid;

/** 需要加的星星数 */
@property(nonatomic, readwrite) uint32_t starCnt;

@end

#pragma mark - NormaV1DefinitionsHandsUpSwitchInfo

typedef GPB_ENUM(NormaV1DefinitionsHandsUpSwitchInfo_FieldNumber) {
  NormaV1DefinitionsHandsUpSwitchInfo_FieldNumber_Cid = 1,
  NormaV1DefinitionsHandsUpSwitchInfo_FieldNumber_Uid = 2,
  NormaV1DefinitionsHandsUpSwitchInfo_FieldNumber_State = 3,
};

@interface NormaV1DefinitionsHandsUpSwitchInfo : GPBMessage

/** 教室ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

/** 操作者uid */
@property(nonatomic, readwrite, copy, null_resettable) NSString *uid;

/** 举手开关 */
@property(nonatomic, readwrite) uint32_t state;

@end

#pragma mark - NormaV1DefinitionsHandsUpUserSimpleInfo

typedef GPB_ENUM(NormaV1DefinitionsHandsUpUserSimpleInfo_FieldNumber) {
  NormaV1DefinitionsHandsUpUserSimpleInfo_FieldNumber_Uid = 1,
  NormaV1DefinitionsHandsUpUserSimpleInfo_FieldNumber_Cid = 2,
  NormaV1DefinitionsHandsUpUserSimpleInfo_FieldNumber_UserName = 3,
  NormaV1DefinitionsHandsUpUserSimpleInfo_FieldNumber_RealName = 4,
  NormaV1DefinitionsHandsUpUserSimpleInfo_FieldNumber_Avatar = 5,
  NormaV1DefinitionsHandsUpUserSimpleInfo_FieldNumber_StarNum = 6,
  NormaV1DefinitionsHandsUpUserSimpleInfo_FieldNumber_Time = 7,
};

@interface NormaV1DefinitionsHandsUpUserSimpleInfo : GPBMessage

/** 学生ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *uid;

/** 学生所在教室 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

/** 用户名 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userName;

/** 用户昵称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *realName;

/** 用户头像链接 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *avatar;

/** 用户星星数 */
@property(nonatomic, readwrite) uint32_t starNum;

/** 用户举手的时间 */
@property(nonatomic, readwrite) uint64_t time;

@end

#pragma mark - NormaV1DefinitionsStarInfo

typedef GPB_ENUM(NormaV1DefinitionsStarInfo_FieldNumber) {
  NormaV1DefinitionsStarInfo_FieldNumber_Cid = 1,
  NormaV1DefinitionsStarInfo_FieldNumber_Sender = 2,
  NormaV1DefinitionsStarInfo_FieldNumber_UsersArray = 3,
};

@interface NormaV1DefinitionsStarInfo : GPBMessage

/** 发送人教室 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

/** 发送人 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *sender;

/** 学生列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NormaV1DefinitionsStarUserInfo*> *usersArray;
/** The number of items in @c usersArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger usersArray_Count;

@end

#pragma mark - NormaV1DefinitionsStarSignConf

typedef GPB_ENUM(NormaV1DefinitionsStarSignConf_FieldNumber) {
  NormaV1DefinitionsStarSignConf_FieldNumber_Cid = 1,
  NormaV1DefinitionsStarSignConf_FieldNumber_Uid = 2,
};

@interface NormaV1DefinitionsStarSignConf : GPBMessage

/** 教室ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

/** 用户ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *uid;

@end

#pragma mark - NormaV1DefinitionsStarSignConfReply

typedef GPB_ENUM(NormaV1DefinitionsStarSignConfReply_FieldNumber) {
  NormaV1DefinitionsStarSignConfReply_FieldNumber_Cid = 1,
  NormaV1DefinitionsStarSignConfReply_FieldNumber_SignInfo = 2,
  NormaV1DefinitionsStarSignConfReply_FieldNumber_AwardStarCount = 3,
  NormaV1DefinitionsStarSignConfReply_FieldNumber_SignStartTime = 4,
  NormaV1DefinitionsStarSignConfReply_FieldNumber_SignEndTime = 5,
  NormaV1DefinitionsStarSignConfReply_FieldNumber_Effect = 6,
};

@interface NormaV1DefinitionsStarSignConfReply : GPBMessage

/** 教室ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

/** 是否签到 */
@property(nonatomic, readwrite) int64_t signInfo;

/** 奖励星星数 */
@property(nonatomic, readwrite) int64_t awardStarCount;

/** 签到开始时间 */
@property(nonatomic, readwrite) int64_t signStartTime;

/** 签到结束时间 */
@property(nonatomic, readwrite) int64_t signEndTime;

/** 是否开启签到 */
@property(nonatomic, readwrite) int64_t effect;

@end

#pragma mark - NormaV1DefinitionsStarSignInfo

typedef GPB_ENUM(NormaV1DefinitionsStarSignInfo_FieldNumber) {
  NormaV1DefinitionsStarSignInfo_FieldNumber_Uid = 1,
  NormaV1DefinitionsStarSignInfo_FieldNumber_Cid = 2,
};

@interface NormaV1DefinitionsStarSignInfo : GPBMessage

/** 用户ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *uid;

/** 教室ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

@end

#pragma mark - NormaV1DefinitionsStarSignInfoReply

typedef GPB_ENUM(NormaV1DefinitionsStarSignInfoReply_FieldNumber) {
  NormaV1DefinitionsStarSignInfoReply_FieldNumber_Uid = 1,
  NormaV1DefinitionsStarSignInfoReply_FieldNumber_Cid = 2,
  NormaV1DefinitionsStarSignInfoReply_FieldNumber_SignInfo = 3,
  NormaV1DefinitionsStarSignInfoReply_FieldNumber_AwardStarCount = 4,
  NormaV1DefinitionsStarSignInfoReply_FieldNumber_Effect = 5,
};

@interface NormaV1DefinitionsStarSignInfoReply : GPBMessage

/** 用户ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *uid;

/** 教室ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

/** 是否签到 */
@property(nonatomic, readwrite) int64_t signInfo;

/** 奖励星星数 */
@property(nonatomic, readwrite) int64_t awardStarCount;

/** 是否开启签到 */
@property(nonatomic, readwrite) int64_t effect;

@end

#pragma mark - NormaV1DefinitionsStarUserInfo

typedef GPB_ENUM(NormaV1DefinitionsStarUserInfo_FieldNumber) {
  NormaV1DefinitionsStarUserInfo_FieldNumber_Uid = 1,
  NormaV1DefinitionsStarUserInfo_FieldNumber_Cid = 2,
  NormaV1DefinitionsStarUserInfo_FieldNumber_StarCnt = 3,
};

@interface NormaV1DefinitionsStarUserInfo : GPBMessage

/** 用户ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *uid;

/** 教室ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

/** 需要加的星星数 */
@property(nonatomic, readwrite) uint32_t starCnt;

@end

#pragma mark - NormaV1DefinitionsSubscribeGet

typedef GPB_ENUM(NormaV1DefinitionsSubscribeGet_FieldNumber) {
  NormaV1DefinitionsSubscribeGet_FieldNumber_Cid = 1,
  NormaV1DefinitionsSubscribeGet_FieldNumber_Uid = 2,
};

@interface NormaV1DefinitionsSubscribeGet : GPBMessage

/** 教室ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

/** 学生ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *uid;

@end

#pragma mark - NormaV1DefinitionsSubscribeInfo

typedef GPB_ENUM(NormaV1DefinitionsSubscribeInfo_FieldNumber) {
  NormaV1DefinitionsSubscribeInfo_FieldNumber_Uid = 1,
  NormaV1DefinitionsSubscribeInfo_FieldNumber_Cid = 2,
  NormaV1DefinitionsSubscribeInfo_FieldNumber_AudioState = 3,
  NormaV1DefinitionsSubscribeInfo_FieldNumber_VideoState = 4,
};

@interface NormaV1DefinitionsSubscribeInfo : GPBMessage

/** 学生ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *uid;

/** 所在教室ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

/** 音频状态 0=关闭 1=开启 */
@property(nonatomic, readwrite) uint32_t audioState;

/** 视频状态 0=关闭 1=开启 */
@property(nonatomic, readwrite) uint32_t videoState;

@end

#pragma mark - NormaV1DefinitionsSubscribeUpdate

typedef GPB_ENUM(NormaV1DefinitionsSubscribeUpdate_FieldNumber) {
  NormaV1DefinitionsSubscribeUpdate_FieldNumber_Uid = 1,
  NormaV1DefinitionsSubscribeUpdate_FieldNumber_Cid = 2,
  NormaV1DefinitionsSubscribeUpdate_FieldNumber_SubcribeListArray = 3,
};

@interface NormaV1DefinitionsSubscribeUpdate : GPBMessage

/** 订阅者ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *uid;

/** 教室ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

/** 被订阅List */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NormaV1DefinitionsSubscribeInfo*> *subcribeListArray;
/** The number of items in @c subcribeListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger subcribeListArray_Count;

@end

#pragma mark - NormaV1DefinitionsSubscribeUpdateReplay

typedef GPB_ENUM(NormaV1DefinitionsSubscribeUpdateReplay_FieldNumber) {
  NormaV1DefinitionsSubscribeUpdateReplay_FieldNumber_Intervals = 1,
};

@interface NormaV1DefinitionsSubscribeUpdateReplay : GPBMessage

/** 上报间隔 毫秒级 */
@property(nonatomic, readwrite) uint32_t intervals;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
