// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: room.v1.tcp.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class RoomV1DefinitionsAttrClean;
@class RoomV1DefinitionsAttrCleanReply;
@class RoomV1DefinitionsAttrDelete;
@class RoomV1DefinitionsAttrDeleteReply;
@class RoomV1DefinitionsAttrQuery;
@class RoomV1DefinitionsAttrQueryReply;
@class RoomV1DefinitionsAttrQueryReplyKvsArr;
@class RoomV1DefinitionsAttrSet;
@class RoomV1DefinitionsAttrSetKvsArr;
@class RoomV1DefinitionsAttrSetReply;
@class RoomV1DefinitionsEnter;
@class RoomV1DefinitionsEnterReply;
@class RoomV1DefinitionsExit;
@class RoomV1DefinitionsExitReply;
@class RoomV1DefinitionsInfo;
@class RoomV1DefinitionsInfoReply;
@class RoomV1DefinitionsMsgAck;
@class RoomV1DefinitionsMsgAckReply;
@class RoomV1DefinitionsMsgHistory;
@class RoomV1DefinitionsMsgHistoryReply;
@class RoomV1DefinitionsMsgHistoryReplyHistoryArr;
@class RoomV1DefinitionsMsgSend;
@class RoomV1DefinitionsMsgSendPic;
@class RoomV1DefinitionsMsgSendPicReply;
@class RoomV1DefinitionsMsgSendReply;
@class RoomV1DefinitionsMsgSendText;
@class RoomV1DefinitionsMsgSendTextReply;
@class RoomV1DefinitionsWithdraw;
@class RoomV1DefinitionsWithdrawReply;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - RoomV1TcpRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface RoomV1TcpRoot : GPBRootObject
@end

#pragma mark - RoomV1PostAttrCleanRequest

typedef GPB_ENUM(RoomV1PostAttrCleanRequest_FieldNumber) {
  RoomV1PostAttrCleanRequest_FieldNumber_Body = 1,
};

@interface RoomV1PostAttrCleanRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RoomV1DefinitionsAttrClean *body;
/** Test to see if @c body has been set. */
@property(nonatomic, readwrite) BOOL hasBody;

@end

#pragma mark - RoomV1PostAttrDeleteRequest

typedef GPB_ENUM(RoomV1PostAttrDeleteRequest_FieldNumber) {
  RoomV1PostAttrDeleteRequest_FieldNumber_Body = 1,
};

@interface RoomV1PostAttrDeleteRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RoomV1DefinitionsAttrDelete *body;
/** Test to see if @c body has been set. */
@property(nonatomic, readwrite) BOOL hasBody;

@end

#pragma mark - RoomV1PostAttrQueryRequest

typedef GPB_ENUM(RoomV1PostAttrQueryRequest_FieldNumber) {
  RoomV1PostAttrQueryRequest_FieldNumber_Body = 1,
};

@interface RoomV1PostAttrQueryRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RoomV1DefinitionsAttrQuery *body;
/** Test to see if @c body has been set. */
@property(nonatomic, readwrite) BOOL hasBody;

@end

#pragma mark - RoomV1PostAttrSetRequest

typedef GPB_ENUM(RoomV1PostAttrSetRequest_FieldNumber) {
  RoomV1PostAttrSetRequest_FieldNumber_Body = 1,
};

@interface RoomV1PostAttrSetRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RoomV1DefinitionsAttrSet *body;
/** Test to see if @c body has been set. */
@property(nonatomic, readwrite) BOOL hasBody;

@end

#pragma mark - RoomV1PostEnterRequest

typedef GPB_ENUM(RoomV1PostEnterRequest_FieldNumber) {
  RoomV1PostEnterRequest_FieldNumber_Body = 1,
};

@interface RoomV1PostEnterRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RoomV1DefinitionsEnter *body;
/** Test to see if @c body has been set. */
@property(nonatomic, readwrite) BOOL hasBody;

@end

#pragma mark - RoomV1PostExitRequest

typedef GPB_ENUM(RoomV1PostExitRequest_FieldNumber) {
  RoomV1PostExitRequest_FieldNumber_Body = 1,
};

@interface RoomV1PostExitRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RoomV1DefinitionsExit *body;
/** Test to see if @c body has been set. */
@property(nonatomic, readwrite) BOOL hasBody;

@end

#pragma mark - RoomV1PostInfoRequest

typedef GPB_ENUM(RoomV1PostInfoRequest_FieldNumber) {
  RoomV1PostInfoRequest_FieldNumber_Body = 1,
};

@interface RoomV1PostInfoRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RoomV1DefinitionsInfo *body;
/** Test to see if @c body has been set. */
@property(nonatomic, readwrite) BOOL hasBody;

@end

#pragma mark - RoomV1PostMsgAckRequest

typedef GPB_ENUM(RoomV1PostMsgAckRequest_FieldNumber) {
  RoomV1PostMsgAckRequest_FieldNumber_Body = 1,
};

@interface RoomV1PostMsgAckRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RoomV1DefinitionsMsgAck *body;
/** Test to see if @c body has been set. */
@property(nonatomic, readwrite) BOOL hasBody;

@end

#pragma mark - RoomV1PostMsgHistoryRequest

typedef GPB_ENUM(RoomV1PostMsgHistoryRequest_FieldNumber) {
  RoomV1PostMsgHistoryRequest_FieldNumber_Body = 1,
};

@interface RoomV1PostMsgHistoryRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RoomV1DefinitionsMsgHistory *body;
/** Test to see if @c body has been set. */
@property(nonatomic, readwrite) BOOL hasBody;

@end

#pragma mark - RoomV1PostMsgSendPicRequest

typedef GPB_ENUM(RoomV1PostMsgSendPicRequest_FieldNumber) {
  RoomV1PostMsgSendPicRequest_FieldNumber_Body = 1,
};

@interface RoomV1PostMsgSendPicRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RoomV1DefinitionsMsgSendPic *body;
/** Test to see if @c body has been set. */
@property(nonatomic, readwrite) BOOL hasBody;

@end

#pragma mark - RoomV1PostMsgSendRequest

typedef GPB_ENUM(RoomV1PostMsgSendRequest_FieldNumber) {
  RoomV1PostMsgSendRequest_FieldNumber_Body = 1,
};

@interface RoomV1PostMsgSendRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RoomV1DefinitionsMsgSend *body;
/** Test to see if @c body has been set. */
@property(nonatomic, readwrite) BOOL hasBody;

@end

#pragma mark - RoomV1PostMsgSendTextRequest

typedef GPB_ENUM(RoomV1PostMsgSendTextRequest_FieldNumber) {
  RoomV1PostMsgSendTextRequest_FieldNumber_Body = 1,
};

@interface RoomV1PostMsgSendTextRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RoomV1DefinitionsMsgSendText *body;
/** Test to see if @c body has been set. */
@property(nonatomic, readwrite) BOOL hasBody;

@end

#pragma mark - RoomV1PostWithdrawRequest

typedef GPB_ENUM(RoomV1PostWithdrawRequest_FieldNumber) {
  RoomV1PostWithdrawRequest_FieldNumber_Body = 1,
};

@interface RoomV1PostWithdrawRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RoomV1DefinitionsWithdraw *body;
/** Test to see if @c body has been set. */
@property(nonatomic, readwrite) BOOL hasBody;

@end

#pragma mark - RoomV1PostAttrCleanReply

typedef GPB_ENUM(RoomV1PostAttrCleanReply_FieldNumber) {
  RoomV1PostAttrCleanReply_FieldNumber_HTTPCode = 1,
  RoomV1PostAttrCleanReply_FieldNumber_ErrCode = 2,
  RoomV1PostAttrCleanReply_FieldNumber_ErrMsg = 3,
  RoomV1PostAttrCleanReply_FieldNumber_Data_p = 15,
};

@interface RoomV1PostAttrCleanReply : GPBMessage

@property(nonatomic, readwrite) uint32_t HTTPCode;

@property(nonatomic, readwrite) uint32_t errCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errMsg;

@property(nonatomic, readwrite, strong, null_resettable) RoomV1DefinitionsAttrCleanReply *data_p;
/** Test to see if @c data_p has been set. */
@property(nonatomic, readwrite) BOOL hasData_p;

@end

#pragma mark - RoomV1PostAttrDeleteReply

typedef GPB_ENUM(RoomV1PostAttrDeleteReply_FieldNumber) {
  RoomV1PostAttrDeleteReply_FieldNumber_HTTPCode = 1,
  RoomV1PostAttrDeleteReply_FieldNumber_ErrCode = 2,
  RoomV1PostAttrDeleteReply_FieldNumber_ErrMsg = 3,
  RoomV1PostAttrDeleteReply_FieldNumber_Data_p = 15,
};

@interface RoomV1PostAttrDeleteReply : GPBMessage

@property(nonatomic, readwrite) uint32_t HTTPCode;

@property(nonatomic, readwrite) uint32_t errCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errMsg;

@property(nonatomic, readwrite, strong, null_resettable) RoomV1DefinitionsAttrDeleteReply *data_p;
/** Test to see if @c data_p has been set. */
@property(nonatomic, readwrite) BOOL hasData_p;

@end

#pragma mark - RoomV1PostAttrQueryReply

typedef GPB_ENUM(RoomV1PostAttrQueryReply_FieldNumber) {
  RoomV1PostAttrQueryReply_FieldNumber_HTTPCode = 1,
  RoomV1PostAttrQueryReply_FieldNumber_ErrCode = 2,
  RoomV1PostAttrQueryReply_FieldNumber_ErrMsg = 3,
  RoomV1PostAttrQueryReply_FieldNumber_Data_p = 15,
};

@interface RoomV1PostAttrQueryReply : GPBMessage

@property(nonatomic, readwrite) uint32_t HTTPCode;

@property(nonatomic, readwrite) uint32_t errCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errMsg;

@property(nonatomic, readwrite, strong, null_resettable) RoomV1DefinitionsAttrQueryReply *data_p;
/** Test to see if @c data_p has been set. */
@property(nonatomic, readwrite) BOOL hasData_p;

@end

#pragma mark - RoomV1PostAttrSetReply

typedef GPB_ENUM(RoomV1PostAttrSetReply_FieldNumber) {
  RoomV1PostAttrSetReply_FieldNumber_HTTPCode = 1,
  RoomV1PostAttrSetReply_FieldNumber_ErrCode = 2,
  RoomV1PostAttrSetReply_FieldNumber_ErrMsg = 3,
  RoomV1PostAttrSetReply_FieldNumber_Data_p = 15,
};

@interface RoomV1PostAttrSetReply : GPBMessage

@property(nonatomic, readwrite) uint32_t HTTPCode;

@property(nonatomic, readwrite) uint32_t errCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errMsg;

@property(nonatomic, readwrite, strong, null_resettable) RoomV1DefinitionsAttrSetReply *data_p;
/** Test to see if @c data_p has been set. */
@property(nonatomic, readwrite) BOOL hasData_p;

@end

#pragma mark - RoomV1PostEnterReply

typedef GPB_ENUM(RoomV1PostEnterReply_FieldNumber) {
  RoomV1PostEnterReply_FieldNumber_HTTPCode = 1,
  RoomV1PostEnterReply_FieldNumber_ErrCode = 2,
  RoomV1PostEnterReply_FieldNumber_ErrMsg = 3,
  RoomV1PostEnterReply_FieldNumber_Data_p = 15,
};

@interface RoomV1PostEnterReply : GPBMessage

@property(nonatomic, readwrite) uint32_t HTTPCode;

@property(nonatomic, readwrite) uint32_t errCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errMsg;

@property(nonatomic, readwrite, strong, null_resettable) RoomV1DefinitionsEnterReply *data_p;
/** Test to see if @c data_p has been set. */
@property(nonatomic, readwrite) BOOL hasData_p;

@end

#pragma mark - RoomV1PostExitReply

typedef GPB_ENUM(RoomV1PostExitReply_FieldNumber) {
  RoomV1PostExitReply_FieldNumber_HTTPCode = 1,
  RoomV1PostExitReply_FieldNumber_ErrCode = 2,
  RoomV1PostExitReply_FieldNumber_ErrMsg = 3,
  RoomV1PostExitReply_FieldNumber_Data_p = 15,
};

@interface RoomV1PostExitReply : GPBMessage

@property(nonatomic, readwrite) uint32_t HTTPCode;

@property(nonatomic, readwrite) uint32_t errCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errMsg;

@property(nonatomic, readwrite, strong, null_resettable) RoomV1DefinitionsExitReply *data_p;
/** Test to see if @c data_p has been set. */
@property(nonatomic, readwrite) BOOL hasData_p;

@end

#pragma mark - RoomV1PostInfoReply

typedef GPB_ENUM(RoomV1PostInfoReply_FieldNumber) {
  RoomV1PostInfoReply_FieldNumber_HTTPCode = 1,
  RoomV1PostInfoReply_FieldNumber_ErrCode = 2,
  RoomV1PostInfoReply_FieldNumber_ErrMsg = 3,
  RoomV1PostInfoReply_FieldNumber_Data_p = 15,
};

@interface RoomV1PostInfoReply : GPBMessage

@property(nonatomic, readwrite) uint32_t HTTPCode;

@property(nonatomic, readwrite) uint32_t errCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errMsg;

@property(nonatomic, readwrite, strong, null_resettable) RoomV1DefinitionsInfoReply *data_p;
/** Test to see if @c data_p has been set. */
@property(nonatomic, readwrite) BOOL hasData_p;

@end

#pragma mark - RoomV1PostMsgAckReply

typedef GPB_ENUM(RoomV1PostMsgAckReply_FieldNumber) {
  RoomV1PostMsgAckReply_FieldNumber_HTTPCode = 1,
  RoomV1PostMsgAckReply_FieldNumber_ErrCode = 2,
  RoomV1PostMsgAckReply_FieldNumber_ErrMsg = 3,
  RoomV1PostMsgAckReply_FieldNumber_Data_p = 15,
};

@interface RoomV1PostMsgAckReply : GPBMessage

@property(nonatomic, readwrite) uint32_t HTTPCode;

@property(nonatomic, readwrite) uint32_t errCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errMsg;

@property(nonatomic, readwrite, strong, null_resettable) RoomV1DefinitionsMsgAckReply *data_p;
/** Test to see if @c data_p has been set. */
@property(nonatomic, readwrite) BOOL hasData_p;

@end

#pragma mark - RoomV1PostMsgHistoryReply

typedef GPB_ENUM(RoomV1PostMsgHistoryReply_FieldNumber) {
  RoomV1PostMsgHistoryReply_FieldNumber_HTTPCode = 1,
  RoomV1PostMsgHistoryReply_FieldNumber_ErrCode = 2,
  RoomV1PostMsgHistoryReply_FieldNumber_ErrMsg = 3,
  RoomV1PostMsgHistoryReply_FieldNumber_Data_p = 15,
};

@interface RoomV1PostMsgHistoryReply : GPBMessage

@property(nonatomic, readwrite) uint32_t HTTPCode;

@property(nonatomic, readwrite) uint32_t errCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errMsg;

@property(nonatomic, readwrite, strong, null_resettable) RoomV1DefinitionsMsgHistoryReply *data_p;
/** Test to see if @c data_p has been set. */
@property(nonatomic, readwrite) BOOL hasData_p;

@end

#pragma mark - RoomV1PostMsgSendReply

typedef GPB_ENUM(RoomV1PostMsgSendReply_FieldNumber) {
  RoomV1PostMsgSendReply_FieldNumber_HTTPCode = 1,
  RoomV1PostMsgSendReply_FieldNumber_ErrCode = 2,
  RoomV1PostMsgSendReply_FieldNumber_ErrMsg = 3,
  RoomV1PostMsgSendReply_FieldNumber_Data_p = 15,
};

@interface RoomV1PostMsgSendReply : GPBMessage

@property(nonatomic, readwrite) uint32_t HTTPCode;

@property(nonatomic, readwrite) uint32_t errCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errMsg;

@property(nonatomic, readwrite, strong, null_resettable) RoomV1DefinitionsMsgSendReply *data_p;
/** Test to see if @c data_p has been set. */
@property(nonatomic, readwrite) BOOL hasData_p;

@end

#pragma mark - RoomV1PostMsgSendPicReply

typedef GPB_ENUM(RoomV1PostMsgSendPicReply_FieldNumber) {
  RoomV1PostMsgSendPicReply_FieldNumber_HTTPCode = 1,
  RoomV1PostMsgSendPicReply_FieldNumber_ErrCode = 2,
  RoomV1PostMsgSendPicReply_FieldNumber_ErrMsg = 3,
  RoomV1PostMsgSendPicReply_FieldNumber_Data_p = 15,
};

@interface RoomV1PostMsgSendPicReply : GPBMessage

@property(nonatomic, readwrite) uint32_t HTTPCode;

@property(nonatomic, readwrite) uint32_t errCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errMsg;

@property(nonatomic, readwrite, strong, null_resettable) RoomV1DefinitionsMsgSendPicReply *data_p;
/** Test to see if @c data_p has been set. */
@property(nonatomic, readwrite) BOOL hasData_p;

@end

#pragma mark - RoomV1PostMsgSendTextReply

typedef GPB_ENUM(RoomV1PostMsgSendTextReply_FieldNumber) {
  RoomV1PostMsgSendTextReply_FieldNumber_HTTPCode = 1,
  RoomV1PostMsgSendTextReply_FieldNumber_ErrCode = 2,
  RoomV1PostMsgSendTextReply_FieldNumber_ErrMsg = 3,
  RoomV1PostMsgSendTextReply_FieldNumber_Data_p = 15,
};

@interface RoomV1PostMsgSendTextReply : GPBMessage

@property(nonatomic, readwrite) uint32_t HTTPCode;

@property(nonatomic, readwrite) uint32_t errCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errMsg;

@property(nonatomic, readwrite, strong, null_resettable) RoomV1DefinitionsMsgSendTextReply *data_p;
/** Test to see if @c data_p has been set. */
@property(nonatomic, readwrite) BOOL hasData_p;

@end

#pragma mark - RoomV1PostWithdrawReply

typedef GPB_ENUM(RoomV1PostWithdrawReply_FieldNumber) {
  RoomV1PostWithdrawReply_FieldNumber_HTTPCode = 1,
  RoomV1PostWithdrawReply_FieldNumber_ErrCode = 2,
  RoomV1PostWithdrawReply_FieldNumber_ErrMsg = 3,
  RoomV1PostWithdrawReply_FieldNumber_Data_p = 15,
};

@interface RoomV1PostWithdrawReply : GPBMessage

@property(nonatomic, readwrite) uint32_t HTTPCode;

@property(nonatomic, readwrite) uint32_t errCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errMsg;

@property(nonatomic, readwrite, strong, null_resettable) RoomV1DefinitionsWithdrawReply *data_p;
/** Test to see if @c data_p has been set. */
@property(nonatomic, readwrite) BOOL hasData_p;

@end

#pragma mark - RoomV1DefinitionsAttrClean

typedef GPB_ENUM(RoomV1DefinitionsAttrClean_FieldNumber) {
  RoomV1DefinitionsAttrClean_FieldNumber_Roomid = 1,
  RoomV1DefinitionsAttrClean_FieldNumber_Broadcast = 2,
};

@interface RoomV1DefinitionsAttrClean : GPBMessage

/** 房间ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *roomid;

/** 是否广播 */
@property(nonatomic, readwrite) BOOL broadcast;

@end

#pragma mark - RoomV1DefinitionsAttrCleanReply

@interface RoomV1DefinitionsAttrCleanReply : GPBMessage

@end

#pragma mark - RoomV1DefinitionsAttrDelete

typedef GPB_ENUM(RoomV1DefinitionsAttrDelete_FieldNumber) {
  RoomV1DefinitionsAttrDelete_FieldNumber_Roomid = 1,
  RoomV1DefinitionsAttrDelete_FieldNumber_KeysArray = 2,
  RoomV1DefinitionsAttrDelete_FieldNumber_Broadcast = 3,
};

@interface RoomV1DefinitionsAttrDelete : GPBMessage

/** 房间ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *roomid;

/** 属性key列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *keysArray;
/** The number of items in @c keysArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger keysArray_Count;

/** 是否广播 */
@property(nonatomic, readwrite) BOOL broadcast;

@end

#pragma mark - RoomV1DefinitionsAttrDeleteReply

@interface RoomV1DefinitionsAttrDeleteReply : GPBMessage

@end

#pragma mark - RoomV1DefinitionsAttrQuery

typedef GPB_ENUM(RoomV1DefinitionsAttrQuery_FieldNumber) {
  RoomV1DefinitionsAttrQuery_FieldNumber_Roomid = 1,
  RoomV1DefinitionsAttrQuery_FieldNumber_KeysArray = 2,
};

@interface RoomV1DefinitionsAttrQuery : GPBMessage

/** 房间ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *roomid;

/** 属性key */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *keysArray;
/** The number of items in @c keysArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger keysArray_Count;

@end

#pragma mark - RoomV1DefinitionsAttrQueryReply

typedef GPB_ENUM(RoomV1DefinitionsAttrQueryReply_FieldNumber) {
  RoomV1DefinitionsAttrQueryReply_FieldNumber_Roomid = 1,
  RoomV1DefinitionsAttrQueryReply_FieldNumber_KvsArray = 2,
};

@interface RoomV1DefinitionsAttrQueryReply : GPBMessage

/** 房间ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *roomid;

/** 属性kv对列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<RoomV1DefinitionsAttrQueryReplyKvsArr*> *kvsArray;
/** The number of items in @c kvsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger kvsArray_Count;

@end

#pragma mark - RoomV1DefinitionsAttrQueryReplyKvsArr

typedef GPB_ENUM(RoomV1DefinitionsAttrQueryReplyKvsArr_FieldNumber) {
  RoomV1DefinitionsAttrQueryReplyKvsArr_FieldNumber_Key = 1,
  RoomV1DefinitionsAttrQueryReplyKvsArr_FieldNumber_Value = 2,
};

@interface RoomV1DefinitionsAttrQueryReplyKvsArr : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *key;

@property(nonatomic, readwrite, copy, null_resettable) NSString *value;

@end

#pragma mark - RoomV1DefinitionsAttrSet

typedef GPB_ENUM(RoomV1DefinitionsAttrSet_FieldNumber) {
  RoomV1DefinitionsAttrSet_FieldNumber_Roomid = 1,
  RoomV1DefinitionsAttrSet_FieldNumber_KvsArray = 2,
  RoomV1DefinitionsAttrSet_FieldNumber_Broadcast = 3,
};

@interface RoomV1DefinitionsAttrSet : GPBMessage

/** 房间ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *roomid;

/** 属性kv对列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<RoomV1DefinitionsAttrSetKvsArr*> *kvsArray;
/** The number of items in @c kvsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger kvsArray_Count;

/** 是否广播 */
@property(nonatomic, readwrite) BOOL broadcast;

@end

#pragma mark - RoomV1DefinitionsAttrSetKvsArr

typedef GPB_ENUM(RoomV1DefinitionsAttrSetKvsArr_FieldNumber) {
  RoomV1DefinitionsAttrSetKvsArr_FieldNumber_Key = 1,
  RoomV1DefinitionsAttrSetKvsArr_FieldNumber_Value = 2,
};

@interface RoomV1DefinitionsAttrSetKvsArr : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *key;

@property(nonatomic, readwrite, copy, null_resettable) NSString *value;

@end

#pragma mark - RoomV1DefinitionsAttrSetReply

@interface RoomV1DefinitionsAttrSetReply : GPBMessage

@end

#pragma mark - RoomV1DefinitionsBaseMessage

typedef GPB_ENUM(RoomV1DefinitionsBaseMessage_FieldNumber) {
  RoomV1DefinitionsBaseMessage_FieldNumber_Type = 1,
  RoomV1DefinitionsBaseMessage_FieldNumber_Message = 3,
  RoomV1DefinitionsBaseMessage_FieldNumber_StrMessage = 4,
  RoomV1DefinitionsBaseMessage_FieldNumber_Bextra = 5,
  RoomV1DefinitionsBaseMessage_FieldNumber_Sextra = 6,
  RoomV1DefinitionsBaseMessage_FieldNumber_Iextra = 7,
};

@interface RoomV1DefinitionsBaseMessage : GPBMessage

/** 聊天消息类型：文本，图片，定位等等，参考消息传输协议中的聊天消息定义类型 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *type;

/** pb消息内容消息内容 */
@property(nonatomic, readwrite, copy, null_resettable) NSData *message;

/** json消息内容 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *strMessage;

/** json字节流需要base64序列化 */
@property(nonatomic, readwrite, copy, null_resettable) NSData *bextra;

/** 字符串类型额外信息 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *sextra;

/** 数字类型额外信息 */
@property(nonatomic, readwrite) int64_t iextra;

@end

#pragma mark - RoomV1DefinitionsBaseMessageReply

typedef GPB_ENUM(RoomV1DefinitionsBaseMessageReply_FieldNumber) {
  RoomV1DefinitionsBaseMessageReply_FieldNumber_Cliid = 1,
  RoomV1DefinitionsBaseMessageReply_FieldNumber_Srvid = 2,
};

@interface RoomV1DefinitionsBaseMessageReply : GPBMessage

/** 客户端消息id */
@property(nonatomic, readwrite) uint32_t cliid;

/** 服务器消息id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *srvid;

@end

#pragma mark - RoomV1DefinitionsEnter

typedef GPB_ENUM(RoomV1DefinitionsEnter_FieldNumber) {
  RoomV1DefinitionsEnter_FieldNumber_Roomid = 1,
};

@interface RoomV1DefinitionsEnter : GPBMessage

/** 房间ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *roomid;

@end

#pragma mark - RoomV1DefinitionsEnterReply

@interface RoomV1DefinitionsEnterReply : GPBMessage

@end

#pragma mark - RoomV1DefinitionsExit

typedef GPB_ENUM(RoomV1DefinitionsExit_FieldNumber) {
  RoomV1DefinitionsExit_FieldNumber_Roomid = 1,
};

@interface RoomV1DefinitionsExit : GPBMessage

/** 房间ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *roomid;

@end

#pragma mark - RoomV1DefinitionsExitReply

@interface RoomV1DefinitionsExitReply : GPBMessage

@end

#pragma mark - RoomV1DefinitionsInfo

typedef GPB_ENUM(RoomV1DefinitionsInfo_FieldNumber) {
  RoomV1DefinitionsInfo_FieldNumber_Roomid = 1,
};

@interface RoomV1DefinitionsInfo : GPBMessage

/** 房间ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *roomid;

@end

#pragma mark - RoomV1DefinitionsInfoReply

typedef GPB_ENUM(RoomV1DefinitionsInfoReply_FieldNumber) {
  RoomV1DefinitionsInfoReply_FieldNumber_Roomid = 1,
  RoomV1DefinitionsInfoReply_FieldNumber_Name = 2,
  RoomV1DefinitionsInfoReply_FieldNumber_CoverImg = 3,
  RoomV1DefinitionsInfoReply_FieldNumber_StartTime = 4,
  RoomV1DefinitionsInfoReply_FieldNumber_EndTime = 5,
  RoomV1DefinitionsInfoReply_FieldNumber_OriginId = 7,
  RoomV1DefinitionsInfoReply_FieldNumber_ParentId = 8,
};

@interface RoomV1DefinitionsInfoReply : GPBMessage

/** 房间ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *roomid;

/** 房间名 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** 房间头像地址 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *coverImg;

/** 开始时间 */
@property(nonatomic, readwrite) int64_t startTime;

/** 结束时间 */
@property(nonatomic, readwrite) int64_t endTime;

/** 分组房间源教室ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *originId;

/** 分组房间父教室ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *parentId;

@end

#pragma mark - RoomV1DefinitionsMsgAck

typedef GPB_ENUM(RoomV1DefinitionsMsgAck_FieldNumber) {
  RoomV1DefinitionsMsgAck_FieldNumber_Roomid = 1,
  RoomV1DefinitionsMsgAck_FieldNumber_Msgid = 2,
};

@interface RoomV1DefinitionsMsgAck : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *roomid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *msgid;

@end

#pragma mark - RoomV1DefinitionsMsgAckReply

typedef GPB_ENUM(RoomV1DefinitionsMsgAckReply_FieldNumber) {
  RoomV1DefinitionsMsgAckReply_FieldNumber_Code = 1,
};

@interface RoomV1DefinitionsMsgAckReply : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *code;

@end

#pragma mark - RoomV1DefinitionsMsgHistory

typedef GPB_ENUM(RoomV1DefinitionsMsgHistory_FieldNumber) {
  RoomV1DefinitionsMsgHistory_FieldNumber_Roomid = 1,
};

@interface RoomV1DefinitionsMsgHistory : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *roomid;

@end

#pragma mark - RoomV1DefinitionsMsgHistoryReply

typedef GPB_ENUM(RoomV1DefinitionsMsgHistoryReply_FieldNumber) {
  RoomV1DefinitionsMsgHistoryReply_FieldNumber_HistoryArray = 1,
};

@interface RoomV1DefinitionsMsgHistoryReply : GPBMessage

/** 消息历史列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<RoomV1DefinitionsMsgHistoryReplyHistoryArr*> *historyArray;
/** The number of items in @c historyArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger historyArray_Count;

@end

#pragma mark - RoomV1DefinitionsMsgHistoryReplyHistoryArr

typedef GPB_ENUM(RoomV1DefinitionsMsgHistoryReplyHistoryArr_FieldNumber) {
  RoomV1DefinitionsMsgHistoryReplyHistoryArr_FieldNumber_Type = 1,
  RoomV1DefinitionsMsgHistoryReplyHistoryArr_FieldNumber_ContentType = 2,
  RoomV1DefinitionsMsgHistoryReplyHistoryArr_FieldNumber_Message = 3,
  RoomV1DefinitionsMsgHistoryReplyHistoryArr_FieldNumber_Bextra = 5,
  RoomV1DefinitionsMsgHistoryReplyHistoryArr_FieldNumber_Sextra = 6,
  RoomV1DefinitionsMsgHistoryReplyHistoryArr_FieldNumber_Iextra = 7,
  RoomV1DefinitionsMsgHistoryReplyHistoryArr_FieldNumber_Roomid = 10,
  RoomV1DefinitionsMsgHistoryReplyHistoryArr_FieldNumber_Uid = 11,
  RoomV1DefinitionsMsgHistoryReplyHistoryArr_FieldNumber_Msgid = 12,
  RoomV1DefinitionsMsgHistoryReplyHistoryArr_FieldNumber_SendTime = 13,
};

@interface RoomV1DefinitionsMsgHistoryReplyHistoryArr : GPBMessage

/** 聊天消息类型：文本，图片，定位等等，参考消息传输协议中的聊天消息定义类型 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *type;

/** 消息序列化类型 */
@property(nonatomic, readwrite) uint32_t contentType;

/** pb消息内容消息内容 */
@property(nonatomic, readwrite, copy, null_resettable) NSData *message;

/** json字节流需要base64序列化 */
@property(nonatomic, readwrite, copy, null_resettable) NSData *bextra;

/** 字符串类型额外信息 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *sextra;

/** 数字类型额外信息 */
@property(nonatomic, readwrite) int64_t iextra;

/** 需要发送聊天的房间 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *roomid;

/** 发送者ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *uid;

/** 消息id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *msgid;

/** 发送时间 */
@property(nonatomic, readwrite) int64_t sendTime;

@end

#pragma mark - RoomV1DefinitionsMsgSend

typedef GPB_ENUM(RoomV1DefinitionsMsgSend_FieldNumber) {
  RoomV1DefinitionsMsgSend_FieldNumber_Type = 1,
  RoomV1DefinitionsMsgSend_FieldNumber_Message = 3,
  RoomV1DefinitionsMsgSend_FieldNumber_StrMessage = 4,
  RoomV1DefinitionsMsgSend_FieldNumber_Bextra = 5,
  RoomV1DefinitionsMsgSend_FieldNumber_Sextra = 6,
  RoomV1DefinitionsMsgSend_FieldNumber_Iextra = 7,
  RoomV1DefinitionsMsgSend_FieldNumber_Roomid = 10,
  RoomV1DefinitionsMsgSend_FieldNumber_Cliid = 11,
};

@interface RoomV1DefinitionsMsgSend : GPBMessage

/** 聊天消息类型：文本，图片，定位等等，参考消息传输协议中的聊天消息定义类型 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *type;

/** pb消息内容消息内容 */
@property(nonatomic, readwrite, copy, null_resettable) NSData *message;

/** json消息内容 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *strMessage;

/** json字节流需要base64序列化 */
@property(nonatomic, readwrite, copy, null_resettable) NSData *bextra;

/** 字符串类型额外信息 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *sextra;

/** 数字类型额外信息 */
@property(nonatomic, readwrite) int64_t iextra;

/** 需要发送聊天的房间 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *roomid;

/** 客户端消息ID */
@property(nonatomic, readwrite) uint32_t cliid;

@end

#pragma mark - RoomV1DefinitionsMsgSendPic

typedef GPB_ENUM(RoomV1DefinitionsMsgSendPic_FieldNumber) {
  RoomV1DefinitionsMsgSendPic_FieldNumber_Roomid = 10,
  RoomV1DefinitionsMsgSendPic_FieldNumber_Cliid = 11,
  RoomV1DefinitionsMsgSendPic_FieldNumber_Content = 12,
  RoomV1DefinitionsMsgSendPic_FieldNumber_Uri = 13,
  RoomV1DefinitionsMsgSendPic_FieldNumber_BExtra = 14,
  RoomV1DefinitionsMsgSendPic_FieldNumber_SExtra = 15,
  RoomV1DefinitionsMsgSendPic_FieldNumber_IExtra = 16,
};

@interface RoomV1DefinitionsMsgSendPic : GPBMessage

/** 需要发送聊天的房间 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *roomid;

/** 客户端消息ID */
@property(nonatomic, readwrite) uint32_t cliid;

/** 消息内容 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

/** 消息选项 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *uri;

/** 字节流额外信息 */
@property(nonatomic, readwrite, copy, null_resettable) NSData *bExtra;

/** 字符串额外信息 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *sExtra;

/** 数字额外信息 */
@property(nonatomic, readwrite) int64_t iExtra;

@end

#pragma mark - RoomV1DefinitionsMsgSendPicReply

typedef GPB_ENUM(RoomV1DefinitionsMsgSendPicReply_FieldNumber) {
  RoomV1DefinitionsMsgSendPicReply_FieldNumber_Cliid = 1,
  RoomV1DefinitionsMsgSendPicReply_FieldNumber_Srvid = 2,
};

@interface RoomV1DefinitionsMsgSendPicReply : GPBMessage

/** 客户端消息id */
@property(nonatomic, readwrite) uint32_t cliid;

/** 服务器消息id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *srvid;

@end

#pragma mark - RoomV1DefinitionsMsgSendReply

typedef GPB_ENUM(RoomV1DefinitionsMsgSendReply_FieldNumber) {
  RoomV1DefinitionsMsgSendReply_FieldNumber_Cliid = 1,
  RoomV1DefinitionsMsgSendReply_FieldNumber_Srvid = 2,
};

@interface RoomV1DefinitionsMsgSendReply : GPBMessage

/** 客户端消息id */
@property(nonatomic, readwrite) uint32_t cliid;

/** 服务器消息id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *srvid;

@end

#pragma mark - RoomV1DefinitionsMsgSendText

typedef GPB_ENUM(RoomV1DefinitionsMsgSendText_FieldNumber) {
  RoomV1DefinitionsMsgSendText_FieldNumber_Roomid = 10,
  RoomV1DefinitionsMsgSendText_FieldNumber_Cliid = 11,
  RoomV1DefinitionsMsgSendText_FieldNumber_Message = 12,
  RoomV1DefinitionsMsgSendText_FieldNumber_Option = 13,
  RoomV1DefinitionsMsgSendText_FieldNumber_BExtra = 14,
  RoomV1DefinitionsMsgSendText_FieldNumber_SExtra = 15,
  RoomV1DefinitionsMsgSendText_FieldNumber_IExtra = 16,
};

@interface RoomV1DefinitionsMsgSendText : GPBMessage

/** 需要发送聊天的房间 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *roomid;

/** 客户端消息ID */
@property(nonatomic, readwrite) uint32_t cliid;

/** 消息内容 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *message;

/** 消息选项 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *option;

/** 字节流额外信息 */
@property(nonatomic, readwrite, copy, null_resettable) NSData *bExtra;

/** 字符串额外信息 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *sExtra;

/** 数字额外信息 */
@property(nonatomic, readwrite) int64_t iExtra;

@end

#pragma mark - RoomV1DefinitionsMsgSendTextReply

typedef GPB_ENUM(RoomV1DefinitionsMsgSendTextReply_FieldNumber) {
  RoomV1DefinitionsMsgSendTextReply_FieldNumber_Cliid = 1,
  RoomV1DefinitionsMsgSendTextReply_FieldNumber_Srvid = 2,
};

@interface RoomV1DefinitionsMsgSendTextReply : GPBMessage

/** 客户端消息id */
@property(nonatomic, readwrite) uint32_t cliid;

/** 服务器消息id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *srvid;

@end

#pragma mark - RoomV1DefinitionsSimpleMsg

typedef GPB_ENUM(RoomV1DefinitionsSimpleMsg_FieldNumber) {
  RoomV1DefinitionsSimpleMsg_FieldNumber_Roomid = 10,
  RoomV1DefinitionsSimpleMsg_FieldNumber_Cliid = 11,
  RoomV1DefinitionsSimpleMsg_FieldNumber_BExtra = 14,
  RoomV1DefinitionsSimpleMsg_FieldNumber_SExtra = 15,
  RoomV1DefinitionsSimpleMsg_FieldNumber_IExtra = 16,
};

@interface RoomV1DefinitionsSimpleMsg : GPBMessage

/** 需要发送聊天的房间 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *roomid;

/** 客户端消息ID */
@property(nonatomic, readwrite) uint32_t cliid;

/** 字节流额外信息 */
@property(nonatomic, readwrite, copy, null_resettable) NSData *bExtra;

/** 字符串额外信息 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *sExtra;

/** 数字额外信息 */
@property(nonatomic, readwrite) int64_t iExtra;

@end

#pragma mark - RoomV1DefinitionsWithdraw

typedef GPB_ENUM(RoomV1DefinitionsWithdraw_FieldNumber) {
  RoomV1DefinitionsWithdraw_FieldNumber_Roomid = 1,
  RoomV1DefinitionsWithdraw_FieldNumber_MsgidsArray = 2,
};

@interface RoomV1DefinitionsWithdraw : GPBMessage

/** 房间消息 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *roomid;

/** 消息ID列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *msgidsArray;
/** The number of items in @c msgidsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger msgidsArray_Count;

@end

#pragma mark - RoomV1DefinitionsWithdrawReply

@interface RoomV1DefinitionsWithdrawReply : GPBMessage

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
